[ImageContainer]
Hidden=1
[Image]
Hidden=1

[Title.2_5]
Meter=String
Text="Change log v2.5"
MeterStyle=Sec.String:S | Style.Title:S

[Description.2_5.0]
Meter=String
Text="• Added option to change time format#CRLF#• Added options to toggle leading zero and time to Smart#CRLF#• Added options to change zero text to Light and Text"
MeterStyle=Sec.String:S | Style.Description:S

[Title.2_42]
Meter=String
Y=(#Sec.P#)R
Text="Change log v2.42"
MeterStyle=Sec.String:S | Style.Title:S

[Description.2_42.0]
Meter=String
Text="• New style - 16!#CRLF#• Added ImageMagick reminder#CRLF#• QoL UI changes#CRLF#• Reduced package size"
MeterStyle=Sec.String:S | Style.Description:S

[Title.2_3]
Meter=String
Text="Change log v2.3"
Y=(#Sec.P#)R
MeterStyle=Sec.String:S | Style.Title:S

[Description.2_3.0]
Meter=String
Text="• Updated all settings UI#CRLF#• Graph style is now an analog clock instead of a weird graph#CRLF#• More options for classical ModularClock styles"
MeterStyle=Sec.String:S | Style.Description:S
