[@Resources\Vars.inc]
name_width=200
IconTheme=Material
SliderStyle=CoreUI
BackgroundMod=1
MixerIcon=1

Accent=242, 52, 0
AccentNode=242,52,0
AccentNodeHover=255,175,153
Alpha=255
background_color=12,12,12
Border=28,28,28
FontColor=242,240,255
VolumePeakColor=77,77,77
BackVolColorOver=35,35,35
BackVolColorLeave=35,35,35

[Main\Elements\Unload\Vars.inc]
Blur=Acrylic
SolidColor=0,0,0
SolidOpacity=50
