[@Resources\Vars.inc]
name_width=100
IconTheme=Material
Position=CC
BackgroundMod=1
DisplayName=0
MixerIcon=1

Accent=137,220,235
AccentNode=35,159,255
AccentNodeHover=255,255,255
Alpha=0
background_color=12,12,12
Border=196,196,196
FontColor=242,240,255
VolumePeakColor=255,255,255
BackVolColorOver=35,35,35
BackVolColorLeave=145,145,145

[Main\Elements\Unload\Vars.inc]
Blur=Acrylic
SolidColor=0,0,0
SolidOpacity=150
