[Rainmeter]
Update=-1
DefaultUpdateDivider=-1
DynamicWindowSize=1
OnRefreshAction=[!DeactivateConfig "#MosaicShell\Main"][!DeactivateConfig "#MosaicShell\Accessories\GenericInteractionBox"][!SetWindowPosition 50% 50% 50% 50%]
DefaultAlwaysOnTop=1
DefaultDraggable=0
DefaultKeepOnscreen=0
SkinWidth=(#Sec.W#)
SkinHeight=(#Sec.H#)

[Focus]
Measure=Plugin
Plugin=Focus
FocusOnRefresh=1

[Variables]
@includeVars=#@#Vars.inc
@includeCorever=#@#Version.inc

Sec.S=((#SCREENAREAWIDTH#/1920) < (#SCREENAREAHEIGHT#/1080) ? (#SCREENAREAWIDTH#/1920) : (#SCREENAREAHEIGHT#/1080))
Sec.W=(500*#Sec.S#)
Sec.H=(700*#Sec.S#)
Sec.P=(20*#Sec.S#)
Sec.R=(10*#Sec.S#)
Log=Initialize...
SkipTrans=0

; ---------------------------------------------------------------------------- ;
;                                   Function                                   ;
; ---------------------------------------------------------------------------- ;

[MeasurePSVer]
Measure=Plugin
Plugin=RunCommand
Program=PowerShell
Parameter=$a=($PSVersionTable.PSVersion); \"$($a.Major).$($a.Minor)\"
OutputType=ANSI
OnUpdateAction=[!CommandMeasure MeasurePSVer "Run"]
FinishAction=[!CommandMeasure ScriptLua "checkPS()"]
State=Hide
Disabled=1

[p.SysInfo.USER_NAME]
Measure=Plugin
Plugin=SysInfo
SysInfoType=USER_NAME
UpdateDivider=-1
OnUpdateAction=[!CommandMeasure ScriptLua "checkNAME()"]
Disabled=1

[ScriptLua]
Measure=Script
ScriptFile=#ROOTCONFIGPATH#Main\Installation\Script.lua

[Func]
Measure=script
ScriptFile=#@#Lua\Func.lua

; ---------------------------------------------------------------------------- ;
;                                  MeterStyles                                 ;
; ---------------------------------------------------------------------------- ;

[Sec.String:S]
FontFace=#Set.Font#
AntiAlias=1
FontSize=(10*#Sec.s#)
clipstring=2
FontColor=#Set.Text_Color#
SolidColor=0,0,0,1

[Sec.Button:S]
X=((150/2)*#Sec.S#+#Sec.P#)r
Y=(-40/2*#Sec.S#)r
Shape=Rectangle 0,0,150,40,#Sec.R# | StrokeWidth 0 | Extend This | Scale #Sec.S#,#Sec.S#
This=fill Color [&Func:LocalVar('#CURRENTSECTION#', 'ColorLeave')]
DynamicVariables=1
MouseOverAction=[!SetOption #CURRENTSECTION# this "Fill Color [&Func:LocalVar('#CURRENTSECTION#', 'ColorOver')]"][!SetOption #Sec.#CURRENTSECTION## FontColor "#Set.Text_Color#"][!UpdateMeter *][!Redraw]
MouseLeaveAction=[!SetOption #CURRENTSECTION# this "Fill Color [&Func:LocalVar('#CURRENTSECTION#', 'ColorLeave')]"][!SetOption #Sec.#CURRENTSECTION## FontColor "#Set.Text_Color#,150"][!UpdateMeter *][!Redraw]
ColorLeave=100,100,100,100
ColorOver=100,100,100,200

[Sec.Text:S]
X=(150/2*#Sec.S#)r
Y=(40/2*#Sec.S#)r
DynamicVariables=1
StringAlign=CenterCenter

; ---------------------------------------------------------------------------- ;
;                                    Content                                   ;
; ---------------------------------------------------------------------------- ;

[B]
Meter = Shape
Shape=Rectangle 0,0,(#Sec.W#),(#Sec.H#),#Set.WinR# | StrokeWidth 0 | Fill Color #Set.Pri_color#,#Set.Alpha#
DynamicVariables=1

[ImgFade]
Meter=Image
X=(#Sec.W#/2-[ImgFade:W]/2)
Y=(#Sec.H#/2-[ImgFade:W]/2)
W=(256*#Sec.S#)
H=([ImgFade:W])
DynamicVariables=1
ImageAlpha=50
ImageName=#@#Images\CoreAssets\LogoIconAccent.png

[LogTitle]
Meter=String
X=(#Sec.P#)
Y=(#Sec.P#)
Text=Verifying installation of Core...
FontWeight=650
FontSize=(15*#Sec.S#)
MeterStyle=Sec.String:S
[LogContainer]
Meter=Shape
X=r
Y=(#Sec.P#)R
Shape=Rectangle 0,0,(#Sec.W#-#Sec.P#*2),(#Sec.H#-#Sec.P#*3-[LogTitle:H]) | StrokeWidth 0 | Fill Color 255,255,255
DynamicVariables=1
[Log]
MEter=String
Text=#Log#
W=(#SEc.W#-#Sec.P#*2)
ClipString=2
Container=LogContainer
Inlinepattern=\[\-\].*
InlineSetting=Color | 255,0,0
Inlinepattern2=\[\+\].*
InlineSetting2=Color | 0,200,0
Inlinepattern3=\[i\].*
InlineSetting3=Color | 74, 139, 245
MeterStyle=SEc.String:S
DynamicVariables=1

[PSButton.Yes:Shape]
Meter=Shape
X=((#Sec.W#)/2-(150*2*#Sec.S#+#sec.P#)/2)
Y=(#Sec.H#-#sec.P#-40*#sec.S#)
ColorLeave=0,100,0,150
ColorOver=0,100,0,250
MeterStyle=Sec.Button:S
Group=PSButton
Hidden=1
[PSButton.Yes:Shape:Cant]
LeftMouseUpAction=[!CommandMeasure ScriptLua "checkTRANS()"]
[PSButton.Yes:Shape:Not]
LeftMouseUpAction=["http://woshub.com/install-update-powershell-windows/"][!CommandMeasure ActionTimer "Execute 2"]
[PSButton.Yes:String]
Meter=String
Text=Continue
Group=PSButton
Hidden=1
MEterStyle=Sec.String:S | Sec.Text:S

[PSButton.No:Shape]
Meter=Shape
LeftMouseUpAction=[!CommandMeasure ActionTimer "Execute 2"]
MeterStyle=Sec.Button:S
Group=PSButton
Hidden=1
[PSButton.No:String]
Meter=String
Text=Quit
Group=PSButton | PSButtonString
Hidden=1
MEterStyle=Sec.String:S | Sec.Text:S


[Esc]
Meter=Shape
DynamicVariables=1
Shape=Ellipse (#Sec.W#-15),(15),(5),(5) | StrokeWidth 10 | StrokeColor 0,0,0,1 | Extend FillE
FillE=Fill Color #Set.Text_Color#,50
MouseOverAction=[!SetOption Esc FillE "Fill Color #Set.Text_Color#"][!UpdateMeter Esc][!Redraw]
MouseLeaveAction=[!SetOption Esc FillE "Fill Color #Set.Text_Color#,50"][!UpdateMeter Esc][!Redraw]
LeftMouseUpAction=[!DeactivateConfig]
Hidden=#Sec.HideEsc#
