[Rainmeter]
Update=-1
DefaultUpdateDivider=-1
DefaultSavePosition=1
DefaultAlwaysOnTop=2
DefaultDraggable=0
DefaultSnapEdges=1
DefaultStartHidden=0
DefaultAlphaValue=255
DefaultHideOnMouseOver=0
DefaultFadeDuration=105
DefaultClickThrough=0
DefaultKeepOnScreen=1
DefaultAutoSelectScreen=0

OnUnfocusAction=[!EnableMeasure mToggle "#MosaicShell\Ctx"][!CommandMeasure Focus "#MosaicShell\Ctx" "#MosaicShell\Ctx"][!CommandMeasure ActionTimer "Execute 2"]

[Focus]
Measure=Plugin
Plugin=Focus
FocusOnRefresh=1

[Variables]
@includeVars=#@#Vars.inc
@includeCacheVarsCtx=#@#CacheVars\Ctx.inc

[ActionTimer]
Measure=Plugin
Plugin=ActionTimer
DynamicVariables=1
ActionList1=Show
ActionList2=Hide | Custom0
Show=[!ShowFade]
HideFade=[!HideFade]
Hide=[!Hide]
Custom0=[!DeactivateConfig]
In=[!CommandMeasure SlideAnimation "tweenAnimation('in')"]
Out=[!CommandMeasure SlideAnimation "tweenAnimation('out')"]


; ---------------------------------------------------------------------------- ;
;                                  MeterStyles                                 ;
; ---------------------------------------------------------------------------- ;

@includeCtxStyles=..\CtxStyles.inc

; ---------------------------------------------------------------------------- ;
;                          Context option meter styles                         ;
; ---------------------------------------------------------------------------- ;

[SlowRefresh:Act]
LeftMouseUpAction=[!DeactivateConfig #Sec.Skin#][!Delay 500][!ActivateConfig #Sec.Skin#]
[SlowRefresh:Text]
Text=SlowRefresh

[RestartRainmeter:Act]
LeftMouseUpAction=[!DeactivateConfig][!DeactivateConfig "#MosaicShell\Ctx"]["#@#Addons\RestartRainmeter.exe"]
[RestartRainmeter:Text]
Text=Reload Rainmeter

;METERSTYLES===========================================================================================
;METERSTYLES===========================================================================================



[SlowRefresh]
Meter=Shape
Y=(#Ctx.P#+1)
MeterStyle=CtxBox:S | SlowRefresh:Act
[SlowRefreshIcon]
Meter=Image
MeterStyle=CtxIcon:S
[SlowRefreshText]
Meter=String
MeterStyle=Ctx.String:S | CtxText:S | SlowRefresh:Text

[RestartRainmeter]
Meter=Shape
MeterStyle=CtxBox:S | RestartRainmeter:Act
[RestartRainmeterIcon]
Meter=Image
MeterStyle=CtxIcon:S
[RestartRainmeterText]
Meter=String
MeterStyle=Ctx.String:S | CtxText:S | RestartRainmeter:Text




[EndAnchor]
Meter=String
X=r
Y=(#Ctx.BoxH#/2*#Ctx.S#)r
