[Rainmeter]
Update=-1
DefaultUpdateDivider=-1
DefaultSavePosition=1
DefaultAlwaysOnTop=2
DefaultDraggable=0
DefaultSnapEdges=1
DefaultStartHidden=0
DefaultAlphaValue=255
DefaultHideOnMouseOver=0
DefaultFadeDuration=105
DefaultClickThrough=0
DefaultKeepOnScreen=1
DefaultAutoSelectScreen=0

OnUnfocusAction=[!EnableMeasure mToggle "#MosaicShell\Ctx"][!CommandMeasure Focus "#MosaicShell\Ctx" "#MosaicShell\Ctx"][!CommandMeasure ActionTimer "Execute 2"]

[Focus]
Measure=Plugin
Plugin=Focus
FocusOnRefresh=1

[Variables]
@includeVars=#@#Vars.inc
@includeCacheVarsCtx=#@#CacheVars\Ctx.inc

[ActionTimer]
Measure=Plugin
Plugin=ActionTimer
DynamicVariables=1
ActionList1=Show
ActionList2=Hide | Custom0
Show=[!ShowFade]
HideFade=[!HideFade]
Hide=[!Hide]
Custom0=[!DeactivateConfig]
In=[!CommandMeasure SlideAnimation "tweenAnimation('in')"]
Out=[!CommandMeasure SlideAnimation "tweenAnimation('out')"]


; ---------------------------------------------------------------------------- ;
;                                  MeterStyles                                 ;
; ---------------------------------------------------------------------------- ;

@includeCtxStyles=..\CtxStyles.inc

; ---------------------------------------------------------------------------- ;
;                          Context option meter styles                         ;
; ---------------------------------------------------------------------------- ;

[Center:Act]
LeftMouseUpAction=[!Move (#SCREENAREAWIDTH#/2-#CCW#/2) (#SCREENAREAHEIGHT#/2-#CCH#/2) "#Sec.Skin#"][!DeactivateConfig]
[Center:Text]
Text=Center
[HoriMiddle:Act]
LeftMouseUpAction=[!Move (#SCREENAREAWIDTH#/2-#CCW#/2) #SKINY# "#Sec.Skin#"][!DeactivateConfig]
[HoriMiddle:Text]
Text=Hortizontally centered
[vertMiddle:Act]
LeftMouseUpAction=[!Move #SKINX# (#SCREENAREAHEIGHT#/2-#CCH#/2) "#Sec.Skin#"][!DeactivateConfig]
[vertMiddle:Text]
Text=Vertically centered
[TopLeft:Act]
LeftMouseUpAction=[!Move 20 20 "#Sec.Skin#"][!DeactivateConfig]
[topLeft:Text]
Text=Top left
[Topright:Act]
LeftMouseUpAction=[!Move (#SCREENAREAWIDTH#-#CCW#-20) 20 "#Sec.Skin#"][!DeactivateConfig]
[TopRight:Text]
Text=Top right
[Bottomleft:Act]
LeftMouseUpAction=[!Move 20 (#SCREENAREAHEIGHT#-#CCH#-20) "#Sec.Skin#"][!DeactivateConfig]
[Bottomleft:Text]
Text=Bottom left
[Bottomright:Act]
LeftMouseUpAction=[!Move (#SCREENAREAWIDTH#-#CCW#-20) (#SCREENAREAHEIGHT#-#CCH#-20) "#Sec.Skin#"][!DeactivateConfig]
[Bottomright:Text]
Text=Bottom right

;METERSTYLES===========================================================================================
;METERSTYLES===========================================================================================



[Center]
Meter=Shape
Y=(#Ctx.P#+1)
MeterStyle=CtxBox:S | Center:Act
[CenterIcon]
Meter=Image
MeterStyle=CtxIcon:S
[CenterText]
Meter=String
MeterStyle=Ctx.String:S | CtxText:S | Center:Text

[HoriMiddle]
Meter=Shape
MeterStyle=CtxBox:S | HoriMiddle:Act
[HoriMiddleIcon]
Meter=Image
MeterStyle=CtxIcon:S
[HoriMiddleText]
Meter=String
MeterStyle=Ctx.String:S | CtxText:S | HoriMiddle:Text

[Vertmiddle]
Meter=Shape
MeterStyle=CtxBox:S | Vertmiddle:Act
[VertmiddleIcon]
Meter=Image
MeterStyle=CtxIcon:S
[VertmiddleText]
Meter=String
MeterStyle=Ctx.String:S | CtxText:S | Vertmiddle:Text

[TopLeft]
Meter=Shape
MeterStyle=CtxBox:S | TopLeft:Act
[TopLeftIcon]
Meter=Image
MeterStyle=CtxIcon:S
[TopLeftText]
Meter=String
MeterStyle=Ctx.String:S | CtxText:S | TopLeft:Text

[topRight]
Meter=Shape
MeterStyle=CtxBox:S | topRight:Act
[topRightIcon]
Meter=Image
MeterStyle=CtxIcon:S
[topRightText]
Meter=String
MeterStyle=Ctx.String:S | CtxText:S | topRight:Text

[Bottomleft]
Meter=Shape
MeterStyle=CtxBox:S | Bottomleft:Act
[BottomleftIcon]
Meter=Image
MeterStyle=CtxIcon:S
[BottomleftText]
Meter=String
MeterStyle=Ctx.String:S | CtxText:S | Bottomleft:Text

[Bottomright]
Meter=Shape
MeterStyle=CtxBox:S | Bottomright:Act
[BottomrightIcon]
Meter=Image
MeterStyle=CtxIcon:S
[BottomrightText]
Meter=String
MeterStyle=Ctx.String:S | CtxText:S | Bottomright:Text



[EndAnchor]
Meter=String
X=r
Y=(#Ctx.BoxH#/2*#Ctx.S#)r
