﻿[Rainmeter]
Update=-1
DefaultUpdateDivider=-1
DefaultSavePosition=1
DefaultAlwaysOnTop=2
DefaultDraggable=0
DefaultSnapEdges=1
DefaultStartHidden=0
DefaultAlphaValue=255
DefaultHideOnMouseOver=0
DefaultFadeDuration=105
DefaultClickThrough=0
DefaultKeepOnScreen=1
DefaultAutoSelectScreen=0

OnUnfocusAction=[!EnableMeasure mToggle "#MosaicShell\Ctx"][!CommandMeasure Focus "#MosaicShell\Ctx" "#MosaicShell\Ctx"][!CommandMeasure ActionTimer "Execute 2"]

[Focus]
Measure=Plugin
Plugin=Focus
FocusOnRefresh=1

[Variables]
@includeVars=#@#Vars.inc
@includeCacheVarsCtx=#@#CacheVars\Ctx.inc

[ActionTimer]
Measure=Plugin
Plugin=ActionTimer
DynamicVariables=1
ActionList1=Show
ActionList2=Hide | Custom0
Show=[!ShowFade]
HideFade=[!HideFade]
Hide=[!Hide]
Custom0=[!DeactivateConfig]
In=[!CommandMeasure SlideAnimation "tweenAnimation('in')"]
Out=[!CommandMeasure SlideAnimation "tweenAnimation('out')"]


; ---------------------------------------------------------------------------- ;
;                                  MeterStyles                                 ;
; ---------------------------------------------------------------------------- ;

@includeCtxStyles=..\CtxStyles.inc

; ---------------------------------------------------------------------------- ;
;                          Context option meter styles                         ;
; ---------------------------------------------------------------------------- ;

[File:Act]
LeftMouseUpAction=["#SKINSPATH#\#Sec.Skin#"]
[File:Text]
Text=Open skin folder

[Dragging:Act]
LeftMouseUpAction=[!Draggable -1 "#Sec.Skin#"]
[Dragging:Text]
Text=Toggle Draggable

[ClickThrough:Act]
LeftMouseUpAction=[!ClickThrough -1 "#Sec.Skin#"]
[ClickThrough:Text]
Text=Toggle ClickThrough

[KeepOnScreen:Act]
LeftMouseUpAction=[!KeepOnScreen -1 "#Sec.Skin#"]
[KeepOnScreen:Text]
Text=Toggle KeepOnScreen

[Edit:Act]
LeftMouseUpAction=[!EditSkin "#Sec.Skin#"]
[Edit:Text]
Text=Edit skin

[Manage:Act]
LeftMouseUpAction=[!Manage "#Sec.Skin#"]
[Manage:Text]
Text=Manage skin

[Logs:Act]
LeftMouseUpAction=[!About]
[Logs:Text]
Text=Logs

[RefreshAll:Act]
LeftMouseUpAction=[!Refreshapp]
[RefreshAll:Text]
Text=Refresh Rainmeter skin list

;METERSTYLES===========================================================================================
;METERSTYLES===========================================================================================



[File]
Meter=Shape
Y=(#Ctx.P#+1)
MeterStyle=CtxBox:S | File:Act
[FileIcon]
Meter=Image
MeterStyle=CtxIcon:S
[FileText]
Meter=String
MeterStyle=Ctx.String:S | CtxText:S | File:Text

[Dragging]
Meter=Shape
Hidden=(#Sec.Ctx.Core#)
MeterStyle=CtxBox:S | Dragging:Act
[DraggingIcon]
Meter=Image
ImageAlpha=(255-105*#Sec.Ctx.Core#)
MeterStyle=CtxIcon:S
[DraggingText]
Meter=String
FontColor=#Set.Text_Color#,(255-105*#Sec.Ctx.Core#)
MeterStyle=Ctx.String:S | CtxText:S | Dragging:Text

[ClickThrough]
Meter=Shape
Hidden=(#Sec.Ctx.Core#)
MeterStyle=CtxBox:S | ClickThrough:Act
[ClickThroughIcon]
Meter=Image
ImageAlpha=(255-105*#Sec.Ctx.Core#)
MeterStyle=CtxIcon:S
[ClickThroughText]
Meter=String
FontColor=#Set.Text_Color#,(255-105*#Sec.Ctx.Core#)
MeterStyle=Ctx.String:S | CtxText:S | ClickThrough:Text

[KeepOnScreen]
Meter=Shape
MeterStyle=CtxBox:S | KeepOnScreen:Act
[KeepOnScreenIcon]
Meter=Image
MeterStyle=CtxIcon:S
[KeepOnScreenText]
Meter=String
MeterStyle=Ctx.String:S | CtxText:S | KeepOnScreen:Text

[Edit]
Meter=Shape
MeterStyle=CtxBox:S | Edit:Act
[EditIcon]
Meter=Image
MeterStyle=CtxIcon:S
[EditText]
Meter=String
MeterStyle=Ctx.String:S | CtxText:S | Edit:Text

[Manage]
Meter=Shape
MeterStyle=CtxBox:S | Manage:Act
[ManageIcon]
Meter=Image
MeterStyle=CtxIcon:S
[ManageText]
Meter=String
MeterStyle=Ctx.String:S | CtxText:S | Manage:Text

[Logs]
Meter=Shape
MeterStyle=CtxBox:S | Logs:Act
[LogsIcon]
Meter=Image
MeterStyle=CtxIcon:S
[LogsText]
Meter=String
MeterStyle=Ctx.String:S | CtxText:S | Logs:Text

[RefreshAll]
Meter=Shape
MeterStyle=CtxBox:S | RefreshAll:Act
[RefreshAllIcon]
Meter=Image
MeterStyle=CtxIcon:S
[RefreshAllText]
Meter=String
MeterStyle=Ctx.String:S | CtxText:S | RefreshAll:Text




[EndAnchor]
Meter=String
X=r
Y=(#Ctx.BoxH#/2*#Ctx.S#)r
