[Rainmeter]
Update=-1
DefaultUpdateDivider=-1
DefaultSavePosition=1
DefaultAlwaysOnTop=2
DefaultDraggable=0
DefaultSnapEdges=1
DefaultStartHidden=0
DefaultAlphaValue=255
DefaultHideOnMouseOver=0
DefaultFadeDuration=105
DefaultClickThrough=0
DefaultKeepOnScreen=1
DefaultAutoSelectScreen=0

OnUnfocusAction=[!EnableMeasure mToggle "#MosaicShell\Ctx"][!CommandMeasure Focus "#MosaicShell\Ctx" "#MosaicShell\Ctx"][!CommandMeasure ActionTimer "Execute 2"]

[Focus]
Measure=Plugin
Plugin=Focus
FocusOnRefresh=1

[Variables]
@includeVars=#@#Vars.inc
Sec.Skin=Chrono\Main

Ctx.LastX=1218
Ctx.LastY=450

Ctx.BoxH=(30*#Ctx.S#)
; Ctx.S=0.7
Ctx.S=#UiScale#
Ctx.W=(250*#Ctx.S#)
Ctx.P=(10*#Ctx.S#)
Ctx.H=([EndAnchor:Y]+#Ctx.P#)
Ctx.R=(5*#Ctx.S#)

Easetype=InOutSine
Animation_Steps=10
Animate_Offset=10
AniDir=Top
Ctx.LastXA=0
Ctx.LastYA=0

[ActionTimer]
Measure=Plugin
Plugin=ActionTimer
DynamicVariables=1
ActionList1=Show
ActionList2=Hide | Custom0
Show=[!ShowFade]
HideFade=[!HideFade]
Hide=[!Hide]
Custom0=[!DeactivateConfig]
In=[!CommandMeasure SlideAnimation "tweenAnimation('in')"]
Out=[!CommandMeasure SlideAnimation "tweenAnimation('out')"]


; ---------------------------------------------------------------------------- ;
;                                  MeterStyles                                 ;
; ---------------------------------------------------------------------------- ;

@includeCtxStyles=..\CtxStyles.inc

; ---------------------------------------------------------------------------- ;
;                          Context option meter styles                         ;
; ---------------------------------------------------------------------------- ;

[ZPOS1:Act]
LeftMouseUpAction=[!Zpos 2 #Sec.Skin#]
[ZPOS1:Text]
Text=Move to layer 2

[ZPOS2:Act]
LeftMouseUpAction=[!Zpos 1 #Sec.Skin#]
[ZPOS2:Text]
Text=Move to layer 1

[ZPOS3:Act]
LeftMouseUpAction=[!Zpos 0 #Sec.Skin#]
[ZPOS3:Text]
Text=Move to layer 0

[ZPOS4:Act]
LeftMouseUpAction=[!Zpos -1 #Sec.Skin#]
[ZPOS4:Text]
Text=Move to layer -1

[ZPOS5:Act]
LeftMouseUpAction=[!Zpos -2 #Sec.Skin#]
[ZPOS5:Text]
Text=Move to layer -2

;METERSTYLES===========================================================================================
;METERSTYLES===========================================================================================



[ZPOS1]
Meter=Shape
Y=(#Ctx.P#+1)
MeterStyle=CtxBox:S | ZPOS1:Act
[ZPOS1Text]
Meter=String
MeterStyle=Ctx.String:S | CtxTextNoIcon:S | ZPOS1:Text

[ZPOS2]
Meter=Shape
MeterStyle=CtxBox:S | ZPOS2:Act
[ZPOS2Text]
Meter=String
MeterStyle=Ctx.String:S | CtxTextNoIcon:S | ZPOS2:Text

[ZPOS3]
Meter=Shape
MeterStyle=CtxBox:S | ZPOS3:Act
[ZPOS3Text]
Meter=String
MeterStyle=Ctx.String:S | CtxTextNoIcon:S | ZPOS3:Text

[ZPOS4]
Meter=Shape
MeterStyle=CtxBox:S | ZPOS4:Act
[ZPOS4Text]
Meter=String
MeterStyle=Ctx.String:S | CtxTextNoIcon:S | ZPOS4:Text

[ZPOS5]
Meter=Shape
MeterStyle=CtxBox:S | ZPOS5:Act
[ZPOS5Text]
Meter=String
MeterStyle=Ctx.String:S | CtxTextNoIcon:S | ZPOS5:Text




[EndAnchor]
Meter=String
X=r
Y=(#Ctx.BoxH#/2*#Ctx.S#)r
