

[Title.2_2]
Meter=String
Text="Change log v2.2"
MeterStyle=Sec.String:S | Style.Title:S

[Description.2_2.0]
Meter=String
Text="• Fixed for lone installations."
MeterStyle=Sec.String:S | Style.Description:S

[Title.2_1]
Meter=String
Text="Change log v2.1"
Y=(#Sec.P#)R
MeterStyle=Sec.String:S | Style.Title:S

[Description.2_1.0]
Meter=String
Text="• Added more supported hotkeys!"
MeterStyle=Sec.String:S | Style.Description:S

[Title.2_0]
Meter=String
Text="Change log v2.0"
Y=(#Sec.P#)R
MeterStyle=Sec.String:S | Style.Title:S

[Description.2_0.0]
Meter=String
Text="• NEW VectorSlide animation style, try it out!#CRLF#• NEW Actions configurator!#CRLF#• You can now swap actions#CRLF#• More accurate positioning"
MeterStyle=Sec.String:S | Style.Description:S
