[Rainmeter]
Update=-1
DefaultWindowX=100
DefaultWindowY=100
DefaultUpdateDivider=-1
DynamicWindowSize=1
AccurateText=1
SkinWidth=(#Set.W#)
SkinHeight=(#Set.H#)
@includeCtx=#SKINSPATH##MosaicShell\CoreShell\}{CtxItms.inc

[Variables]
@includeCacheVarsHome=#@#CacheVars\Home.inc
Sec.Container=BC
Sec.Ctx.Pos=1
Sec.Page=1
Sec.AnchorName=Anchor
Sec.drag_bar_text=Home
Sec.selector_height=(75*[Set.S])
Process.tween_node_0=0
HomePage.P=(100*[Set.S])

; ---------------------------------------------------------------------------- ;
;                                   Functions                                  ;
; ---------------------------------------------------------------------------- ;

@includeCommonFunctions=#ROOTCONFIGPATH#CoreShell\Common\Functions.inc

[m.ShowInToolbar]
WindowTitle=MosaicShell

[DefaultStartActions]
Custom1=[!Draggable 1][!KeepOnScreen 0][!SetOption Selector.Item.Shape.#Sec.Page# MeterStyle "Selector.Item.Shape.n:S | Selector.Item.Shape.n:S_1"][!UpdateMeter Selector.Item.Shape.#Sec.Page#][!SetOption #Sec.AnchorName# Y [#Sec.AnchorName#:Y]][!EnableMeasure AnchorChecker][!UpdateMeasure AnchorChecker]
ActionList2=StartTween | Repeat In,2,40 | WriteTweenNode1
ActionList3=EndTween | Repeat Out,2,40 | WriteTweenNode0
ActionList4=StartTween | CompleteTween | WriteTweenNode1
ActionList5=EndTween | ResetTween | WriteTweenNode0
WriteTweenNode0=[!WriteKeyValue Variables Process.tween_node_0 0][!HideMeterGroup Selector.Group2][!Redraw]
WriteTweenNode1=[!WriteKeyValue Variables Process.tween_node_0 1][!HideMeterGroup Selector.Group1][!Redraw]
In=[!CommandMeasure s.SimpleAnimation "tweenAnimation('in')"]
Out=[!CommandMeasure s.SimpleAnimation "tweenAnimation('out')"]
StartTween=[!ShowMeterGroup Selector.Group2][!Redraw]
EndTween=[!ShowMeterGroup Selector.Group1][!Redraw][!CommandMeasure s.SimpleAnimation "endTween()"]
CompleteTween=[!SetVariable Process.tween_node_0 1][!UpdateMeterGroup Selector]
ResetTween=[!SetVariable Process.tween_node_0 0][!UpdateMeterGroup Selector]

[s.SimpleAnimation]
Measure=Script
ScriptFile=#@#Lua\SimpleAnimation.lua
Animation_Steps=40
Animation_Easing=InOutQuart
Animation_Node=Process.tween_node_0
Animation_Group=Selector
Animation_Handler=DefaultStartActions
Disabled=#Set.PerformanceMode#

[AnchorChecker]
Measure=Calc
Formula=(Clamp([BC:H]-[#Sec.AnchorName#:Y], -5000, 0))
IfCondition=AnchorChecker=0
IfTrueAction=[!DisableMouseAction BC "MouseScrollUpAction|MouseScrollDownAction"][!UpdateMeterGroup Background][!Redraw]
IfFalseAction=[!ShowMeter ScrollBar][!UpdateMeterGroup Background][!Redraw]
IfConditionMode=1
Group=AnchorChecker
DynamicVariables=1
Disabled=1

[MouseScrollBar]
Measure=Plugin
Plugin=Mouse
MouseMoveAction=[!SetVariable Scroll "(Clamp(($MouseY$-#ScrollClickedPos#-[BC:Y])/(#Set.H#/2-#Set.P#)*[AnchorChecker],[AnchorChecker],0))"][!UpdateMeter *][!Redraw]
LeftMouseUpAction=[!SetOption ScrollBar MeterStyle ScrollBar:Idle][!SetOption ScrollBar Fill "Stroke Color #Set.Ter_Color#"][!CommandMeasure MouseScrollBar "Stop"][!DisableMeasure MouseScrollBar][!UpdateMeter ScrollBar][!Redraw]
RequireDragging=1
RelativeToSkin=1
DynamicVariables=1
Disabled=1

; ---------------------------------------------------------------------------- ;
;                                  MeterStyles                                 ;
; ---------------------------------------------------------------------------- ;

@includeCommonStyles=#ROOTCONFIGPATH#CoreShell\Common\Styles.inc

[Selector.Item.Shape.n:S]
X=(135*[Set.S]-#Set.P#*0.2)r
Y=(-40*[Set.S]/2+1)r
Shape=Rectangle 0,0,(150*[Set.S]),(40*[Set.S]),(#Set.R#/2) | StrokeWidth 0 | Extend This
This=Fill Color #Set.Sec_Color#
DynamicVariables=1
MouseOverAction=[!SetOption #CURRENTSECTION# This "Fill Color #Set.Ter_color#"][!UpdateMeter #CURRENTSECTION#][!Redraw]
MouseLeaveAction=[!SetOption #CURRENTSECTION# This "Fill Color #Set.Sec_Color#"][!UpdateMeter #CURRENTSECTION#][!Redraw]
LeftMouseUpAction=[!WriteKeyValue Variables Sec.Page "[&Func:trim('#CURRENTSECTION#', 'Selector.Item.Shape.', '')]"][!Refresh]

[Selector.Item.Shape.n:S_1]
This=Fill LinearGradient CoreGrad
CoreGrad=45 | #Set.Accent_Color_2# ; 1 | #Set.Accent_Color# ;0
MouseOverAction=
MouseLeaveAction=

[Selector.Item.Icon.String.n:S]
X=(15*[Set.S])r
Y=(40*[Set.S]/2)r
FontSize=(20*[Set.S])
Fontface=Material Icons Round
FontColor=[&Func:returnBool('Sec.Page', '[&Func:trim('#CURRENTSECTION#', 'Selector.Item.Icon.String.', '')]', '#Set.Text_Color#', '#Set.SubText_Color#')]
Container=
StringAlign=LeftCenter
InlineSetting=Shadow | 2 | 2 | 5 | #Set.Pri_Color#,150

[Selector.Item.String.n:S]
FontSize=(12*[Set.S])
X=(#Set.P#*1.2)r
Y=(-1)r
W=((150-15)*[Set.S]-#Set.P#*1.2)
ClipString=2
Container=
FontColor=[&Func:returnBool('Sec.Page', '[&Func:trim('#CURRENTSECTION#', 'Selector.Item.String.', '')]', '#Set.Text_Color#', '#Set.SubText_Color#')]
StringAlign=LeftCenter
InlineSetting=Shadow | 2 | 2 | 5 | #Set.Pri_Color#,150

[Selector.Item.String.n:SmallText]
FontSize=(10*[Set.S])

; ---------------------------------------------------------------------------- ;
;                                    Content                                   ;
; ---------------------------------------------------------------------------- ;

; -------------------------------- Background -------------------------------- ;

[B]
Meter=Shape
X=(#Set.WinB#/2)
Y=(#Set.WinB#/2)
Shape=Rectangle 0,0, #Set.W#, #Set.H#, (#Set.WinR#*(1-#Set.Maximized#)) | StrokeWidth #Set.WinB# | Fill Color #Set.Pri_Color#,#Set.Alpha# | Stroke Color #Set.Ter_Color#
MouseActionCursor=0
DynamicVariables=1
[BC]
Meter=Shape
Y=#Set.TitleBarH#
Shape=Rectangle 0,0, #Set.W#, (#Set.H#-#Sec.selector_height#-#Set.TitleBarH#), #Set.WinR# | StrokeWidth 0 | Fill Color #Set.Pri_Color#
MouseActionCursor=0
DynamicVariables=1
MouseScrollDownAction=[!SetVariable Scroll "(Clamp(#Scroll#-50,[AnchorChecker],0))"][!UpdateMeter *][!Redraw]
MouseScrollUpAction=[!SetVariable Scroll "(Clamp(#Scroll#+50,[AnchorChecker],0))"][!UpdateMeter *][!Redraw]

; ------------------------------- Page selector ------------------------------ ;

[Selector.Shape]
Meter=Shape
X=0
Y=(#Set.H#-#Sec.selector_height#)
Shape=Rectangle 0,0,(#Set.W#),(#Sec.selector_height#) | StrokeWidth 0 | Fill Color #Set.Sec_Color#
Shape2=Rectangle 0,0,(#Set.W#),(2*[Set.S]) | StrokeWidth 0 | Fill Color #Set.Ter_Color#
DynamicVariables=1

; ---------------------------------- Group 1 --------------------------------- ;

[Selector.Group1.Container]
Meter=String
X=((#Set.W#/2-((150*3)*[Set.S]+#Set.P#*2)/2)*(1-#process.tween_node_0#))
Y=(#Set.H#-#Sec.selector_height#/2-20*[Set.S])
W=((150*3)*[Set.S]+#Set.P#*2)
H=(40*[Set.S])
DynamicVariables=1
Group=Selector
SolidColor=255,255,255,(255*(1-#process.tween_node_0#))
Group=Selector.Group1
Hidden=(#process.tween_node_0#)

[Selector.Item.Shape.1]
Meter=Shape
X=0
Y=0
MeterStyle=Selector.Item.Shape.n:S
Container=Selector.Group1.Container
Group=Selector.Group1
Hidden=(#process.tween_node_0#)
[Selector.Item.Icon.String.1]
Meter=String
Text=[\xe88a]
MeterStyle=Set.String:S | Selector.Item.Icon.String.n:S
Container=Selector.Group1.Container
Group=Selector.Group1
Hidden=(#process.tween_node_0#)
[Selector.Item.String.1]
Meter=String
Text=Discover
MeterStyle=Set.String:S | Selector.Item.String.n:S
Container=Selector.Group1.Container
Group=Selector.Group1
Hidden=(#process.tween_node_0#)

[Selector.Item.Shape.3]
Meter=Shape
MeterStyle=Selector.Item.Shape.n:S
Container=Selector.Group1.Container
Group=Selector.Group1
Hidden=(#process.tween_node_0#)
[Selector.Item.Icon.String.3]
Meter=String
Text=[\xe02f]
MeterStyle=Set.String:S | Selector.Item.Icon.String.n:S
Container=Selector.Group1.Container
Group=Selector.Group1
Hidden=(#process.tween_node_0#)
[Selector.Item.String.3]
Meter=String
Text=Library
MeterStyle=Set.String:S | Selector.Item.String.n:S
Container=Selector.Group1.Container
Group=Selector.Group1
Hidden=(#process.tween_node_0#)

[Selector.Item.Shape.4]
Meter=Shape
MeterStyle=Selector.Item.Shape.n:S
LeftMouseUpAction=[!WriteKeyValue Variables Skin.Name "#MosaicShell" "#@#CacheVars\Configurator.inc"][!WriteKeyValue Variables Skin.Set_Page General "#@#CacheVars\Configurator.inc"][!ActivateConfig "#CURRENTCONFIG#" "Settings.ini"]
Container=Selector.Group1.Container
Group=Selector.Group1
Hidden=(#process.tween_node_0#)
[Selector.Item.Icon.String.4]
Meter=String
Text=[\xe8b8]
MeterStyle=Set.String:S | Selector.Item.Icon.String.n:S
Container=Selector.Group1.Container
Group=Selector.Group1
Hidden=(#process.tween_node_0#)
[Selector.Item.String.4]
Meter=String
Text=Settings
MeterStyle=Set.String:S | Selector.Item.String.n:S
Container=Selector.Group1.Container
Group=Selector.Group1
Hidden=(#process.tween_node_0#)

; ------------------------------- Page switcher ------------------------------ ;

[Selector.PageSwitcher.Shape]
Meter=Shape
X=((#Set.W#-90*[Set.S])*(1-#process.tween_node_0#)+20*[Set.S]*#process.tween_node_0#)
Y=(#Set.H#-#Sec.selector_height#/2-20*[Set.S])
Shape=Rectangle 0,0,(70*[Set.S]),(40*[Set.S]),(#Set.R#/2) | StrokeWidth 0 | Extend This
This=Fill Color #Set.Ter_color#
DynamicVariables=1
MouseOverAction=[!SetOption #CURRENTSECTION# This "Fill Color #Set.Subtext_color#"][!UpdateMeter #CURRENTSECTION#][!Redraw]
MouseLeaveAction=[!SetOption #CURRENTSECTION# This "Fill Color #Set.Ter_color#"][!UpdateMeter #CURRENTSECTION#][!Redraw]
MeterStyle=Selector.PageSwitcher.Shape:#process.tween_node_0#_#Set.PerformanceMode#
Group=Selector
[Selector.PageSwitcher.Shape:0_0]
LeftMouseUpAction=[!CommandMeasure DefaultStartActions "Execute 2"]
[Selector.PageSwitcher.Shape:1_0]
LeftMouseUpAction=[!CommandMeasure DefaultStartActions "Execute 3"]
[Selector.PageSwitcher.Shape:0_1]
LeftMouseUpAction=[!CommandMeasure DefaultStartActions "Execute 4"]
[Selector.PageSwitcher.Shape:1_1]
LeftMouseUpAction=[!CommandMeasure DefaultStartActions "Execute 5"]
[Selector.PageSwitcher.Icon.String]
Meter=String
X=(70*[Set.S]/2)r
Y=(22*[Set.S])r
FontSize=(30*[Set.S])
Fontface=Material Icons Round
FontColor=#Set.Text_Color#
Container=
StringAlign=CenterCenter
InlineSetting=Shadow | 0 | 0 | 5 | #Set.Pri_Color#,150
MeterStyle=Set.String:S | Selector.PageSwitcher.Icon.String:#process.tween_node_0#
Group=Selector
[Selector.PageSwitcher.Icon.String:0]
Text=[\xe315]
[Selector.PageSwitcher.Icon.String:1]
Text=[\xe314]

; ---------------------------------- Group 2 --------------------------------- ;

[Selector.Group2.Container]
Meter=String
X=((#Set.W#/2-((150*4)*[Set.S]+#Set.P#*3)/2)+100*[Set.S]*(1-#process.tween_node_0#))
Y=(#Set.H#-#Sec.selector_height#/2-20*[Set.S])
W=((150*4)*[Set.S]+#Set.P#*3)
H=(40*[Set.S])
DynamicVariables=1
Group=Selector
SolidColor=255,255,255,(255*(#process.tween_node_0#))
Group=Selector.Group2
Hidden=(1-#process.tween_node_0#)

[Selector.Item.Shape.5]
Meter=Shape
X=0
Y=0
MeterStyle=Selector.Item.Shape.n:S
Container=Selector.Group2.Container
Group=Selector.Group2
Hidden=(1-#process.tween_node_0#)
[Selector.Item.Icon.String.5]
Meter=String
Text=[\xe575]
MeterStyle=Set.String:S | Selector.Item.Icon.String.n:S
Container=Selector.Group2.Container
Group=Selector.Group2
Hidden=(1-#process.tween_node_0#)
[Selector.Item.String.5]
Meter=String
Text=About MosaicShell
MeterStyle=Set.String:S | Selector.Item.String.n:S | Selector.Item.String.n:SmallText
Container=Selector.Group2.Container
Group=Selector.Group2
Hidden=(1-#process.tween_node_0#)

[Selector.Item.Shape.6]
Meter=Shape
MeterStyle=Selector.Item.Shape.n:S
Container=Selector.Group2.Container
Group=Selector.Group2
Hidden=(1-#process.tween_node_0#)
[Selector.Item.Icon.String.6]
Meter=String
Text=[\xe88e]
MeterStyle=Set.String:S | Selector.Item.Icon.String.n:S
Container=Selector.Group2.Container
Group=Selector.Group2
Hidden=(1-#process.tween_node_0#)
[Selector.Item.String.6]
Meter=String
Text=About
MeterStyle=Set.String:S | Selector.Item.String.n:S | Selector.Item.String.n:SmallText
Container=Selector.Group2.Container
Group=Selector.Group2
Hidden=(1-#process.tween_node_0#)

[Selector.Item.Shape.7]
Meter=Shape
MeterStyle=Selector.Item.Shape.n:S
Container=Selector.Group2.Container
Group=Selector.Group2
Hidden=(1-#process.tween_node_0#)
LeftMouseUpAction=["https://github.com/uairhahs/MosaicShell"]
[Selector.Item.Icon.String.7]
Meter=String
Text=[\xe87d]
MeterStyle=Set.String:S | Selector.Item.Icon.String.n:S
Container=Selector.Group2.Container
Group=Selector.Group2
Hidden=(1-#process.tween_node_0#)
[Selector.Item.String.7]
Meter=String
Text=GitHub
MeterStyle=Set.String:S | Selector.Item.String.n:S | Selector.Item.String.n:SmallText
Container=Selector.Group2.Container
Group=Selector.Group2
Hidden=(1-#process.tween_node_0#)

[Selector.Item.Shape.8]
Meter=Shape
MeterStyle=Selector.Item.Shape.n:S
Container=Selector.Group2.Container
Group=Selector.Group2
Hidden=(1-#process.tween_node_0#)
[Selector.Item.Icon.String.8]
Meter=String
Text=[\xeb9b]
MeterStyle=Set.String:S | Selector.Item.Icon.String.n:S
Container=Selector.Group2.Container
Group=Selector.Group2
Hidden=(1-#process.tween_node_0#)
[Selector.Item.String.8]
Meter=String
Text=S-Hub
MeterStyle=Set.String:S | Selector.Item.String.n:S | Selector.Item.String.n:SmallText
Container=Selector.Group2.Container
Group=Selector.Group2
Hidden=(1-#process.tween_node_0#)

; -------------------------------- Header bar -------------------------------- ;

[Header.Shape]
Meter=Shape
X=0
Y=(#Scroll#)
Shape=Rectangle 0,0,(#Set.W#),(90*[Set.S]) | StrokeWidth 0 | Fill Color #Set.Sec_Color#
Shape2=Rectangle 0,(90*[Set.S]),(#Set.W#),(2*[Set.S]) | StrokeWidth 0 | Fill Color #Set.Sec_Color#
DynamicVariables=1
Container=#Sec.Container#

[Header.String]
Meter=String
X=(#HomePage.P#)
Y=(90*[Set.S]/2+2*[Set.S]+#Scroll#)
Stringalign=LeftCenter
FontSize=(24*[Set.S])
FontWeight=600
MeterStyle=Set.String:S

; ------------------------------- Page content ------------------------------- ;

@includePage=#ROOTCONFIGPATH#CoreShell\Home\Pages\Page#Sec.Page#.inc

; ---------------------------- Page scroll anchor ---------------------------- ;

[Anchor]
Meter=String
Container=BC
x=r
Y=R

; -------------------------------- Scroll bar -------------------------------- ;

[ScrollBar:Scrolling]
Fill=Stroke Color #Set.Subtext_Color#
[ScrollBar:Idle]
LeftMouseDownAction=[!SetVariable ScrollClickedPos "$MouseY$"][!SetOption ScrollBar MeterStyle ScrollBar:Scrolling][!EnableMeasure MouseScrollBar][!UpdateMeasure MouseScrollBar][!CommandMeasure MouseScrollBar "Start"]
MouseOverAction=[!SetOption #CURRENTSECTION# Fill "Stroke Color #Set.Subtext_Color#"][!UpdateMeter #CURRENTSECTION#][!Redraw]
MouseLeaveAction=[!SetOption #CURRENTSECTION# Fill "Stroke Color #Set.Ter_Color#"][!UpdateMeter #CURRENTSECTION#][!Redraw]
[ScrollBar]
Meter=Shape
X=([BC:XW]-10*[Set.S])
Y=(#Set.P#+#Set.TitleBarH#+(#Scroll#/([AnchorChecker]+1)*(([BC:H]-#Set.P#*2)-([BC:H]/([BC:H]-[AnchorChecker])*([BC:H]-#Set.P#*2)))))
Shape=Line 0,0,0,([BC:H]/([BC:H]-[AnchorChecker])*([BC:H]-#Set.P#*2)) | StrokeWidth (4*[Set.S]) | StrokeStartCap Round | StrokeEndCap Round | Extend Fill
Fill=Stroke Color #Set.Ter_Color#
DynamicVariables=1
Group=Background | Scrollbar
Hidden=1
MeterStyle=ScrollBar:Idle

@includeWindowControls=#ROOTCONFIGPATH#CoreShell\Common\WindowControls.inc

[CommandBar.Shape]
Hidden=1
[CommandBar.String]