[Rainmeter]
Update=-1
DefaultWindowX=100
DefaultWindowY=100
DefaultUpdateDivider=-1
DynamicWindowSize=1
AccurateText=1
SkinWidth=(#Set.W#)
SkinHeight=(#Set.H#)
@includeCtx=#SKINSPATH##MosaicShell\CoreShell\}{CtxItms.inc

[Variables]
Sec.Container=BC
Sec.Ctx.Pos=1
Sec.drag_bar_text=S-Hub packager tool
BoxH=70

; ---------------------------------------------------------------------------- ;
;                                   Functions                                  ;
; ---------------------------------------------------------------------------- ;

@includeCommonFunctions=#ROOTCONFIGPATH#CoreShell\Common\Functions.inc

[m.ShowInToolbar]
WindowTitle=MosaicShell

[S-HubScript]
Measure=Plugin
Plugin=PowershellRM
DynamicVariables=1
ScriptFile=#@#Powershell\S-Hub.ps1
ExecutionPolicy=Unrestricted

; ---------------------------------------------------------------------------- ;
;                                  MeterStyles                                 ;
; ---------------------------------------------------------------------------- ;

@includeCommonStyles=#ROOTCONFIGPATH#CoreShell\Common\Styles.inc

[Sec.Section.Text:S]
X=(5*[Set.S])R
Y=r
W=(#Set.W#-#Set.P#*2-80*[Set.S])
ClipString=2
FontSize=(14*[Set.S])
StringAlign=LeftCenter
InlineSetting=Weight | 650
[Sec.Section.Icon:S]
X=(#Set.P#)r
Y=(#BoxH#/2*[Set.S])r
FontSize=(22*[set.s])
StringAlign=LeftCenter
FontFace=Material Icons Round
Container=#Sec.Container#
[Sec.Section.Shape:S]
X=#Set.P#
Y=(#BoxH#/2*[Set.S]+#Set.P#/2)r
Shape=Rectangle 0,0,(#Set.W#-#Set.P#*2),(#BoxH#*[Set.S]),(#Set.R#/4) | Extend Fill | Stroke Color #Set.Accent_Color#
Fill=Fill Color #Set.Sec_Color#,100 | StrokeWidth 0
MouseOverAction=[!SetOption #CURRENTSECTION# Fill "Fill Color #Set.Sec_Color#,200 | StrokeWidth 2"][!UpdateMeter #CURRENTSECTION#][!Redraw]
MouseLeaveAction=[!SetOption #CURRENTSECTION# Fill "Fill Color #Set.Sec_Color#,100 | StrokeWidth 0"][!UpdateMeter #CURRENTSECTION#][!Redraw]
DynamicVariables=1
Container=#Sec.Container#

; ---------------------------------------------------------------------------- ;
;                                    Content                                   ;
; ---------------------------------------------------------------------------- ;

[B]
Meter=Shape
X=(#Set.WinB#/2)
Y=(#Set.WinB#/2)
Shape=Rectangle 0,0, #Set.W#, #Set.H#, (#Set.WinR#*(1-#Set.Maximized#)) | StrokeWidth #Set.WinB# | Fill Color #Set.Pri_Color#,#Set.Alpha# | Stroke Color #Set.Ter_Color#
MouseActionCursor=0
DynamicVariables=1
[BC]
Meter=Shape
Y=#Set.TitleBarH#
Shape=Rectangle 0,0, #Set.W#, (#Set.H#-#Set.TitleBarH#), #Set.WinR# | StrokeWidth 0 | Fill Color #Set.Pri_Color#
MouseActionCursor=0
DynamicVariables=1

[title.Text1]
Meter=String
MeterStyle=Set.String:S
Text=S-Hub packager
X=(#Set.W#/2)
Y=(40*[Set.S])
FontSize=(28*[Set.S])
FontWeight=650
StringAlign=Center
InlineSetting=GradientColor | 180 | #Set.Accent_Color# ; 0.0 | #Set.Accent_Color_2# ; 1.0

[SpotDes]
Meter=String
X=r
Y=R
W=(#Set.W#-#Set.P#*4)
ClipString=2
FontSize=(11*[Set.S])
Fontcolor=#Set.SubText_Color#
StringAlign=Center
MeterStyle=Set.String:S
Text=Register file associations, build an .SHP package, or open the export folder. Register once before creating packages.

[Register]
Meter=Shape
X=#Set.P#
Y=(160*[Set.S])
MeterStyle=Sec.Section.Shape:S
LeftMouseUpAction=[!CommandMeasure S-HubScript Initiate]
[Register.Icon]
Meter=String
Text=[\xe161]
MeterStyle=Set.String:S | Set.Icon:S | Sec.Section.Icon:S
[Register.Text]
Meter=String
Text=Register .SHP paths and file type
MeterStyle=Set.String:S | Sec.Section.Text:S

[Create]
Meter=Shape
MeterStyle=Sec.Section.Shape:S
LeftMouseUpAction=[!CommandMeasure S-HubScript Pack]
[Create.Icon]
Meter=String
Text=[\xe2c8]
MeterStyle=Set.String:S | Set.Icon:S | Sec.Section.Icon:S
[Create.Text]
Meter=String
Text=Create package
MeterStyle=Set.String:S | Sec.Section.Text:S

[Directory]
Meter=Shape
MeterStyle=Sec.Section.Shape:S
LeftMouseUpAction=[!CommandMeasure S-HubScript OpenExports]
[Directory.Icon]
Meter=String
Text=[\xe2c7]
MeterStyle=Set.String:S | Set.Icon:S | Sec.Section.Icon:S
[Directory.Text]
Meter=String
Text=Go to generated packages directory
MeterStyle=Set.String:S | Sec.Section.Text:S

@includeWindowControls=#ROOTCONFIGPATH#CoreShell\Common\WindowControls.inc

[CommandBar.Shape]
Hidden=1
[CommandBar.String]