[Rainmeter]
Update=-1
DefaultWindowX=100
DefaultWindowY=100
DefaultUpdateDivider=-1
DynamicWindowSize=1
AccurateText=1
SkinWidth=(#Set.W#)
SkinHeight=(#Set.H#)
@includeCtx=#SKINSPATH##MosaicShell\CoreShell\}{CtxItms.inc

[Variables]
Sec.Container=BC
Sec.Ctx.Pos=1
Sec.drag_bar_text=S-Hub packager tool

; ---------------------------------------------------------------------------- ;
;                                   Functions                                  ;
; ---------------------------------------------------------------------------- ;

@includeCommonFunctions=#ROOTCONFIGPATH#CoreShell\Common\Functions.inc

[m.ShowInToolbar]
WindowTitle=MosaicShell


[S-HubScript]
Measure=Plugin
Plugin=PowershellRM
DynamicVariables=1
ScriptFile=#@#Powershell\S-Hub.ps1
ExecutionPolicy=Unrestricted

; ---------------------------------------------------------------------------- ;
;                                  MeterStyles                                 ;
; ---------------------------------------------------------------------------- ;

@includeCommonStyles=#ROOTCONFIGPATH#CoreShell\Common\Styles.inc

; ---------------------------------------------------------------------------- ;
;                                    Content                                   ;
; ---------------------------------------------------------------------------- ;

[B]
Meter=Shape
X=(#Set.WinB#/2)
Y=(#Set.WinB#/2)
Shape=Rectangle 0,0, #Set.W#, #Set.H#, (#Set.WinR#*(1-#Set.Maximized#)) | StrokeWidth #Set.WinB# | Fill Color #Set.Pri_Color#,#Set.Alpha# | Stroke Color #Set.Ter_Color#
MouseActionCursor=0
DynamicVariables=1
[BC]
Meter=Shape
Y=#Set.TitleBarH#
Shape=Rectangle 0,0, #Set.W#, (#Set.H#-#Set.TitleBarH#), #Set.WinR# | StrokeWidth 0 | Fill Color #Set.Pri_Color#
MouseActionCursor=0
DynamicVariables=1

[Register]
Meter=String
X=#Set.P#
Y=#Set.P#
Text=Register .SHP paths and file type
MeterStyle=Set.String:S
LeftMouseUpAction=[!CommandMeasure S-HubScript Initiate]

[Create]
Meter=String
X=r
Y=R
Text=Create package
MeterStyle=Set.String:S
LeftMouseUpAction=[!CommandMeasure S-HubScript Pack]

[Directory]
Meter=String
X=r
Y=R
Text=Go to generated packages directory
MeterStyle=Set.String:S
LeftMouseUpAction=["#SKINSPATH#..\CoreData\S-hub\Exports"]

; -------------------------------- Scroll bar -------------------------------- ;

@includeWindowControls=#ROOTCONFIGPATH#CoreShell\Common\WindowControls.inc

[CommandBar.Shape]
Hidden=1
[CommandBar.String]
