[Rainmeter]
Update=-1
DefaultWindowX=100
DefaultWindowY=100
DefaultUpdateDivider=-1
DynamicWindowSize=1
AccurateText=1
SkinWidth=(#Set.W#)
SkinHeight=(#Set.H#)
@includeCtx=#SKINSPATH##MosaicShell\CoreShell\}{CtxItms.inc
[Variables]
@includeSkin=#@#CacheVars\Configurator.inc
@includeSkinVars=#SKINSPATH##Skin.Name#\@Resources\Vars.inc
@includeSkinVer=#SKINSPATH##Skin.Name#\@Resources\Version.inc
Sec.Ctx.Settings=0
Sec.Ctx.Pos=1
Sec.Container=ContentContainer
Sec.AnchorName=Anchor
Sec.drag_bar_text=#Skin.Name# settings
process.tween_node_pagelist=0
ScrollClickedPos=0

; ---------------------------------------------------------------------------- ;
;                                   Functions                                  ;
; ---------------------------------------------------------------------------- ;

@includeCommonFunctions=#ROOTCONFIGPATH#CoreShell\Common\Functions.inc

[DefaultStartActions]
Custom2=[!Draggable 0][!SetOption #Sec.AnchorName# Y [#Sec.AnchorName#:Y]][!EnableMeasure AnchorChecker][!UpdateMeasure AnchorChecker]

[AnchorChecker]
Measure=Calc
Formula=(Clamp(#Set.H#-#Set.P#*2-[#Sec.AnchorName#:Y], -5000, 0))
IfCondition=AnchorChecker=0
IfTrueAction=[!DisableMouseAction ContentContainer "MouseScrollUpAction|MouseScrollDownAction"][!UpdateMeterGroup Background][!Redraw]
IfFalseAction=[!ShowMeter ScrollBar][!UpdateMeterGroup Background][!Redraw]
IfConditionMode=1
Group=AnchorChecker
DynamicVariables=1
Disabled=1

[MouseScrollBar]
Measure=Plugin
Plugin=Mouse
MouseMoveAction=[!SetVariable Scroll "(Clamp(($MouseY$-#ScrollClickedPos#-#SEt.P#)/(#Set.H#/2-#Set.P#)*[AnchorChecker],[AnchorChecker],0))"][!UpdateMeter *][!Redraw]
LeftMouseUpAction=[!SetOption ScrollBar MeterStyle ScrollBar:Idle][!SetOption ScrollBar Fill "Stroke Color #Set.Ter_Color#"][!CommandMeasure MouseScrollBar "Stop"][!DisableMeasure MouseScrollBar][!UpdateMeter ScrollBar][!Redraw]
RequireDragging=1
RelativeToSkin=1
DynamicVariables=1
Disabled=1

[m.ConfigActive]
Measure=Plugin
Plugin=ConfigActive
ConfigName=#Skin.Name#\Main
IfCondition=m.ConfigActive=1
IfTrueAction=[!SetOption PageList.Toggler.Shape MeterStyle PageList.Toggler.Shape:1][!SetOption PageList.Toggler.String MeterStyle "Set.String:S | PageList.Toggler.String:1"]
IfFalseAction=[!SetOption PageList.Toggler.Shape MeterStyle PageList.Toggler.Shape:0][!SetOption PageList.Toggler.String MeterStyle "Set.String:S | PageList.Toggler.String:0"]

[p.ActionTimer.PageList]
Measure=Plugin
Plugin=ActionTimer
DynamicVariables=1
ActionList1=Repeat SlideIn,0,5
ActionList2=Repeat SlideOut,0,5
SlideIn=[!SetVariable process.tween_node_pagelist "(Clamp((#process.tween_node_pagelist#+0.2),0,1))"][!UpdateMeterGroup PageList][!UpdateMeasure p.ActionTimer.PageList][!Redraw]
SlideOut=[!SetVariable process.tween_node_pagelist "(Clamp((#process.tween_node_pagelist#-0.2),0,1))"][!UpdateMeterGroup PageList][!UpdateMeasure p.ActionTimer.PageList][!Redraw]

; ---------------------------------------------------------------------------- ;
;                                  MeterStyles                                 ;
; ---------------------------------------------------------------------------- ;

@includeMeterStyles=#ROOTCONFIGPATH#\CoreShell\Setting\Styles.inc
@includeCommonStyles=#ROOTCONFIGPATH#CoreShell\Common\Styles.inc

; ---------------------------------------------------------------------------- ;
;                                    Content                                   ;
; ---------------------------------------------------------------------------- ;

; ---------------------------------- Window ---------------------------------- ;

[Background.Shape]
Meter=Shape
X=(#Set.WinB#/2)
Y=(#Set.WinB#/2)
Shape=Rectangle 0,0, #Set.W#, #Set.H#, (#Set.WinR#*(1-#Set.Maximized#)) | StrokeWidth #Set.WinB# | Fill Color #Set.Pri_Color#,#Set.Alpha# | Stroke Color #Set.Ter_Color#
; Shape2=Line #Set.L#, (#Set.P#+#Set.TitleBarH#), #Set.L#, (#Set.H#-#Set.P#) | StrokeWidth 2 | Stroke LinearGradient This
; Shape3=Rectangle (#Set.L#-5*[SEt.S]),(#Set.P#+#Set.TitleBarH#),(10*[SEt.S]),(10*[SEt.S]) | Rotate 45 | StrokeWidth 0 | Fill Color #Set.Accent_Color#
This=270 | #Set.Accent_Color# ; 0 | #Set.Ter_Color#,100 ; 0.1 | #Set.Pri_Color#,0 ; 1.0
MouseActionCursor=0
DynamicVariables=1

[ContentContainer]
Meter=Shape
X=(#set.P#*2+30*[SEt.S])
Y=(#Set.TitleBarH#+#Set.P#/2)
Shape=Rectangle (0),(0),(#Set.W#-30*[Set.S]-#Set.P#*3),(#Set.H#-#Set.TitleBarH#-#Set.P#*1.5),(#Set.R#/2),(#Set.R#/2) | StrokeWidth 0 | Fill Color 255,255,255
DynamicVariables=1
MouseScrollDownAction=[!SetVariable Scroll "(Clamp(#Scroll#-50,[AnchorChecker],0))"][!UpdateMeter *][!Redraw]
MouseScrollUpAction=[!SetVariable Scroll "(Clamp(#Scroll#+50,[AnchorChecker],0))"][!UpdateMeter *][!Redraw]
MouseActionCursor=0
Group=Background | PageList

[ScrollBar:Scrolling]
Fill=Stroke Color #Set.Subtext_Color#
[ScrollBar:Idle]
LeftMouseDownAction=[!SetVariable ScrollClickedPos "$MouseY$"][!SetOption ScrollBar MeterStyle ScrollBar:Scrolling][!EnableMeasure MouseScrollBar][!UpdateMeasure MouseScrollBar][!CommandMeasure MouseScrollBar "Start"]
MouseOverAction=[!SetOption #CURRENTSECTION# Fill "Stroke Color #Set.Subtext_Color#"][!UpdateMeter #CURRENTSECTION#][!Redraw]
MouseLeaveAction=[!SetOption #CURRENTSECTION# Fill "Stroke Color #Set.Ter_Color#"][!UpdateMeter #CURRENTSECTION#][!Redraw]
[ScrollBar]
Meter=Shape
X=([ContentContainer:XW]+25*[Set.S])
Y=(#Set.P#+(#Scroll#/([AnchorChecker]+1)*([ContentContainer:H]-([ContentContainer:H]/([ContentContainer:H]-[AnchorChecker])*[ContentContainer:H]))))
Shape=Line 0,0,0,([ContentContainer:H]/([ContentContainer:H]-[AnchorChecker])*[ContentContainer:H]) | StrokeWidth (4*[Set.S]) | StrokeStartCap Round | StrokeEndCap Round | Extend Fill
Fill=Stroke Color #Set.Ter_Color#
DynamicVariables=1
Group=Background | Scrollbar
Hidden=1
MeterStyle=ScrolLBar:Idle

@includeWindowControls=#ROOTCONFIGPATH#CoreShell\Common\WindowControls.inc

; --------------------------------- Page list -------------------------------- ;

[PageList.Shape]
Meter=Shape
X=(#Set.P#/2)
Y=(#Set.P#/2+#Set.TitleBarH#)
Shape=Rectangle 0,0,((#Set.L#-#Set.P#)*#process.tween_node_pagelist#+(#Set.P#+30*[Set.S])*(1-#process.tween_node_pagelist#)),(#Set.H#-#set.P#-#Set.TitleBarH#),(#Set.R#) | StrokeWidth (#Set.P#/2) | Stroke Color #Set.Pri_Color# | FIll Color #Set.Sec_Color#
Shape2=Rectangle 0,0,((#Set.L#-#Set.P#)*#process.tween_node_pagelist#+(#Set.P#+30*[Set.S])*(1-#process.tween_node_pagelist#)),(#Set.H#-#set.P#-#Set.TitleBarH#),(#Set.R#) | StrokeWidth 0 | FIll Color #Set.Sec_Color#
DynamicVariables=1
Group=PageList
MeterStyle=PageList.Shape:#Set.PerformanceMode#
[PageList.Shape:0]
MouseOverAction=[!CommandMeasure p.ActionTimer.PageList "Execute 1"]
MouseLeaveAction=[!CommandMeasure p.ActionTimer.PageList "Execute 2"]
[PageList.Shape:1]
MouseOverAction=[!SetVariable process.tween_node_pagelist "1"][!UpdateMeterGroup PageList][!Redraw]
MouseLeaveAction=[!SetVariable process.tween_node_pagelist "0"][!UpdateMeterGroup PageList][!Redraw]

[PageList.Container]
Meter=Shape
X=r
Y=r
Shape=Rectangle 0,0,((#Set.L#-#Set.P#)*#process.tween_node_pagelist#+(#Set.P#+30*[Set.S])*(1-#process.tween_node_pagelist#)),(#Set.H#-#set.P#-#Set.TitleBarH#),(#Set.R#) | StrokeWidth 0 | FIll Color #Set.Sec_Color#
DynamicVariables=1
Group=PageList

[PageList.Header.Image]
Meter=Image
X=(#Set.P#/2)
Y=(#Set.P#/2)
W=(30*[Set.S])
H=(30*[Set.S])
ImageAlpha=(255*(1-#process.tween_node_pagelist#))
ImageName="#@#Icons\LibraryIcons\#Skin.Name#.png"
DynamicVariables=1
ImageTint=#Set.Text_Color#
Container=PageList.Container
Group=PageList

[PageList.Header.String]
Meter=String
X=r
Y=r
MeterStyle=Set.String:S
Text=#Skin.Name#
W=(#Set.L#-#Set.P#*1.5)
ClipString=1
FontWeight=(650)
FontColor=#Set.Text_Color#,(255*#process.tween_node_pagelist#)
FontSize=(14*[Set.S])
DynamicVariables=1
Container=PageList.Container
Group=PageList

; ---------------------------------- Toggler --------------------------------- ;

[PageList.Toggler.Shape]
Meter=Shape
X=(#Set.P#/2)
Y=(#Set.P#/2)R
Shape=Rectangle 0,0,((#Set.L#-#Set.P#*2)*#process.tween_node_pagelist#+(30*[Set.S])*(1-#process.tween_node_pagelist#)),(25*[Set.S]),(12.5*[Set.S]) | StrokeWidth (14*[Set.S]) | Extend Fill
DynamicVariables=1
RightMouseUpAction=[!Refresh "#Skin.Name#\Main"]
MeterStyle=PageList.Toggler.Shape:0
Group=PageList.Toggler | PageList
Container=PageList.Container
[PageList.Toggler.Shape:0]
Fill=Fill Color #Set.Sec_Color# | Stroke Color #set.Sec_Color#
Shape2=Rectangle 0,0,((30+20*#process.tween_node_pagelist#)*[Set.S]),(25*[Set.S]),(12.5*[Set.S]) | StrokeWidth 0 | Fill Color #Set.SubText_Color#
Shape3=Ellipse ((15-1*#process.tween_node_pagelist#)*[Set.S]),(12.5*[Set.S]),(6*[Set.S]) | StrokeWidth (2*[Set.S]) | Stroke Color #Set.Text_Color# | Fill Color 0,0,0,0
Leftmouseupaction=[!ActivateConfig "#Skin.Name#\Main"][!UpdateMeasure m.ConfigActive][!UpdatemeterGroup PageList.Toggler][!Redraw]
[PageList.Toggler.Shape:1]
Fill=Fill Color #Set.Ter_Color# | Stroke Color #set.Ter_Color#
Shape2=Rectangle 0,0,((30+20*#process.tween_node_pagelist#)*[Set.S]),(25*[Set.S]),(12.5*[Set.S]) | StrokeWidth 0 | Fill LinearGradient CoreGrad
Shape3=Ellipse ((15+21*#process.tween_node_pagelist#)*[Set.S]),(12.5*[Set.S]),(8*[Set.S]) | StrokeWidth 0 | Fill Color #Set.Text_Color#
CoreGrad=45 | #Set.Accent_Color_2# ; 1 | #Set.Accent_Color# ;0
Leftmouseupaction=[!DeactivateConfig "#Skin.Name#\Main"][!UpdateMeasure m.ConfigActive][!UpdatemeterGroup PageList.Toggler][!Redraw]
[PageList.Toggler.String]
Meter=String
X=(60*[Set.S])r
Y=(12.5*[Set.S])r
DynamicVariables=1
FontSize=(10*[Set.S])
MeterStyle=Set.String:S | PageList.Toggler.String:0
StringAlign=LeftCenter
Group=PageList.Toggler | PageList
Container=PageList.Container
[PageList.Toggler.String:0]
Text=Not Active
FontColor=#Set.SubText_Color#
[PageList.Toggler.String:1]
Text=Activated
FontColor=#Set.Positive_Color#

@includePagesList=#SKINSPATH##Skin.Name#\Core\#page.inc

; Legacy style category disabler
[General:Category]
Meter=

[PageList.Bottom.Divider]
Meter=Shape
Y=((#Set.H#-#set.P#-#Set.TitleBarH#)-50*[Set.S]-#Set.P#)
MeterStyle=PageDiv:S

[Help.Shape]
Meter=Shape
MeterStyle=PageList.Item.Shape:S
[Help.Icon.String]
Meter=String
Text="[\xe887]"
MeterStyle=Set.String:S | PageList.Item.Icon.String:S
[Help.String]
Meter=String
Text=Help
MeterStyle=Set.String:S | PageList.Item.String:S

; ---------------------------------------------------------------------------- ;
;                             Include page content                             ;
; ---------------------------------------------------------------------------- ;

@includePages=#ROOTCONFIGPATH#\CoreShell\#Skin.Set_Page#.inc
@includeActualOverride=#SKINSPATH##Skin.Name#\Core\#Skin.Set_Page#.inc

; ---------------------------- Page scroll anchor ---------------------------- ;

[Anchor]
Meter=String
Container=ContentContainer
x=r
Y=R
