[ImageContainer]
Hidden=1
[Image]
Hidden=1

[Title.2_1]
Meter=String
Text="Change log v2.1"
MeterStyle=Sec.String:S | Style.Title:S

[Description.2_1]
Meter=String
Text="• Fixed issue where mixer doesn't appear when animations are turned off#CRLF#• Fixed module mode mis-behaving#CRLF#• Added static mixer icons for Windows 11 users"
MeterStyle=Sec.String:S | Style.Description:S

[Title.2_0]
Meter=String
Y=(#Sec.P#)R
Text="Change log v2.0"
MeterStyle=Sec.String:S | Style.Title:S

[Description.2_0]
Meter=String
Text="• Revamped settings UI#CRLF#• New Rounded and Center style#CRLF#• Prettier code syntax for developers#CRLF#• DLC support#CRLF#• Easier, more user-friendly customization#CRLF#• Version-applied default style and taskbar settings in setupp wizard"
MeterStyle=Sec.String:S | Style.Description:S
