[Variables]
Scale=1
Layout.fetch_icons=1
Layout.circ_size=6
Layout.volbar_width=(#W#-(#name_width#+22+75)*#scale#)
Layout.volbar_divide_margin=10

Width=500
name_width=190
line_pad=5
Font=Poppins
greyscale_icons=1
Corner=0

color_theme=Black
Accent=230,230,230
AccentNode=255,255,255
AccentNodeHover=255,255,255
Alpha=0
background_color=0,0,0
FontColor=255,255,255
VolumePeakColor=240,240,240
BackVolColorOver=150,150,150
BackVolColorLeave=100,100,100
