[Variables]
Scale=1
Layout.fetch_icons=1
Layout.volbar_width=(#W#-(#name_width#+22+75)*#scale#)
Layout.volbar_divide_margin=10

Width=470
MinH=0
name_width=190
line_pad=5
vol_icontheme=RegularSegoe
Font=Segoe UI
Stroke=0
Corner=0
DisplayName=1
background_style=Win10
Blur=Acrylic
BlurCorner=None

color_theme=Dark
Accent=35,159,255
AccentNode=35,159,255
AccentNodeHover=255,255,255
Alpha=150
background_color=36,36,36
Border=150,150,150
FontColor=255,255,255
VolumePeakColor=141,204,252
BackVolColorOver=80,80,80
BackVolColorLeave=60,60,60
