[Variables]
Scale=1
Layout.fetch_icons=1
Layout.circ_size=5
Layout.box_padding=(10*#scale#)
Layout.P=(25*#scale#)
Layout.left_box_width=(190*#scale#)
Layout.volbar_width=(230*#scale#)
Layout.volbar_divide_margin=(8*#scale#)
Width=(50+16+190+230)

Font=Roboto
Stroke=4
Corner=16

color_theme=Material Dark
Alpha=255
bar_color=51, 152, 255
background_color=28,28,28
FontColor=255,255,255
foreground_color=42,42,42
foreground_hover_color=64,64,64
shadow_color=0,0,0,0
