[Variables]
module_shortcuts.totalitems_count=1

[Shortcut1.Shape]
Meter=Shape
MeterStyle=Shortcut.Shape:S | Shortcut.Shape.NewLine:S
LeftMouseUpAction=["#SKINSPATH#Inlay\@Resources\@Structure\DefaultShortcuts\MosaicShell.url"]
[Shortcut1.Image]
Meter=Image
MeterStyle=Shortcut.Image:S
ImageName="#SKINSPATH#..\CoreData\Inlay\IconCache\MosaicShell_url.png"
[Shortcut1.String]
Meter=String
MeterStyle=RegularText | Shortcut.String:S
Text=MosaicShell
