[Rainmeter]
Update=-1
DefaultUpdateDivider=-1
OnRefreshAction=#Sec.StartAction#[!KeepOnScreen 0][!Delay 50][!CommandMeasure DefaultStartActions "Execute 1"][!SetOption #Sec.AnchorName# Y [#Sec.AnchorName#:Y]][!EnableMeasure AnchorChecker][!UpdateMeasure AnchorChecker][!EnableMeasureGroup NUOl][!UpdateMeter *][!Redraw]
DefaultAlwaysOnTop=1
DefaultDraggable=0
DefaultKeepOnscreen=0
RightMOuseUpAction=[]

[Focus]
Measure=Plugin
Plugin=Focus
FocusOnRefresh=1

[m.ShowInToolbar]
Measure=Plugin
Plugin=ShowInToolbar
WindowTitle=MosaicShell Generic Window
WindowIcon=#@#Images\Logo.ico

[FrostedGlass]
Measure=Plugin
Plugin=FrostedGlass
Type=#Set.Blur#
Corner=#Set.BlurCorner#
DynamicVariables=1
Border=All

[Variables]
@includeVars=#@#Vars.inc
Sec.P=(20*[S])
Sec.R=(10*[S])

Sec.Variant=C:\Users\Jax\AppData\Roaming\MosaicShell\InstalledComponents\ValliStart\Core\Window\Setup.inc
SEc.StartAction=
Scroll=0
Sec.AnchorName=Anchor
ScrollClickedPos=0

W=1248
H=864
B=2
WR=2
Maximized=0
Arg.1=1
Arg.2=2

[S]
Measure=Calc
Formula=1

[WindowSave]
Measure=Calc
X=2771
Y=168
W=2000
H=1920
S=0.75

Easetype=OutQuart
Animation_Steps=25
Animate_Offset=50
AniDir=Right
Sec.HideEsc=0

Arg.1=Module0
Arg.2=https://github.com/MosaicShell/Keystrokes/releases/download/v1.5/Keystrokes_v1.5.rmskin

; ---------------------------------------------------------------------------- ;
;                                   Function                                   ;
; ---------------------------------------------------------------------------- ;

[Func]
Measure=Script
ScriptFile=#@#Lua\Func.lua
DynamicVariables=1

[Sec.String:S]
FontFace=#Set.Font#
AntiAlias=1
FontSize=(10*[S])
ClipString=2
DynamicVariables=1
FontColor=#Set.Text_Color#
SolidColor=0,0,0,1
Container=ContentContainer

[DefaultStartActions]
Measure=Plugin
PLugin=ActionTimer
ActionList1=Custom0
Custom0=

[MeasureOnLoad]
Measure=Calc
Formula=Counter
IfEqualValue=1
IfEqualAction=[!WriteKeyValue Variables W (#SCREENAREAWIDTH#*0.65)][!WriteKeyValue Variables H (0.8*#SCREENAREAHEIGHT#)][!WriteKeyValue S Formula "((#SCREENAREAWIDTH#/1920) < (#SCREENAREAHEIGHT#/1080) ? (#SCREENAREAWIDTH#/1920) : (#SCREENAREAHEIGHT#/1080))"][!SetOption S Formula "((#SCREENAREAWIDTH#/1920) < (#SCREENAREAHEIGHT#/1080) ? (#SCREENAREAWIDTH#/1920) : (#SCREENAREAHEIGHT#/1080))"][!UpdateMeasure S][!SetVariable W (#SCREENAREAWIDTH#*0.65)][!SetVariable H (0.8*#SCREENAREAHEIGHT#)][!UpdateMeter *][!Redraw][!Move (#SCREENAREAWIDTH#*(0.5-0.65/2)) (#SCREENAREAHEIGHT#*(0.5-0.8/2))]
UpdateDivider=-1

[AnchorChecker]
Measure=Calc
Formula=(Clamp(#H#-#Sec.P#*2-[#Sec.AnchorName#:Y], -5000, 0))
IfCondition=AnchorChecker=0
IfTrueAction=[!DisableMouseAction ContentContainer "MouseScrollUpAction|MouseScrollDownAction"][!UpdateMeterGroup Background][!Redraw]
IfFalseAction=[!ShowMeter ScrollBar][!UpdateMeterGroup Background][!Redraw]
IfConditionMode=1
DynamicVariables=1
Disabled=1

[MouseScrollBar]
Measure=Plugin
Plugin=Mouse
MouseMoveAction=[!SetVariable Scroll "(Clamp(($MouseY$-#ScrollClickedPos#-#Sec.P#)/(#H#/2-#Sec.P#)*[AnchorChecker],[AnchorChecker],0))"][!UpdateMeter *][!Redraw]
LeftMouseUpAction=[!SetOption ScrollBar MeterStyle ScrollBar:Idle][!SetOption ScrollBar Fill "Stroke Color #Set.Ter_Color#"][!CommandMeasure MouseScrollBar "Stop"][!DisableMeasure MouseScrollBar][!UpdateMeter ScrollBar][!Redraw]
RequireDragging=1
RelativeToSkin=1
DynamicVariables=1
Disabled=1


[Window]
@IncludeWindow=#@#Includes/GenericWindow/Window.inc
@IncludeMouse=#@#Includes/GenericWindow/ScriptMouseHandler#Set.PerformanceMode#.ini

; ---------------------------------------------------------------------------- ;
;                                    Window                                    ;
; ---------------------------------------------------------------------------- ;

[B]
Meter=Shape
X=(#B#/2)
Y=(#B#/2)
Shape=Rectangle 0,0, #W#, #H#, #WR# | StrokeWidth #B# | Fill Color [#Set.Pri_Color] | Stroke Color [#Set.Ter_Color]
MouseActionCursor=0
DynamicVariables=1

[DragBar.Shape]
Meter=Shape
X=(#B#/2)
Y=(#B#/2)
Shape=Rectangle 0,0,#W#,(30*[S]),#WR# | StrokeWidth #B# | Fill Color [#Set.Ter_Color] | Stroke Color [#Set.Ter_Color]
MouseOverAction=[!CommandMeasure WindowHandler ToggleDrag(1)]
MouseLeaveAction=[!CommandMeasure WindowHandler ToggleDrag(0)]
LeftMouseDoubleClickAction=[!CommandMeasure WindowHandler ToggleMaximize()]
MouseActionCursor=0
DynamicVariables=1
[DragBar.Image]
Meter=Image
ImageName=#@#Images\CoreAssets\#Set.IconStyle#Logo64.png
X=(5*[S])r
Y=(5*[S])r
W=(30*[S]-10*[S])
H=(30*[S]-10*[S])
DynamicVariables=1
[DragBar.String]
Meter=String
X=(10*[S])R
y=(#B#/2+30*[S]/2)
FontSize=(8*[S])
FontColor=[#Set.Subtext_color]
MeterStyle=Sec.String:S | DragBar.String:S1
StringAlign=LeftCenter
Container=
MouseOverAction=[!SetOption #CURRENTSECTION# MeterStyle "Sec.String:S | DragBar.String:S2"][!Updatemeter #CURRENTSECTION#][!Redraw]
MouseLeaveAction=[!SetOption #CURRENTSECTION# MeterStyle "Sec.String:S | DragBar.String:S1"][!Updatemeter #CURRENTSECTION#][!Redraw]
[DragBar.String:S1]
Text=MosaicShell Generic Window - [&Func:trim('#Sec.Variant#', '#SKINSPATH#', '')]
[DragBar.String:S2]
Text=Variant #Sec.Variant#  - Scaled at [S]x

[ContentContainer]
Meter=Shape
X=(#B#/2)
Y=(#B#/2+30*[S])
Shape=Rectangle 0,0, #W#, (#H#-30*[S]), #WR# | StrokeWidth #B# | Fill Color [#Set.Pri_Color] | Stroke Color [#Set.Ter_Color]
DynamicVariables=1
MouseScrollDownAction=[!SetVariable Scroll "(Clamp(#Scroll#-50,[AnchorChecker],0))"][!UpdateMeter *][!Redraw]
MouseScrollUpAction=[!SetVariable Scroll "(Clamp(#Scroll#+50,[AnchorChecker],0))"][!UpdateMeter *][!Redraw]
MouseActionCursor=0
[ScrollBar:Scrolling]
Fill=Stroke Color #Set.Subtext_Color#
[ScrollBar:Idle]
LeftMouseDownAction=[!SetVariable ScrollClickedPos "$MouseY$"][!SetOption ScrollBar MeterStyle ScrollBar:Scrolling][!EnableMeasure MouseScrollBar][!UpdateMeasure MouseScrollBar][!CommandMeasure MouseScrollBar "Start"]
MouseOverAction=[!SetOption #CURRENTSECTION# Fill "Stroke Color #Set.Subtext_Color#"][!UpdateMeter #CURRENTSECTION#][!Redraw]
MouseLeaveAction=[!SetOption #CURRENTSECTION# Fill "Stroke Color #Set.Ter_Color#"][!UpdateMeter #CURRENTSECTION#][!Redraw]
[ScrollBar]
Meter=Shape
X=([ContentContainer:XW]-15*[Set.S])
Y=(#Sec.P#+(#Scroll#/([AnchorChecker]+1)*([ContentContainer:H]-([ContentContainer:H]/([ContentContainer:H]-[AnchorChecker])*[ContentContainer:H]))))
Shape=Line 0,0,0,([ContentContainer:H]/([ContentContainer:H]-[AnchorChecker])*[ContentContainer:H]) | StrokeWidth (4*[Set.S]) | StrokeStartCap Round | StrokeEndCap Round | Extend Fill
Fill=Stroke Color #Set.Ter_Color#
DynamicVariables=1
Group=Background | Scrollbar
Hidden=1
MeterStyle=ScrolLBar:Idle



; ---------------------------------------------------------------------------- ;
;                                    Buttons                                   ;
; ---------------------------------------------------------------------------- ;

[EscToggleMaximize]
Meter=Shape
X=(#W#-45*[S])
Y=(16*[S])
DynamicVariables=1
Shape=Ellipse 0,0,(5*[S]),(5*[S]) | StrokeWidth (20*[S]) | StrokeColor 0,0,0,1 | Fill Color 0,0,0,1
Shape2=Rectangle -4,-4,8,8 | StrokeWidth 0 | Extend FillE | Scale [S],[S] | Rotate 45
Triangle=-5,0 | LineTo 5,5 | LineTo 5,-5 | ClosePath 1
FillE=Fill Color [#Set.Text_Color],50
MouseOverAction=[!SetOption #CURRENTSECTION# FillE "Fill Color [#Set.Text_Color]"][!UpdateMeter #CURRENTSECTION#][!Redraw]
MouseLeaveAction=[!SetOption #CURRENTSECTION# FillE "Fill Color [#Set.Text_Color],50"][!UpdateMeter #CURRENTSECTION#][!Redraw]
LeftMouseUpAction=[!CommandMeasure WindowHandler ToggleMaximize()]


[Esc]
Meter=Shape
X=(29*[S])r
Y=r
DynamicVariables=1
Shape=Ellipse 0,0,(5*[S]),(5*[S]) | StrokeWidth (20*[S]) | StrokeColor 0,0,0,1 | Extend FillE
FillE=Fill Color [#Set.Text_Color],50
MouseOverAction=[!SetOption #CURRENTSECTION# FillE "Fill Color [#Set.Text_Color]"][!UpdateMeter #CURRENTSECTION#][!Redraw]
MouseLeaveAction=[!SetOption #CURRENTSECTION# FillE "Fill Color [#Set.Text_Color],50"][!UpdateMeter #CURRENTSECTION#][!Redraw]
LeftMouseUpAction=[!DeactivateConfig]
; LeftMouseUpAction=[!UpdateMeasure CheckPreview][!ActivateConfig "#CURRENTCONFIG#" "Home.ini"]
RightMOuseUpAction=[!commandMeasure Func "startDrop('Rainmeter', '#CURRENTSECTION#', 'MosaicShell')"]

@includeVariant=#Sec.Variant#

; ---------------------------- Page scroll anchor ---------------------------- ;

[Anchor]
Meter=String
Container=ContentContainer
x=r
Y=R
