[TimeUnderlay]
Meter=
[Time]
Meter=String
FontColor=#FontCOlor#
InlineSetting=Shadow | 0 | 0 | #Style_ShadowSigma# | 0,0,0,#ShadowStrength#
MeterStyle=String:S | Time:S
[TimeOverlay]
Meter=
[DateUnderlay]
Meter=
[Date]
Meter=String
X=(#SW#/2)
Y=(10*#Scale#-[Time:H]/2)r
FontColor=#FontCOlor#
InlineSetting=Shadow | 0 | 0 | #Style_ShadowSigma# | 0,0,0,#ShadowStrength#
MeterStyle=String:S | Date:S
[DateOverlay]
Meter=
