[Variables]
; ---------------------------- Operation settings ---------------------------- ;
Timeout=2
; ----------------------------- Behavior settings ---------------------------- ;
OptionalKey=0
Locks=1
Media=1
; ------------------------------ Legacy settings ----------------------------- ;
LegacyVol=0
LegacyVolChange=5
OverrideLocks=0
LegacyBright=0
BrightnessMode=-1
; ---------------------------- Animation settings ---------------------------- ;
Ani=2
AniDir=Left
AniSteps=20
Easetype=OutQuart
AnimationDisplacement=30
; ------------------------------- Smart volume ------------------------------- ;
SmartVolume=0
MediaKeyChange=5
; ----------------------------- Position settings ---------------------------- ;
Position=TL
MonitorIndex=1
XPad=20
YPad=20
; ------------------------------ Media settings ------------------------------ ;
MediaType=Modern
FetchImage=1
; ---------------------------------- Layout ---------------------------------- ;
Layout=Fluent
