

[Title.1_62]
Meter=String
Text="Change log v1.62"
MeterStyle=Sec.String:S | Style.Title:S

[Description.1_61.0]
Meter=String
Text="• Settings UI updated to match MosaicShell v5#CRLF#• UIv2 guides are added to allow easy understanding of settings."
MeterStyle=Sec.String:S | Style.Description:S


[Title.1_6]
Meter=String
Text="Change log v1.61"
Y=R
MeterStyle=Sec.String:S | Style.Title:S

[Description.1_6.0]
Meter=String
Text="• Using ESC key to turn off Slate should work consistently now#CRLF#• Added a setup wizard#CRLF#• Changed link to github guide for video player"
MeterStyle=Sec.String:S | Style.Description:S
