[Rainmeter]
Update=1000
AccurateText=1
OnCloseAction=["#@#Actions\AHKv1.exe" "#@#Actions\Source Code\Close.ahk"]
OnRefreshAction=["#@#Actions\AHKv1.exe" "#@#Actions\Source Code\Slate.ahk"][!Delay 50][!EnableMeasure mForce][!CommandMeasure Esc Stop]

[Variables]
@includeVars=#@#Vars.inc

; ---------------------------------------------------------------------------- ;
;                                   Functions                                  ;
; ---------------------------------------------------------------------------- ;

[Func]
Measure=Script
ScriptFile=#@#Lua\Func.lua
DynamicVariables=1
UpdateDivider=(#IgnoreIdleDuration# = 1 ? -1 : 1)

[CoreBridge]
Measure=Script
ScriptFile="#SKINSPATH##MosaicShell\@Resources\Lua\CoreElements\Toast.lua"
[mToggle]
Measure=Calc
Formula=1 - mToggle
IfCondition=mToggle = 0
IfTrueAction=[!CommandMEasure CoreBridge "start('', 'Slate toggled off', 'Idle timer is now paused and will remain until toggled', '', '1000')"]
IfCondition2=mToggle = 1 && #LoadedNotif# = 1
IfTrueAction2=[!CommandMEasure CoreBridge "start('', 'Slate is active', 'Slate will show up after #TimeOut# of idle time', '', '1000')"]
IfConditionMode=1
DynamicVariables=1
UpdateDivider=-1
[mForce]
Measure=Calc
OnUpdateAction=[!CommandMeasure Func "Force()"]
Disabled=1
UpdateDivider=-1
Group=NUOL

[Idletime]
Measure=SysInfo
SysInfoType=IDLE_TIME

[Youtubecheck]
Measure=Plugin
Plugin=WebNowPlaying
PlayerType=Player
Disabled=(1-#YoutubeCheck#)
OnChangeAction=[!CommandMeasure Func "CheckPause()"]
[YoutubeState]
Measure=Plugin
Plugin=WebNowPlaying
PlayerType=State
Disabled=(1-#YoutubeState#)
OnChangeAction=[!CommandMeasure Func "CheckPause()"]

[MeasureIsFullScreen]
Measure=Plugin
Plugin=IsFullScreen
Disabled=(1-#FullScreenCheck#)
OnChangeAction=[!CommandMeasure Func "CheckPause()"]

; ---------------------------------------------------------------------------- ;
;                                     Meter                                    ;
; ---------------------------------------------------------------------------- ;

[Dum]
Meter=String
