[Variables]
@includeScaleContract=#SKINSPATH##MosaicShell\@Resources\Includes\ScaleContract.inc
Scale=#UiScale#
ColorMode=0
MainColor=12,12,12
OppositeColor=255,255,255

Style=Center

Rm.Update=25
Render=Color

;RenderBlur (Brightness, Saturation, Hue)
BlurModulate=125,100,100
BlurRadius=5
BlurSigma=5

;RenderShadow
ShadowOpacity=80
ShadowSigma=10
ShadowOffset=0,0

;RenderBar
; BarBackpacity=150

Cache.Wallpaper=C:\Users\enhan\Pictures\Wallpapers\Minimalistic\soda-bg.png
FormatLocale=Local
