[Variables]
; -------------------------------- Activation -------------------------------- ;
Hotkey=1
StayOnDesktop=0
Tray=1
TrayScroll=0
IconTheme=SegoeDark
; --------------------------------- Behavior --------------------------------- ;
VolumeChangeLevel=2
ReplaceApp=".exe":""
ExcludeApp=rainmeter.exe; explorer.exe;
VolumePeaks=0
CollapseIcons=Combine
; -------------------------------- Appearance -------------------------------- ;
Layout=Fluent

BackgroundMod=0
header_text=Volume Mixer
IconSize=24

Animated=1
EaseType=OutQuart
AniDir=Bottom
AniSteps=18
AnimationDisplacement=30
; -------------------------------- Positional -------------------------------- ;
Position=BR
MonitorIndex=1
XPad=10
YPad=10
PreserveTaskbarSpace=1

Scale=1
