[PageList.Configuration]
Meter=String
MeterStyle=Set.String:S | PageList.Category:S
Text=BEHAVIORAL

[General.Shape]
Meter=Shape
MeterStyle=PageList.Item.Shape:S
[General.Icon.String]
Meter=String
Text="[\xe8b8]"
MeterStyle=Set.String:S | PageList.Item.Icon.String:S
[General.String]
Meter=String
Text=General
MeterStyle=Set.String:S | PageList.Item.String:S
[GlobalVars.Shape]
Meter=Shape
MeterStyle=PageList.Item.Shape:S
[GlobalVars.Icon.String]
Meter=String
Text="[\xe3f8]"
MeterStyle=Set.String:S | PageList.Item.Icon.String:S
[GlobalVars.String]
Meter=String
Text=Global settings
MeterStyle=Set.String:S | PageList.Item.String:S

[PageList.looknfeel]
Meter=String
MeterStyle=Set.String:S | PageList.Category:S
Text=LOOK N' FEEL

[Appearance.Shape]
Meter=Shape
MeterStyle=PageList.Item.Shape:S
[Appearance.Icon.String]
Meter=String
Text="[\xe243]"
MeterStyle=Set.String:S | PageList.Item.Icon.String:S
[Appearance.String]
Meter=String
Text=Appearance
MeterStyle=Set.String:S | PageList.Item.String:S
