﻿[Rainmeter]
Update=1000
@includevars=#@#Vars.inc
SkinWidth=(#Scale#*#SkinWidth#)
AccurateText=1
DynamicWindowSize=1
BackgroundMode=2
SolidColor=0, 0, 0, 1
DefaultAlwaysOnTop=2
DefaultSavePosition=0
DefaultClickThrough=1
DefaultAnchorY=B
DefaultKeepOnScreen=0
OnRefreshAction=[!UpdateMeter *] [!UpdateMeter *] [!Redraw]

[ExportVars]
Measure=String
String=#Alignment#
IfMatch=Left
IfMatchAction=[!SetWindowPosition ([#SCREENAREAX@#Location#]+[#SCREENAREAHEIGHT@#Location#]*0.05) ([#SCREENAREAY@#Location#]+[#SCREENAREAHEIGHT@#Location#]*0.95) 0 100% "Slate\Launch\Addons\JDWS"]
IfMatch2=Center
IfMatchAction2=[!SetWindowPosition ([#SCREENAREAX@#Location#]+[#SCREENAREAWIDTH@#Location#]/2) ([#SCREENAREAY@#Location#]+[#SCREENAREAHEIGHT@#Location#]/2) 50% 50% "Slate\Launch\Addons\JDWS"]
IfMatch3=Right
IfMatchAction3=[!SetWindowPosition ([#SCREENAREAX@#Location#]+[#SCREENAREAWIDTH@#Location#]-[#SCREENAREAHEIGHT@#Location#]*0.05) ([#SCREENAREAY@#Location#]+[#SCREENAREAHEIGHT@#Location#]*0.95) 100% 100% "Slate\Launch\Addons\JDWS"]
UpdateDivider=-1

; ================================================

[IncludeWeatherParser]
@Include=#@#Global\WeatherParser.inc
@Include2=#@#Global\WeatherParserDaily.inc

[Variables]
@includeConfigurableVariables=#ROOTCONFIGPATH#Launch\Vars\#Style#.inc

True=1
False=0

IconStyleMono=0
IconStyleColor=1
AlignmentLeft=0
AlignmentCenter=1
AlignmentRight=2

DetailsContainerScrollPlusOrMinus=-

; ================================================

[mDate]
Measure=Time
Format=%A %#d %B
FormatLocale=Locale

DynamicVariables=1

OnChangeAction=[!UpdateMeter *] [!UpdateMeter *] [!Redraw]

; ================================================

[Date]
Meter=String

Text=[mDate]

FontFace=Roboto
FontSize=(#Scale#*#DateSize#*0.75)
FontColor=255,255,255
FontWeight=500
AntiAlias=1

StringAlign=#Alignment#
ClipString=2
ClipStringW=(#Scale#*#SkinWidth#)

X=((#Scale#*#SkinWidth#)*([#Alignment[#Alignment]]/2))

DynamicVariables=1
UpdateDivider=-1

[CurrentTemperature]
Meter=String

Text=[mCurrentTemperature]

FontFace=Roboto
FontSize=(#Scale#*#CurrentTemperatureSize#*0.75)
FontColor=255,255,255
FontWeight=200
AntiAlias=1

StringAlign=#Alignment#
ClipString=1
W=(#Scale#*#SkinWidth#)

X=r
Y=R

DynamicVariables=1
UpdateDivider=-1

[CurrentPhrase]
Meter=String

Text=[mCurrentPhrase]

FontFace=Roboto
FontSize=(#Scale#*#CurrentPhraseSize#*0.75)
FontColor=255,255,255
FontWeight=500
AntiAlias=1

StringAlign=#Alignment#
ClipString=2
ClipStringW=(#Scale#*#SkinWidth#)

X=r
Y=(#Scale#*8)R

DynamicVariables=1
UpdateDivider=-1

[Day0Narrative]
Meter=String

Text=[mDay0Narrative]

FontFace=Roboto
FontSize=(#Scale#*#NarrativeSize#*0.75)
FontColor=255,255,255, (255*0.5)
AntiAlias=1

StringAlign=#Alignment#
ClipString=2
ClipStringW=(#Scale#*#SkinWidth#)

X=r
Y=R

DynamicVariables=1
UpdateDivider=-1

; ================================================

[mDetailsContainerScroll]
Measure=Calc

Formula=Clamp(mDetailsContainerScroll#DetailsContainerScrollPlusOrMinus#(Max(#Scale#*#DetailsIconSize#, [CurrentHumidity:H])+#Scale#*#DetailsIconSize#*0.5)/((1000/10)*0.1), 0, Max(#Scale#*#DetailsIconSize#, [CurrentHumidity:H])+#Scale#*#DetailsIconSize#*0.5)

DynamicVariables=1
UpdateDivider=-1

[mContainerScrollActionTimer]
Measure=Plugin
Plugin=ActionTimer

ActionList1=Repeat Scroll, 10, 10
Scroll=[!UpdateMeasure mDetailsContainerScroll] [!UpdateMeterGroup Details] [!Redraw]

[DetailsContainer]
Meter=Image

W=(#Scale#*#SkinWidth#)
H=(Max(#Scale#*#DetailsIconSize#, [CurrentHumidity:H]))
SolidColor=FFFFFF

Y=(#Scale#*16)R

DynamicVariables=1
UpdateDivider=-1

MouseOverAction=[!CommandMeasure mContainerScrollActionTimer "Stop 1"] [!SetVariable DetailsContainerScrollPlusOrMinus "+"] [!CommandMeasure mContainerScrollActionTimer "Execute 1"]
MouseLeaveAction=[!CommandMeasure mContainerScrollActionTimer "Stop 1"] [!SetVariable DetailsContainerScrollPlusOrMinus "-"] [!CommandMeasure mContainerScrollActionTimer "Execute 1"]

; ================================================

[CurrentHumidityIcon]
Group=Details
Meter=String

Text=humidity

FontFace=JDWI-MISC
FontSize=(#Scale#*#DetailsIconSize#*0.75)
FontColor=255,255,255
AntiAlias=1

X=((#Scale#*(#SkinWidth#-6.5*#DetailsIconSize#)-[CurrentHumidity:W]-[Day0Precipitation:W]-[CurrentWindSpeed:W])*([#Alignment[#Alignment]]/2)+(#DetailsFlip#=0 ? 0 : [CurrentHumidity:W]+#Scale#*#DetailsIconSize#*0.5))
Y=(Max(([CurrentHumidity:H]-#Scale#*#DetailsIconSize#)/2, 0)-[mDetailsContainerScroll])

DynamicVariables=1
UpdateDivider=-1
Container=DetailsContainer

[CurrentHumidity]
Group=Details
Meter=String

Text=[mCurrentHumidity]

FontFace=Roboto
FontSize=(#Scale#*#DetailsSize#*0.75)
FontColor=255,255,255
AntiAlias=1

X=(#DetailsFlip#=0 ? #Scale#*#DetailsIconSize#*0.5 : Neg(#Scale#*#DetailsIconSize#*1.5+[CurrentHumidity:W]))R
Y=((#Scale#*#DetailsIconSize#-[CurrentHumidity:H])/2)r

DynamicVariables=1
UpdateDivider=-1
Container=DetailsContainer

[Day0PrecipitationIcon]
Group=Details
Meter=String

Text=precipitation

FontFace=JDWI-MISC
FontSize=(#Scale#*#DetailsIconSize#*0.75)
FontColor=255,255,255
AntiAlias=1

X=(#DetailsFlip#=0 ? #Scale#*#DetailsIconSize# : #Scale#*#DetailsIconSize#*3+[Day0Precipitation:W])R
Y=(([CurrentHumidity:H]-#Scale#*#DetailsIconSize#)/2)r

DynamicVariables=1
UpdateDivider=-1
Container=DetailsContainer

[Day0Precipitation]
Group=Details
Meter=String

Text=[&mDay0[&mCheckDay0DayOrNight]Precipitation]

FontFace=Roboto
FontSize=(#Scale#*#DetailsSize#*0.75)
FontColor=255,255,255
AntiAlias=1

X=(#DetailsFlip#=0 ? #Scale#*#DetailsIconSize#*0.5 : Neg(#Scale#*#DetailsIconSize#*1.5+[Day0Precipitation:W]))R
Y=((#Scale#*#DetailsIconSize#-[Day0Precipitation:H])/2)r

DynamicVariables=1
UpdateDivider=-1
Container=DetailsContainer

[CurrentWindDirectionIcon]
Group=Details
Meter=String

Text=[mCurrentWindDirectionIcon]

FontFace=JDWI-WIND
FontSize=(#Scale#*#DetailsIconSize#*0.75)
FontColor=255,255,255
AntiAlias=1

X=(#DetailsFlip#=0 ? #Scale#*#DetailsIconSize# : #Scale#*#DetailsIconSize#*3+[CurrentWindSpeed:W])R
Y=(([Day0Precipitation:H]-#Scale#*#DetailsIconSize#)/2)r

DynamicVariables=1
UpdateDivider=-1
Container=DetailsContainer

[CurrentWindSpeed]
Group=Details
Meter=String

Text=[mCurrentWindSpeed] [mUnitsSpeed]

FontFace=Roboto
FontSize=(#Scale#*#DetailsSize#*0.75)
FontColor=255,255,255
AntiAlias=1

X=(#DetailsFlip#=0 ? #Scale#*#DetailsIconSize#*0.5 : Neg(#Scale#*#DetailsIconSize#*1.5+[CurrentWindSpeed:W]))R
Y=((#Scale#*#DetailsIconSize#-[CurrentWindSpeed:H])/2)r

DynamicVariables=1
UpdateDivider=-1
Container=DetailsContainer

; ================================================

[Day0SunriseIcon]
Group=Details
Meter=String

Text=sunrise

FontFace=JDWI-MISC
FontSize=(#Scale#*#DetailsIconSize#*0.75)
FontColor=255,255,255
AntiAlias=1

X=((#Scale#*(#SkinWidth#-6.5*#DetailsIconSize#)-[Day0Sunrise:W]-[Day0Sunset:W]-[Day0MoonPhase:W])*([#Alignment[#Alignment]]/2)+(#DetailsFlip#=0 ? 0 : [Day0Sunrise:W]+#Scale#*#DetailsIconSize#*0.5))
Y=(Max((#Scale#*#DetailsIconSize#-[CurrentHumidity:H])/2, 0)+Max(([Day0Sunrise:H]-#Scale#*#DetailsIconSize#)/2, 0)+#Scale#*#DetailsIconSize#*0.5)R

DynamicVariables=1
UpdateDivider=-1
Container=DetailsContainer

[Day0Sunrise]
Group=Details
Meter=String

Text=[mDay0Sunrise]

FontFace=Roboto
FontSize=(#Scale#*#DetailsSize#*0.75)
FontColor=255,255,255
AntiAlias=1

X=(#DetailsFlip#=0 ? #Scale#*#DetailsIconSize#*0.5 : Neg(#Scale#*#DetailsIconSize#*1.5+[Day0Sunrise:W]))R
Y=((#Scale#*#DetailsIconSize#-[Day0Sunrise:H])/2)r

DynamicVariables=1
UpdateDivider=-1
Container=DetailsContainer

[Day0SunsetIcon]
Group=Details
Meter=String

Text=sunset

FontFace=JDWI-MISC
FontSize=(#Scale#*#DetailsIconSize#*0.75)
FontColor=255,255,255
AntiAlias=1

X=(#DetailsFlip#=0 ? #Scale#*#DetailsIconSize# : #Scale#*#DetailsIconSize#*3+[Day0Sunset:W])R
Y=(([Day0Sunrise:H]-#Scale#*#DetailsIconSize#)/2)r

DynamicVariables=1
UpdateDivider=-1
Container=DetailsContainer

[Day0Sunset]
Group=Details
Meter=String

Text=[mDay0Sunset]

FontFace=Roboto
FontSize=(#Scale#*#DetailsSize#*0.75)
FontColor=255,255,255
AntiAlias=1

X=(#DetailsFlip#=0 ? #Scale#*#DetailsIconSize#*0.5 : Neg(#Scale#*#DetailsIconSize#*1.5+[Day0Sunset:W]))R
Y=((#Scale#*#DetailsIconSize#-[Day0Sunset:H])/2)r

DynamicVariables=1
UpdateDivider=-1
Container=DetailsContainer

[Day0MoonPhaseIcon]
Group=Details
Meter=String

Text=[mDay0MoonPhaseIcon]

FontFace=JDWI-MOON
FontSize=(#Scale#*#DetailsIconSize#*0.75)
FontColor=255,255,255
AntiAlias=1

X=(#DetailsFlip#=0 ? #Scale#*#DetailsIconSize# : #Scale#*#DetailsIconSize#*3+[Day0MoonPhase:W])R
Y=(([Day0Sunrise:H]-#Scale#*#DetailsIconSize#)/2)r

DynamicVariables=1
UpdateDivider=-1
Container=DetailsContainer

[Day0MoonPhase]
Group=Details
Meter=String

Text=[mDay0MoonPhase]

FontFace=Roboto
FontSize=(#Scale#*#DetailsSize#*0.75)
FontColor=255,255,255
AntiAlias=1

ClipString=2
ClipStringW=(#Scale#*(#SkinWidth#-6.5*#DetailsIconSize#)-[Day0Sunrise:W]-[Day0Sunset:W])
ClipStringH=[Day0Sunset:H]

X=(#DetailsFlip#=0 ? #Scale#*#DetailsIconSize#*0.5 : Neg(#Scale#*#DetailsIconSize#*1.5+[Day0MoonPhase:W]))R
Y=((#Scale#*#DetailsIconSize#-[Day0MoonPhase:H])/2)r

DynamicVariables=1
UpdateDivider=-1
Container=DetailsContainer

; ================================================

[MeterStyleDayNWeekdayShort]
FontFace=Roboto
FontSize=(#Scale#*#DailyWeekdaySize#*0.75)
FontColor=255,255,255
FontWeight=500
AntiAlias=1

StringAlign=Center
ClipString=1
W=(#Scale#*#DailyIconSize#)

X=(#Scale#*#DailyIconSize#*2)r
Y=[Day0WeekdayShort:Y]

DynamicVariables=1
UpdateDivider=-1

[MeterStyleDayNIconColor]
ImagePath=#@#icons\WeatherIcons

X=(Neg(#Scale#*#DailyIconSize#*0.5))r
Y=(#Scale#*#DailyIconSize#*0.125)R
W=(#Scale#*#DailyIconSize#)
H=(#Scale#*#DailyIconSize#)

DynamicVariables=1
UpdateDivider=-1
Hidden=([#IconStyle[#IconStyle]]=0 ? 1 : 0)

[MeterStyleDayNIconMono]
Text=[&mDay0[&mCheckDay0DayOrNight]Icon]

FontFace=JDWI
FontSize=(#Scale#*#DailyIconSize#*0.75)
FontColor=255,255,255
AntiAlias=1

X=r
Y=r

DynamicVariables=1
UpdateDivider=-1
Hidden=([#IconStyle[#IconStyle]]=1 ? 1 : 0)

[MeterStyleDayNTemperature]
FontFace=Roboto
FontSize=(#Scale#*#DailyTemperatureSize#*0.75)
FontColor=255,255,255
AntiAlias=1

InlineSetting=Color | 255,255,255, (255*0.5)
InlinePattern=.+ (.+)

StringAlign=Center
ClipString=1
W=(#Scale#*#DailyIconSize#)

X=(#Scale#*#DailyIconSize#*0.5)r
Y=(#Scale#*(#DailyIconSize#*1.125))r

DynamicVariables=1
UpdateDivider=-1

; ================================================

[Day0WeekdayShort]
Meter=String
MeterStyle=MeterStyleDayNWeekdayShort

Text=[mDay0WeekdayShort]

X=(#Scale#*#DailyIconSize#*0.5+(#Scale#*(#SkinWidth#-#DailyIconSize#*(4*2-1)))*([#Alignment[#Alignment]]/2))
Y=(#Scale#*16)R

[Day0IconColor]
Meter=Image
MeterStyle=MeterStyleDayNIconColor

ImageName=[&mDay0[&mCheckDay0DayOrNight]Icon].png

[Day0IconMono]
Meter=String
MeterStyle=MeterStyleDayNIconMono

Text=[&mDay0[&mCheckDay0DayOrNight]Icon]

[Day0Temperature]
Meter=String
MeterStyle=MeterStyleDayNTemperature

Text=[mDay0TemperatureMax] [mDay0TemperatureMin]

; ================================================

[Day1WeekdayShort]
Meter=String
MeterStyle=MeterStyleDayNWeekdayShort

Text=[mDay1WeekdayShort]

[Day1IconColor]
Meter=Image
MeterStyle=MeterStyleDayNIconColor

ImageName=[mDay1Icon].png

[Day1IconMono]
Meter=String
MeterStyle=MeterStyleDayNIconMono

Text=[mDay1Icon]

[Day1Temperature]
Meter=String
MeterStyle=MeterStyleDayNTemperature

Text=[mDay1TemperatureMax] [mDay1TemperatureMin]

; ================================================

[Day2WeekdayShort]
Meter=String
MeterStyle=MeterStyleDayNWeekdayShort

Text=[mDay2WeekdayShort]

[Day2IconColor]
Meter=Image
MeterStyle=MeterStyleDayNIconColor

ImageName=[mDay2Icon].png

[Day2IconMono]
Meter=String
MeterStyle=MeterStyleDayNIconMono

Text=[mDay2Icon]

[Day2Temperature]
Meter=String
MeterStyle=MeterStyleDayNTemperature

Text=[mDay2TemperatureMax] [mDay2TemperatureMin]

; ================================================

[Day3WeekdayShort]
Meter=String
MeterStyle=MeterStyleDayNWeekdayShort

Text=[mDay3WeekdayShort]

[Day3IconColor]
Meter=Image
MeterStyle=MeterStyleDayNIconColor

ImageName=[mDay3Icon].png

[Day3IconMono]
Meter=String
MeterStyle=MeterStyleDayNIconMono

Text=[mDay3Icon]

[Day3Temperature]
Meter=String
MeterStyle=MeterStyleDayNTemperature

Text=[mDay3TemperatureMax] [mDay3TemperatureMin]
