[@Resources\Vars.inc]

BackgroundMod=0


FixW=590
MinH=0
WinR=15
WinB=0
Pad=25



Blur=None
BlurCorner=Round
ImageUnderlay=1
ImageUnderlayAlpha=50


Font=Poppins
Stroke=1
Divider=1
R=10


Position=CC
AnimationDisplacement=30
XPad=10
YPad=10


Animated=1
EaseType=OutSine
AniDir=Bottom
AniSteps=10


Module0=GenericHeader
Module1=Shortcuts
Module2=Volume
Module3=Connection
Module4=Mon
Module5=None
Module6=HotApps




Alpha=255
Accent_Color=137,220,235
Pri_Color=18,18,18
Sec_Color=28,28,28
Ter_Color=35,35,35
Dark_Color=120,120,120
Font_Color=242,240,255

BoxColor=35,35,35
BoxBorder=35,35,35
Border=28,28,28

[Main\Modules\Vars\GenericHeader.inc]
IconName=Core



















