[@Resources\Vars.inc]

BackgroundMod=1
ListShowIcon=1
ListShowFolders=0
ListMax=100


FixW=590
MinH=0
WinR=15
WinB=0
Pad=25



Blur=None
BlurCorner=Round
ImageUnderlay=0
ImageUnderlayAlpha=50


Font=Poppins
Stroke=0
Divider=0
R=10


Position=CC
AnimationDisplacement=30
XPad=10
YPad=10


Animated=1
EaseType=OutSine
AniDir=Bottom
AniSteps=10


Module0=TimeDate
Module1=Volume
Module2=Connection
Module3=Music
Module4=Resource
Module5=None
Module6=PowerControl




Alpha=255
Accent_Color=242, 52, 0
Pri_Color=18,18,18
Sec_Color=28,28,28
Ter_Color=35,35,35
Dark_Color=120,120,120
Font_Color=242,240,255

BoxBorder=35,35,35
BoxColor=35,35,35
Border=28,28,28

[Main\Modules\Vars\GenericHeader.inc]
IconName=Core



















