[@Resources\Vars.inc]

BackgroundMod=0


FixW=420
MinH=0
WinR=8
WinB=1
Pad=25



Blur=Acrylic
BlurCorner=Round
ImageUnderlay=0
ImageUnderlayAlpha=50


Font=Poppins
Stroke=0
Divider=0
R=8


Position=CL
AnimationDisplacement=30
XPad=10
YPad=10


Animated=1
EaseType=OutSine
AniDir=Left
AniSteps=10


Module0=GenericHeader
Module1=Volume
Module2=Connection
Module3=Music
Module4=Resource
Module5=None
Module6=PowerControl



Alpha=175
Accent_Color=35,159,255
Pri_Color=36,36,36
Sec_Color=48,48,48
Ter_Color=60,60,60
Dark_Color=190,190,190
Font_Color=255,255,255

BoxColor=60,60,60
BoxBorder=80,80,80
Border=54,54,54
[Main\Modules\Vars\GenericHeader.inc]
IconName=Arrow




















