[@Resources\Vars.inc]

BackgroundMod=0


FixW=590
MinH=0
WinR=8
WinB=1
Pad=25



Blur=Acrylic
BlurCorner=Round
ImageUnderlay=0
ImageUnderlayAlpha=50


Font=Segoe UI
Stroke=1
Divider=1
R=8


Position=CC
AnimationDisplacement=30
XPad=10
YPad=10


Animated=1
EaseType=OutSine
AniDir=Bottom
AniSteps=10


Module0=GenericHeader
Module1=SearchBar
Module2=Shortcuts
Module3=Volume
Module4=Connection
Module5=None
Module6=HotApps




Alpha=175
Accent_Color=35,159,255
Pri_Color=36,36,36
Sec_Color=48,48,48
Ter_Color=60,60,60
Dark_Color=190,190,190
Font_Color=255,255,255
BoxBorder=80,80,80
BoxColor=60,60,60
Border=54,54,54
[Main\Modules\Vars\GenericHeader.inc]
IconName=Win11



















