[Rainmeter]
Update=1000
OnRefreshAction=[!CommandMeasure ActionTimer "Execute #Mode#"]
DefaultAlwaysOnTop=2
DefaultWindowX=0
DefaultWindowY=#WORKAREAHEIGHT#

[Variables]
@includeVars=#@#Vars.inc
@includeSize=Vars\WinBlock.inc
CurrentValliAction=[!UpdateMeasure mToggle "Inlay\Main"]
TweenNode1=255
isblock=1

[ActionTimer]
Measure=Plugin
Plugin=ActionTimer
DynamicVariables=1
ActionList1=Function | Repeat In,4,100 | End
ActionList2=Edit
In=[!SetVariable TweenNode1 "(Clamp((#TweenNode1#-255/100),0,255))"][!UpdateMeasure ActionTimer][!UpdateMeter Block][!Redraw]
End=[!SetOption Block SolidColor "0,0,0,1"][!UpdateMeasure ActionTimer][!UpdateMeter Block][!Redraw][!EnableMeasuregroup NUOL]
UpdateDivider=-1
Function=[!Draggable 0]
Edit=[!Draggable 1][!DisableMouseAction Block MouseOverAction|MouseLeaveAction][!KeepOnScreen 1]
; ---------------------------------------------------------------------------- ;
;                                   Functions                                  ;
; ---------------------------------------------------------------------------- ;

[Func]
Measure=Script
ScriptFile=#@#Lua\Func.lua
DynamicVariables=1
UpdateDivider=-1

[MeasureIsFullScreen]
Measure=Plugin
Plugin=IsFullScreen
OnChangeAction=[!CommandMeasure Func "CheckFullScreen()"]

[isValliOn]
Measure=Calc
Formula=0
IfCondition=isValliOn = 0
; Actions to run when vallistart -> inactivate
IfTrueAction=[!SetVariable CurrentValliAction """[!UpdateMeasure mToggle "Inlay\Main"]"""][!CommandMeasure Func "StopReceiver(500)"][!UpdateMeter Block]
; Actions to run when vallistart -> active
IfFalseAction=[!SetVariable CurrentValliAction """"""][!UpdateMeter Block]
UpdateDivider=-1

[valliActionReceiver]
Measure=Calc
OnUpdateAction=[!UpdateMeasure Func][!CommandMeasure Func "WinBlock()"]
DynamicVariables=1
UpdateDivider=-1
Group=NUOl
Disabled=1


; Active: Down -> Close, Up -> Void
; Inactivate: Down -> Void, Up -> Launch

; ---------------------------------------------------------------------------- ;
;                                    Content                                   ;
; ---------------------------------------------------------------------------- ;

[Block]
Meter=Shape
Shape=Rectangle 0,0,#AW#,#AH# | StrokeWidth 0 | Fill Color 0,0,0,1
Shape2=Rectangle #X#,#Y#,#W#,#H#,#R# | StrokeWidth 0 | Extend Fill
Fill=Fill Color 0,0,0,1
Hidden=(1-#WinblockDisplay#)
SolidColor=255,20,0,#TweenNode1#
DynamicVariables=1
MouseOverAction=[!SetOption Block Fill "Fill Color #OverColor#,#OverOpacity#"][!UpdateMeter Block][!Redraw]
MouseLeaveAction=[!SetOption Block Fill "Fill Color 0,0,0,1"][!UpdateMeter Block][!Redraw]
UpdateDivider=-1
LeftMouseUpAction=#CurrentValliAction#

