[Rainmeter]
Update=-1
DefaultSavePosition=0
DefaultAlwaysOnTop=2
DefaultDraggable=0
DefaultSnapEdges=0
DefaultStartHidden=0
DefaultAlphaValue=255
DefaultHideOnMouseOver=0
DefaultFadeDuration=100
DefaultClickThrough=0
DefaultKeepOnScreen=0
DefaultAutoSelectScreen=0
DefaultUpdateDivider=-1
AccurateText=1
OnRefreshAction=[!Delay 100][!WriteKeyValue "#CURRENTCONFIG#" "Active" "0" "#SETTINGSPATH#Rainmeter.ini"][!EnableMEasureGroup NUOL]
OnUnfocusAction=[!UpdateMeasure mToggle]

; ---------------------------------------------------------------------------- ;
;                                   Functions                                  ;
; ---------------------------------------------------------------------------- ;

[Esc]
Measure=Plugin
Plugin=Hotkey
HotKey=ESCAPE
KeyDownAction=[!UpdateMeasure mToggle]
UpdateDivider=-1

[Focus]
Measure=Plugin
Plugin=Focus
FocusOnRefresh=1

[Variables]
@includeVars=#@#Vars.inc
Sec.Parent="Inlay/Main"

Sec.S=#UiScale#
Sec.BoxH=(30*#Sec.S#)
Sec.W=(150*#Sec.S#)
Sec.P=(5*#Sec.S#)
Sec.H=([EndAnchor:Y]+#Sec.P#)
Sec.R=(#WinR#/2*#Sec.S#)

Easetype=InOutSine
Animation_Steps=10
Animate_Offset=10
AniDir=Bottom

Sec.LastX=361
Sec.LastY=716
Sec.Variant=Power

[FrostedGlass]
Measure=Plugin
Plugin=FrostedGlass
Type=#Blur#
Corner=#BlurCorner#
DynamicVariables=1
Border=All

[ActionTimer]
Measure=Plugin
Plugin=ActionTimer
DynamicVariables=1
ActionList1=Repeat In,2,#Animation_Steps# | Custom1
ActionList2=HideFade | Repeat Out,2,#Animation_Steps# | Hide | Custom0
Show=[!Show]
HideFade=[!HideFade]
Hide=[!Hide]
Custom0=[!EnableMeasure mToggle "Inlay\Main"][!CommandMeasure Focus "Inlay\Main"][!DeactivateConfig]
In=[!CommandMeasure Func "tweenAnimation('in')"]
Out=[!CommandMeasure Func "tweenAnimation('out')"]

[Func]
Measure=Script
ScriptFile=#SKINSPATH##MosaicShell\@Resources\Lua\SlideAnimation.lua
DynamicVariables=1
OnUpdateAction=[!CommandMeasure Func "importPosition(#Sec.LastX#, #Sec.LastY#, '50%', '100%')"][!CommandMeasure ActionTimer "Execute 1"]

[mToggle]
Measure=String
Formula=1 - mToggle
IfCondition=mToggle = 0
IfTrueAction=[!DisableMeasure mToggle][!CommandMeasure ActionTimer "Execute 2"]
IfCondition2=mToggle = 1
IfTrueAction2=
IfConditionMode=1
DynamicVariables=1
Disabled=1
Group=NUOL

; ---------------------------------------------------------------------------- ;
;                                  MeterStyles                                 ;
; ---------------------------------------------------------------------------- ;

[Sec.String:S]
FontFace=#Font#
AntiAlias=1
FontSize=((12*[Set.S])*#FontSizeModifier#)
FontColor=#Font_Color#
SolidColor=0,0,0,1

[SecBox:S]
X=(#Sec.P#+1)
Y=(#Sec.BoxH#/2+#Sec.P#)r
Shape=Rectangle 0,0,(#Sec.W#-#Sec.P#*2),(#Sec.BoxH#),(#Sec.R#/2),(#Sec.R#/2) | StrokeWidth 0 | Extend Fill
DynamicVariables=1
Group=Sec.SideButtons
Fill=Fill Color #Pri_color#,0
MouseOverAction=[!SetOption #CURRENTSECTION# Fill "Fill Color #Border#"][!SetOption #CURRENTSECTION#Icon ImageTint "Accent_Color"][!SetOption #CURRENTSECTION#Text Font_Color "Accent_Color"][!UpdateMeter *][!Redraw]
MouseLeaveAction=[!SetOption #CURRENTSECTION# Fill "Fill Color #Pri_color#,0"][!SetOption #CURRENTSECTION#Icon ImageTint "#Font_Color#"][!SetOption #CURRENTSECTION#Text Font_Color "#Font_Color#"][!UpdateMeter *][!Redraw]

[SecIcon:S]
ImageName=#@#Icons\Popup\#CURRENTSECTION#.png
X=(#Sec.P#*1.5+1)
Y=(#Sec.BoxH#/2-24/2*#Sec.S#)r
W=(19*#Sec.S#)
H=(19*#Sec.S#)
Padding=(2.5*#Sec.S#),(2.5*#Sec.S#),(2.5*#Sec.S#),(2.5*#Sec.S#)
DynamicVariables=1
GreyScale=1
ImageTint=#Font_Color#
Group=Sec.SideButtons | Sec.SideIcons

[SecText:S]
X=(5*#Sec.S#)R
Y=(24/2*#Sec.S#)r
StringAlign=LeftCenter
FontColor=#Font_Color#
FontSize=((10*#Sec.S#)*#FontSizeModifier#)
Group=Sec.SideButtons

[SecTextNoIcon:S]
X=(#Sec.P#*1.5+1)
Y=(#Sec.BoxH#/2*#Sec.S#)r
StringAlign=LeftCenter
FontColor=#Font_Color#
FontSize=((10*#Sec.S#)*#FontSizeModifier#)
Group=Sec.SideButtons

[SecTextIcon:S]
X=(#Sec.W#-1-#Sec.P#*1.5)
Y=r
StringAlign=RightCenter
FontFace=Segoe Fluent Icons
Text=[\xe970]
FontColor=#Font_Color#
FontSize=((10*#Sec.S#)*#FontSizeModifier#)
Group=Sec.SideButtons

[Sec.Div:S]
X=#Sec.P#
Y=(24*#Sec.S#+#Sec.P#)r
Shape=Line 0,0,(#Sec.W#-#Sec.P#*2),0 | StrokeWidth 1 | Fill Color #Set.Subtext_Color#,0 | Stroke Color #Set.Subtext_Color#,50

; ---------------------------------------------------------------------------- ;
;                                    Content                                   ;
; ---------------------------------------------------------------------------- ;

[BA]
Meter=Shape
X=1
Y=1
Shape=Rectangle #Sec.Stroke#,#Sec.Stroke#,#Sec.W#,#Sec.H#,#Sec.R# | Fill Color #Pri_color#,#Alpha# | StrokeWidth (2*#Scale#) | StrokeColor #BoxBorder#
DynamicVariables=1

@includePopupContent=Variants\#Sec.variant#.inc

[EndAnchor]
Meter=String
X=r
Y=(#Sec.BoxH#/2*#Sec.S#)r

