[Variables]
In=20
@includeScaleContract=#SKINSPATH##MosaicShell\@Resources\Includes\ScaleContract.inc
Scale=#UiScale#

Font=Consolas
FontAlias=1
FontWeight=100
Accent=255,255,255
FontColor=255,255,255
BarColor=150,150,150

PrefixText=Starting MS-DOS...#CRLF##CRLF#HIMEM is testing extended memory ... done.#CRLF#C:\>C:\DOS\SMARTDRV.exe /X#CRLF#C:\>CD RAINMETER~1#CRLF#C:\RAINME~1>PLAINEXT.EXE
BreakerString=-----------------------

CompactLook=0

Prefix=1
Name=1
Time=1
CPU=1
RAM=1
GPU=1
Drives=1
DriveChar=CD
Misc=1

Align=Left
Rm.Update=500
