[Variables]
@includegVar1=#SKINSPATH##MosaicShell\@Resources\gVars\Time.inc
@includeScaleContract=#SKINSPATH##MosaicShell\@Resources\Includes\ScaleContract.inc
TimeOut=5m
IgnoreIdleDuration=0
LoadedNotif=1

FullScreenCheck=1
YoutubeCheck=1
YoutubeState=1
Dev=0
Location=1
Stretch=0
Align=1
Blur=None
BackgroundOpacity=255

Style=CoreUI

SmartOverlayDetection=1
WindowX=556
WindowY=185
WindowW=862
WindowH=547
UseCustomOverlay=1
