[List.Item0.Shape]
Meter=Shape
LeftMouseDownAction=[!CommandMeasure CoreInstallHandler "Install Chrono v2.42"][!DeactivateConfig]
MeterStyle=List.Item.Shape:S
[List.Item0.Title.String]
Meter=String
Text=Added ImageMagick reminder
MeterStyle=Sec.String:S | List.Item.Title.String:S
[List.Item0.Date.String]
Meter=String
Text=2022-08-02
MeterStyle=Sec.String:S | List.Item.Date.String:S
[List.Item0.Version.String]
Meter=String
Text=v2.42
MeterStyle=Sec.String:S | List.Item.Version.String:S
[List.Item1.Shape]
Meter=Shape
LeftMouseDownAction=[!CommandMeasure CoreInstallHandler "Install Chrono v2.41"][!DeactivateConfig]
MeterStyle=List.Item.Shape:S
[List.Item1.Title.String]
Meter=String
Text=Changed links to gitbook
MeterStyle=Sec.String:S | List.Item.Title.String:S
[List.Item1.Date.String]
Meter=String
Text=2022-08-01
MeterStyle=Sec.String:S | List.Item.Date.String:S
[List.Item1.Version.String]
Meter=String
Text=v2.41
MeterStyle=Sec.String:S | List.Item.Version.String:S
[List.Item2.Shape]
Meter=Shape
LeftMouseDownAction=[!CommandMeasure CoreInstallHandler "Install Chrono v2.4"][!DeactivateConfig]
MeterStyle=List.Item.Shape:S
[List.Item2.Title.String]
Meter=String
Text=New style, new blur
MeterStyle=Sec.String:S | List.Item.Title.String:S
[List.Item2.Date.String]
Meter=String
Text=2022-07-16
MeterStyle=Sec.String:S | List.Item.Date.String:S
[List.Item2.Version.String]
Meter=String
Text=v2.4
MeterStyle=Sec.String:S | List.Item.Version.String:S
[List.Item3.Shape]
Meter=Shape
LeftMouseDownAction=[!CommandMeasure CoreInstallHandler "Install Chrono v2.3"][!DeactivateConfig]
MeterStyle=List.Item.Shape:S
[List.Item3.Title.String]
Meter=String
Text=Better settings UI + More options
MeterStyle=Sec.String:S | List.Item.Title.String:S
[List.Item3.Date.String]
Meter=String
Text=2022-07-04
MeterStyle=Sec.String:S | List.Item.Date.String:S
[List.Item3.Version.String]
Meter=String
Text=v2.3
MeterStyle=Sec.String:S | List.Item.Version.String:S
[List.Item4.Shape]
Meter=Shape
LeftMouseDownAction=[!CommandMeasure CoreInstallHandler "Install Chrono v2.23"][!DeactivateConfig]
MeterStyle=List.Item.Shape:S
[List.Item4.Title.String]
Meter=String
Text=Shortcut to change weather
MeterStyle=Sec.String:S | List.Item.Title.String:S
[List.Item4.Date.String]
Meter=String
Text=2022-05-21
MeterStyle=Sec.String:S | List.Item.Date.String:S
[List.Item4.Version.String]
Meter=String
Text=v2.23
MeterStyle=Sec.String:S | List.Item.Version.String:S
[List.Item5.Shape]
Meter=Shape
LeftMouseDownAction=[!CommandMeasure CoreInstallHandler "Install Chrono v2.22"][!DeactivateConfig]
MeterStyle=List.Item.Shape:S
[List.Item5.Title.String]
Meter=String
Text=Fixed blur key writing
MeterStyle=Sec.String:S | List.Item.Title.String:S
[List.Item5.Date.String]
Meter=String
Text=2022-03-02
MeterStyle=Sec.String:S | List.Item.Date.String:S
[List.Item5.Version.String]
Meter=String
Text=v2.22
MeterStyle=Sec.String:S | List.Item.Version.String:S
[List.Item6.Shape]
Meter=Shape
LeftMouseDownAction=[!CommandMeasure CoreInstallHandler "Install Chrono v2.21"][!DeactivateConfig]
MeterStyle=List.Item.Shape:S
[List.Item6.Title.String]
Meter=String
Text=Fixed translation issue + Clipping issue
MeterStyle=Sec.String:S | List.Item.Title.String:S
[List.Item6.Date.String]
Meter=String
Text=2022-02-10
MeterStyle=Sec.String:S | List.Item.Date.String:S
[List.Item6.Version.String]
Meter=String
Text=v2.21
MeterStyle=Sec.String:S | List.Item.Version.String:S
[List.Item7.Shape]
Meter=Shape
LeftMouseDownAction=[!CommandMeasure CoreInstallHandler "Install Chrono v2.2"][!DeactivateConfig]
MeterStyle=List.Item.Shape:S
[List.Item7.Title.String]
Meter=String
Text=Font change, UTF-16 encoding, UI fix, Coredata
MeterStyle=Sec.String:S | List.Item.Title.String:S
[List.Item7.Date.String]
Meter=String
Text=2022-02-04
MeterStyle=Sec.String:S | List.Item.Date.String:S
[List.Item7.Version.String]
Meter=String
Text=v2.2
MeterStyle=Sec.String:S | List.Item.Version.String:S
[List.Item8.Shape]
Meter=Shape
LeftMouseDownAction=[!CommandMeasure CoreInstallHandler "Install Chrono v2.14"][!DeactivateConfig]
MeterStyle=List.Item.Shape:S
[List.Item8.Title.String]
Meter=String
Text=Now uses global variables
MeterStyle=Sec.String:S | List.Item.Title.String:S
[List.Item8.Date.String]
Meter=String
Text=2022-01-25
MeterStyle=Sec.String:S | List.Item.Date.String:S
[List.Item8.Version.String]
Meter=String
Text=v2.14
MeterStyle=Sec.String:S | List.Item.Version.String:S
[List.Item9.Shape]
Meter=Shape
LeftMouseDownAction=[!CommandMeasure CoreInstallHandler "Install Chrono v2.13"][!DeactivateConfig]
MeterStyle=List.Item.Shape:S
[List.Item9.Title.String]
Meter=String
Text=Weather API key change
MeterStyle=Sec.String:S | List.Item.Title.String:S
[List.Item9.Date.String]
Meter=String
Text=2022-01-11
MeterStyle=Sec.String:S | List.Item.Date.String:S
[List.Item9.Version.String]
Meter=String
Text=v2.13
MeterStyle=Sec.String:S | List.Item.Version.String:S
[List.Item10.Shape]
Meter=Shape
LeftMouseDownAction=[!CommandMeasure CoreInstallHandler "Install Chrono v2.12"][!DeactivateConfig]
MeterStyle=List.Item.Shape:S
[List.Item10.Title.String]
Meter=String
Text=Fixed scroll and variable saving
MeterStyle=Sec.String:S | List.Item.Title.String:S
[List.Item10.Date.String]
Meter=String
Text=2022-01-02
MeterStyle=Sec.String:S | List.Item.Date.String:S
[List.Item10.Version.String]
Meter=String
Text=v2.12
MeterStyle=Sec.String:S | List.Item.Version.String:S
[List.Item11.Shape]
Meter=Shape
LeftMouseDownAction=[!CommandMeasure CoreInstallHandler "Install Chrono v2.11"][!DeactivateConfig]
MeterStyle=List.Item.Shape:S
[List.Item11.Title.String]
Meter=String
Text=Core4 Installer Compatability
MeterStyle=Sec.String:S | List.Item.Title.String:S
[List.Item11.Date.String]
Meter=String
Text=2021-12-11
MeterStyle=Sec.String:S | List.Item.Date.String:S
[List.Item11.Version.String]
Meter=String
Text=v2.11
MeterStyle=Sec.String:S | List.Item.Version.String:S
[List.Item12.Shape]
Meter=Shape
LeftMouseDownAction=[!CommandMeasure CoreInstallHandler "Install Chrono v2.1"][!DeactivateConfig]
MeterStyle=List.Item.Shape:S
[List.Item12.Title.String]
Meter=String
Text=Bug fixes and more customization
MeterStyle=Sec.String:S | List.Item.Title.String:S
[List.Item12.Date.String]
Meter=String
Text=2021-11-20
MeterStyle=Sec.String:S | List.Item.Date.String:S
[List.Item12.Version.String]
Meter=String
Text=v2.1
MeterStyle=Sec.String:S | List.Item.Version.String:S
[List.Item13.Shape]
Meter=Shape
LeftMouseDownAction=[!CommandMeasure CoreInstallHandler "Install Chrono v2.0"][!DeactivateConfig]
MeterStyle=List.Item.Shape:S
[List.Item13.Title.String]
Meter=String
Text=Color customization and more!
MeterStyle=Sec.String:S | List.Item.Title.String:S
[List.Item13.Date.String]
Meter=String
Text=2021-11-07
MeterStyle=Sec.String:S | List.Item.Date.String:S
[List.Item13.Version.String]
Meter=String
Text=v2.0
MeterStyle=Sec.String:S | List.Item.Version.String:S
[List.Item14.Shape]
Meter=Shape
LeftMouseDownAction=[!CommandMeasure CoreInstallHandler "Install Chrono v1.6"][!DeactivateConfig]
MeterStyle=List.Item.Shape:S
[List.Item14.Title.String]
Meter=String
Text=Bug fixes
MeterStyle=Sec.String:S | List.Item.Title.String:S
[List.Item14.Date.String]
Meter=String
Text=2021-11-03
MeterStyle=Sec.String:S | List.Item.Date.String:S
[List.Item14.Version.String]
Meter=String
Text=v1.6
MeterStyle=Sec.String:S | List.Item.Version.String:S
[List.Item15.Shape]
Meter=Shape
LeftMouseDownAction=[!CommandMeasure CoreInstallHandler "Install Chrono v1.5"][!DeactivateConfig]
MeterStyle=List.Item.Shape:S
[List.Item15.Title.String]
Meter=String
Text=Core format update
MeterStyle=Sec.String:S | List.Item.Title.String:S
[List.Item15.Date.String]
Meter=String
Text=2021-10-09
MeterStyle=Sec.String:S | List.Item.Date.String:S
[List.Item15.Version.String]
Meter=String
Text=v1.5
MeterStyle=Sec.String:S | List.Item.Version.String:S
[List.Item16.Shape]
Meter=Shape
LeftMouseDownAction=[!CommandMeasure CoreInstallHandler "Install Chrono v1.4"][!DeactivateConfig]
MeterStyle=List.Item.Shape:S
[List.Item16.Title.String]
Meter=String
Text=Fixed issue with installing Core (Global update)
MeterStyle=Sec.String:S | List.Item.Title.String:S
[List.Item16.Date.String]
Meter=String
Text=2021-08-28
MeterStyle=Sec.String:S | List.Item.Date.String:S
[List.Item16.Version.String]
Meter=String
Text=v1.4
MeterStyle=Sec.String:S | List.Item.Version.String:S
[List.Item17.Shape]
Meter=Shape
LeftMouseDownAction=[!CommandMeasure CoreInstallHandler "Install Chrono v1.3"][!DeactivateConfig]
MeterStyle=List.Item.Shape:S
[List.Item17.Title.String]
Meter=String
Text=Start menu update.
MeterStyle=Sec.String:S | List.Item.Title.String:S
[List.Item17.Date.String]
Meter=String
Text=2021-08-26
MeterStyle=Sec.String:S | List.Item.Date.String:S
[List.Item17.Version.String]
Meter=String
Text=v1.3
MeterStyle=Sec.String:S | List.Item.Version.String:S
[List.Item18.Shape]
Meter=Shape
LeftMouseDownAction=[!CommandMeasure CoreInstallHandler "Install Chrono v1.2"][!DeactivateConfig]
MeterStyle=List.Item.Shape:S
[List.Item18.Title.String]
Meter=String
Text=Arc Tech + new blur
MeterStyle=Sec.String:S | List.Item.Title.String:S
[List.Item18.Date.String]
Meter=String
Text=2021-08-05
MeterStyle=Sec.String:S | List.Item.Date.String:S
[List.Item18.Version.String]
Meter=String
Text=v1.2
MeterStyle=Sec.String:S | List.Item.Version.String:S
[List.Item19.Shape]
Meter=Shape
LeftMouseDownAction=[!CommandMeasure CoreInstallHandler "Install Chrono v1.1"][!DeactivateConfig]
MeterStyle=List.Item.Shape:S
[List.Item19.Title.String]
Meter=String
Text=Clocks v1.1 - MosaicShell
MeterStyle=Sec.String:S | List.Item.Title.String:S
[List.Item19.Date.String]
Meter=String
Text=2021-07-16
MeterStyle=Sec.String:S | List.Item.Date.String:S
[List.Item19.Version.String]
Meter=String
Text=v1.1
MeterStyle=Sec.String:S | List.Item.Version.String:S
[List.Item20.Shape]
Meter=Shape
LeftMouseDownAction=[!CommandMeasure CoreInstallHandler "Install Chrono v1.0"][!DeactivateConfig]
MeterStyle=List.Item.Shape:S
[List.Item20.Title.String]
Meter=String
Text=Clocks 1.0
MeterStyle=Sec.String:S | List.Item.Title.String:S
[List.Item20.Date.String]
Meter=String
Text=2021-06-27
MeterStyle=Sec.String:S | List.Item.Date.String:S
[List.Item20.Version.String]
Meter=String
Text=v1.0
MeterStyle=Sec.String:S | List.Item.Version.String:S

