[PageList.Configuration]
Meter=String
MeterStyle=Set.String:S | PageList.Category:S
Text=CONFIGURATION

[Info.Shape]
Meter=Shape
MeterStyle=PageList.Item.Shape:S
[Info.Icon.String]
Meter=String
Text="[\xe88e]"
MeterStyle=Set.String:S | PageList.Item.Icon.String:S
[Info.String]
Meter=String
Text=Info
MeterStyle=Set.String:S | PageList.Item.String:S

[General.Shape]
Meter=Shape
MeterStyle=PageList.Item.Shape:S
[General.Icon.String]
Meter=String
Text="[\xe8b8]"
MeterStyle=Set.String:S | PageList.Item.Icon.String:S
[General.String]
Meter=String
Text=General
MeterStyle=Set.String:S | PageList.Item.String:S

[Audio.Shape]
Meter=Shape
MeterStyle=PageList.Item.Shape:S
[Audio.Icon.String]
Meter=String
Text="[\xe1b8]"
MeterStyle=Set.String:S | PageList.Item.Icon.String:S
[Audio.String]
Meter=String
Text=Audio
MeterStyle=Set.String:S | PageList.Item.String:S

[PageList.looknfeel]
Meter=String
MeterStyle=Set.String:S | PageList.Category:S
Text=LOOK N' FEEL

[Appearance.Shape]
Meter=Shape
MeterStyle=PageList.Item.Shape:S
[Appearance.Icon.String]
Meter=String
Text="[\xe243]"
MeterStyle=Set.String:S | PageList.Item.Icon.String:S
[Appearance.String]
Meter=String
Text=Appearance
MeterStyle=Set.String:S | PageList.Item.String:S

[Layout.Shape]
Meter=Shape
MeterStyle=PageList.Item.Shape:S
[Layout.Icon.String]
Meter=String
Text="[\xe936]"
MeterStyle=Set.String:S | PageList.Item.Icon.String:S
[Layout.String]
Meter=String
Text=Layout
MeterStyle=Set.String:S | PageList.Item.String:S

[AddOns.Shape]
Meter=Shape
MeterStyle=PageList.Item.Shape:S
[AddOns.Icon.String]
Meter=String
Text="[\xe53b]"
MeterStyle=Set.String:S | PageList.Item.Icon.String:S
[AddOns.String]
Meter=String
Text=3D Overlay
MeterStyle=Set.String:S | PageList.Item.String:S

[Render.Shape]
Meter=Shape
MeterStyle=PageList.Item.Shape:S
[Render.Icon.String]
Meter=String
Text="[\xe3a2]"
MeterStyle=Set.String:S | PageList.Item.Icon.String:S
[Render.String]
Meter=String
Text=Render options
MeterStyle=Set.String:S | PageList.Item.String:S
