; ---------------------------------------------------------------------------- ;
;                                   Packager                                   ;
; ---------------------------------------------------------------------------- ;

[Setup]
PluginsFolder=

[Version]
AudioAnalyzer=2.0.3.3
CursorColor=1.3.0.0
FrostedGlass=1.1.2
FileChoose=1.2.0.1
magickmeter=0.7.4.0
ConfigActive=2.2.1.0
Focus=1.0.0.1
Mouse=3.2.0
MouseXY=1.0.0.0
PowershellRM=0.6.0.0
ShowInToolbar=1.0.0.0
HotKey=1.0.0.12
Chameleon=1.6.2.0
IsFullScreen=3.0.0.0
WebNowPlaying=0.5.0.0
Drag&Drop=3.1.0.3
AppVolume=1.3.0.0
TrayIcon=1.1.1.0
SysColor=1.1.0.15
Backlight=0.9.3.0
Tessera=1.1.0.0
FlightModeWatcher=1.1.0.0
ScreenBrightness=0.2.0.0
WindowsNowPlaying=1.0.0.1

; ---------------------------------------------------------------------------- ;
;                                  WebContent                                  ;
; ---------------------------------------------------------------------------- ;

[Droptop]
VarFiles=Droptop\@Resources\GlobalVar\UserSettings.inc | Droptop\@Resources\GlobalVar\TopBarPos.inc | Droptop\@Resources\GlobalVar\Supporter.inc | Droptop\@Resources\GlobalVar\FolderSettings.inc | Droptop\@Resources\GlobalVar\CustomAppSettings.inc | Droptop\@Resources\Symbols\Symbols11.inc | Droptop\@Resources\Themes\1Settings.inc | Droptop\@Resources\Themes\2Settings.inc | Droptop\@Resources\Themes\3Settings.inc | Droptop\@Resources\Themes\4Settings.inc | Droptop\@Resources\Themes\5Settings.inc | Droptop\@Resources\Themes\6Settings.inc | Droptop\@Resources\Themes\7Settings.inc | Droptop\@Resources\Themes\8Settings.inc | Droptop\@Resources\Themes\9Settings.inc | Droptop\@Resources\Themes\10Settings.inc | Droptop\@Resources\Themes\11Settings.inc | Droptop\@Resources\Themes\12Settings.inc | Droptop\@Resources\Themes\13Settings.inc | Droptop\@Resources\Themes\14Settings.inc | Droptop\@Resources\Themes\15Settings.inc | Droptop\@Resources\Themes\16Settings.inc | Droptop\@Resources\Themes\17Settings.inc | Droptop\@Resources\Themes\18Settings.inc | Droptop\@Resources\Themes\19Settings.inc | Droptop\@Resources\Themes\20Settings.inc | Droptop\@Resources\Themes\21Settings.inc | Droptop\@Resources\Themes\22Settings.inc | Droptop\@Resources\Themes\99.inc | Droptop\@Resources\Themes\99Settings.inc

[MosaicShellDLCs]
DLCList=Vekl|Sleek
ModuleList=Inlay|Mixdeck|Tessera

[CustomUserImages]
Pulse=@Resources\Vars.inc=ImageUnderlayName
Inlay=@Resources\Vars.inc=ImageUnderlayPath

[SHubPreferences]
SectionFilterPattern=^Rainmeter$|^#MosaicShell|^Chord|^Shade|^Slate|@Start$|^;|^TaskbarX|^Polybar
PreserveSections=Rainmeter|#MosaicShell\Accessories\UpdatePrompt|Chord\Main|Slate\Main|TaskbarX
TaggedModules=Inlay|Tessera|Mixdeck|Droptop

; ---------------------------------------------------------------------------- ;
;                                  MosaicShell                                 ;
; ---------------------------------------------------------------------------- ;

[MosaicShell]
LoadSkin=Main\Installation\Main.ini
SkinFolderName=#MosaicShell
VarFiles={#}MosaicShell\@Resources\Vars.inc | {#}MosaicShell\@Resources\gVars\Time.inc | {#}MosaicShell\@Resources\gVars\Weather.inc
Creator=uairhahs
Plugins=8
Plugin1=ConfigActive
Plugin2=Focus
Plugin3=Mouse
Plugin4=MouseXY
Plugin5=PowershellRM
Plugin6=ShowInToolbar
Plugin7=FileChoose
Plugin8=FrostedGlass

[IdleWebview]
LoadSkin=Main\Main.ini
SkinFolderName=IdleWebview
VarFiles=IdleWebview\@Resources\Vars.inc
Creator=uairhahs
Plugins=5
Plugin1=IsFullScreen
Plugin2=WindowsNowPlaying
Plugin3=Hotkey
Plugin4=Webview
Plugin5=FrostedGlass

; ---------------------------------------------------------------------------- ;
;                                    Tiles                                     ;
; ---------------------------------------------------------------------------- ;

[SnipControl]
LoadSkin=@Start\Main.ini
SkinFolderName=SnipControl
VarFiles=SnipControl\@Resources\Vars.inc
Creator=uairhahs
Plugins=0

[Tessera]
LoadSkin=@Start\Main.ini
SkinFolderName=Tiles\Tessera
VarFiles=Tiles\Tessera\@Resources\Vars.inc | Tiles\Tessera\@Resources\WelcomeVars.inc | Tiles\Tessera\@Resources\Actions\Hotkeys.ini | Tiles\Tessera\Main\Vars\Center.inc | Tiles\Tessera\Main\Vars\CoreUI.inc | Tiles\Tessera\Main\Vars\Fluent.inc | Tiles\Tessera\Main\Vars\Modern.inc | Tiles\Tessera\Main\Vars\Canvas.inc | Tiles\Tessera\Main\Vars\Side.inc | Tiles\Tessera\Main\Vars\Simple.inc | Tiles\Tessera\Main\Vars\Vekl.inc | Tiles\Tessera\Main\Vars\Sleek.inc | Tiles\Tessera\Main\Vars\Win11.inc | Tiles\Tessera\Main\Vars\Pixel.inc
Creator=uairhahs
Plugins=9
Plugin1=Hotkey
Plugin2=IsFullScreen
Plugin3=WebNowPlaying
Plugin4=WindowsNowPlaying
Plugin5=SysColor
Plugin6=FlightModeWatcher
Plugin7=Tessera
Plugin8=ScreenBrightness
Plugin9=Backlight

[Mixdeck]
LoadSkin=@Start\Main.ini
SkinFolderName=Tiles\Mixdeck
VarFiles=Tiles\Mixdeck\@Resources\Vars.inc | Tiles\Mixdeck\@Resources\WelcomeVars.inc | Tiles\Mixdeck\Main\Accessories\Unload\Vars.inc | Tiles\Mixdeck\@Resources\Actions\Hotkeys.ini | Tiles\Mixdeck\Main\Elements\ControlScreen\Vars\Center.inc | Tiles\Mixdeck\Main\Elements\ControlScreen\Vars\Fluent.inc | Tiles\Mixdeck\Main\Elements\ControlScreen\Vars\Rounded.inc | Tiles\Mixdeck\Main\Elements\ControlScreen\Vars\Vekl.inc
Creator=uairhahs
Plugins=5
Plugin1=Hotkey
Plugin2=IsFullScreen
Plugin3=AppVolume
Plugin4=TrayIcon
Plugin5=Tessera

[Inlay]
LoadSkin=@Start\Main.ini
SkinFolderName=Tiles\Inlay
VarFiles=Tiles\Inlay\@Resources\Vars.inc | Tiles\Inlay\@Resources\WelcomeVars.inc | Tiles\Inlay\Main\Accessories\Unload\Vars.inc | Tiles\Inlay\@Resources\Shortcuts.inc | Tiles\Inlay\@Resources\Actions\Hotkeys.ini | Tiles\Inlay\@Resources\HotApps.inc | Tiles\Inlay\Main\Modules\Vars\GenericHeader.inc | Tiles\Inlay\Main\Modules\Vars\Hotapps.inc | Tiles\Inlay\Main\Modules\Vars\Music.inc | Tiles\Inlay\Main\Modules\Vars\Shortcuts.inc | Tiles\Inlay\Main\Modules\Vars\VeklBarHeader.inc | Tiles\Inlay\Main\Modules\Vars\VeklDWFMeasures.inc | Tiles\Inlay\Main\Modules\Vars\VeklResource.inc | Tiles\Inlay\Main\Modules\Vars\VeklVolume.inc | Tiles\Inlay\Main\Modules\Vars\Volume.inc | Tiles\Inlay\Main\Modules\Vars\Weather.inc
Creator=uairhahs
Plugins=5
Plugin1=Hotkey
Plugin2=IsFullScreen
Plugin3=WebNowPlaying
Plugin4=WindowsNowPlaying
Plugin5=Tessera

[Slate]
LoadSkin=@Start\Main.ini
SkinFolderName=Tiles\Slate
VarFiles=Tiles\Slate\@Resources\Vars.inc | Tiles\Slate\@Resources\WelcomeVars.inc | Tiles\Slate\Launch\Vars\CoreUI.inc | Tiles\Slate\Launch\Vars\CustomPaper.inc | Tiles\Slate\Launch\Vars\CustomGroup.inc | Tiles\Slate\Launch\Vars\CustomVideo.inc | Tiles\Slate\Launch\Vars\JD.inc | Tiles\Slate\Launch\Vars\Ninety.inc | Tiles\Slate\Launch\Vars\String.inc | Tiles\Slate\@Resources\Actions\Hotkeys.ini
Creator=uairhahs
Plugins=3
Plugin1=IsFullScreen
Plugin2=WebNowPlaying
Plugin3=Hotkey

[Chord]
LoadSkin=@Start\Main.ini
SkinFolderName=Tiles\Chord
VarFiles=Tiles\Chord\@Resources\Vars.inc
Creator=uairhahs
Plugins=0

[Shade]
LoadSkin=@Start\Main.ini
SkinFolderName=Tiles\Shade
VarFiles=Tiles\Shade\@Resources\Vars.inc | Tiles\Shade\@Resources\Actions\Hotkeys.ini
Creator=uairhahs
Plugins=3
Plugin1=HotKey
Plugin2=IsFullScreen
Plugin3=WebNowPlaying

[Pulse]
LoadSkin=@Start\Main.ini
SkinFolderName=Tiles\Pulse
VarFiles=Tiles\Pulse\@Resources\Vars.inc | Tiles\Pulse\@Resources\Visualizer\Bar.inc | Tiles\Pulse\@Resources\Visualizer\Round.inc | Tiles\Pulse\@Resources\Visualizer\Vector.inc | Tiles\Pulse\@Resources\Vars\Bar\MirrorX.inc | Tiles\Pulse\@Resources\Vars\Bar\MirrorXY.inc | Tiles\Pulse\@Resources\Vars\Bar\MirrorY.inc | Tiles\Pulse\@Resources\Vars\Bar\Normal.inc | Tiles\Pulse\@Resources\Vars\Bar\Reflection.inc | Tiles\Pulse\@Resources\Vars\Vector\Gradient.inc | Tiles\Pulse\@Resources\Vars\Vector\Solid.inc | Tiles\Pulse\@Resources\Vars\AudioAnalyzerSettings.inc | Tiles\Pulse\@Resources\Vars\Bar.inc | Tiles\Pulse\@Resources\Vars\Colors.inc | Tiles\Pulse\@Resources\Vars\Round.inc | Tiles\Pulse\@Resources\Vars\Vector.inc | Tiles\Pulse\@Resources\Measures\AudioMeasures.inc
Creator=uairhahs
Plugins=5
Plugin1=AudioAnalyzer
Plugin2=Drag&Drop
Plugin3=WindowsNowPlaying
Plugin4=CursorColor
Plugin5=WebNowPlaying

[Chrono]
LoadSkin=@Start\Main.ini
SkinFolderName=Tiles\Chrono
VarFiles=Tiles\Chrono\@Resources\Vars.inc | Tiles\Chrono\Main\Styles\Vars\Arc.inc | Tiles\Chrono\Main\Styles\Vars\Center.inc | Tiles\Chrono\Main\Styles\Vars\CircTech.inc | Tiles\Chrono\Main\Styles\Vars\Graph.inc | Tiles\Chrono\Main\Styles\Vars\Light.inc | Tiles\Chrono\Main\Styles\Vars\Measure.inc | Tiles\Chrono\Main\Styles\Vars\Smart.inc | Tiles\Chrono\Main\Styles\Vars\Tech.inc | Tiles\Chrono\Main\Styles\Vars\Text.inc | Tiles\Chrono\Main\Styles\Vars\16.inc
Creator=uairhahs
Plugins=1
Plugin1=magickmeter

[Phono]
LoadSkin=@Start\Main.ini
SkinFolderName=Tiles\Phono
VarFiles=Tiles\Phono\@Resources\Vars.inc | Tiles\Phono\Main\Vars\Win11.inc | Tiles\Phono\Main\Vars\BigCirc.inc | Tiles\Phono\Main\Vars\Blur.inc | Tiles\Phono\Main\Vars\Card.inc | Tiles\Phono\Main\Vars\Center.inc | Tiles\Phono\Main\Vars\DoubleCirc.inc | Tiles\Phono\Main\Vars\Fortnite.inc | Tiles\Phono\Main\Vars\MIUI.inc | Tiles\Phono\Main\Vars\Modern.inc | Tiles\Phono\Main\Vars\Neumorphism.inc | Tiles\Phono\Main\Vars\Side.inc | Tiles\Phono\Main\Vars\Simple.inc | Tiles\Phono\Main\Vars\16.inc
Creator=uairhahs
Plugins=4
Plugin1=magickmeter
Plugin2=WebNowPlaying
Plugin3=WindowsNowPlaying
Plugin4=Chameleon

[Canvas]
LoadSkin=@Start\Main.ini
SkinFolderName=Tiles\Canvas
VarFiles=Tiles\Canvas\@Resources\Vars.inc
Creator=uairhahs
Plugins=0
