[Variables]
@includegVar2=#SKINSPATH##MosaicShell\@Resources\gVars\Weather.inc
@includegVar3=#SKINSPATH##MosaicShell\@Resources\gVars\WeatherAPIKey.inc
Align=Center
Weather=1
Date=1
Time=1
Shadow=1
DateTimeRatio=0.14
Seperator=:
TintColor=255,255,255
TintIcon=0
ShadowColor=0,0,0
FontFace=MetroPolis Semi Bold
ShowLeadingZero=0
LeadingZeroCharacter0=#
LeadingZeroCharacter1=
ShowSeconds=0
SecondsCharacter0=
SecondsCharacter1=%S

Scale=1
