[Rainmeter]
Update=1000
DefaultSavePosition=0
DefaultAlwaysOnTop=1
DefaultDraggable=0
DefaultSnapEdges=0
DefaultStartHidden=1
DefaultAlphaValue=255
DefaultHideOnMouseOver=0
DefaultFadeDuration=100
DefaultClickThrough=0
DefaultKeepOnScreen=0
DefaultAutoSelectScreen=0

DefaultUpdateDivider=-1
AccurateText=1
SkinWidth=(#W#+#WinB#*2)
SkinHeight=(#H#+#WinB#*2)
OnCloseAction=[!DeactivateConfig "Inlay\Main\Accessories\VolumeHook"]["#@#Actions\AHKv1.exe" "#@#Actions\Source Code\Close.ahk"]["#@#Actions\AHKv1.exe" "#@#Actions\Source Code\Close2.ahk"]
OnRefreshAction=[!Delay 100][!EnableMeasureGroup NUOL]
OnUnfocusAction=[!UpdateMeasure mToggleSet]
@includeCtx=#SKINSPATH##MosaicShell\CoreShell\}{CtxItms.inc

[Variables]
@include=#@#Vars.inc
@includeKeys=#@#Actions\HotKeys.ini
@includegVar1=#SKINSPATH##MosaicShell\@Resources\gVars\Time.inc
; @includeCoreDataVars=#SKINSPATH#..\CoreData\Vars.inc

ActualBlur=None
TweenNode1=0
MusicModuleCheckerVariable=0

W=(#FixW#*#Scale#)
; H=(Clamp(((12+90)+[##Module0#Height]+[##Module1#Height]+[##Module2#Height]+[##Module3#Height]+[##Module4#Height]+[##Module5#Height])*#Scale#,(#MinH#*#scale#),#SCREENAREAHEIGHT#))
H=(Clamp(([Anchor:Y]),(#MinH#*#scale#),#SCREENAREAHEIGHT#))
P=(#Pad#*#Scale#)
; ---------------------------------------------------------------------------- ;
;                                   Functions                                  ;
; ---------------------------------------------------------------------------- ;

[Esc]
Measure=Plugin
Plugin=Hotkey
HotKey=ESCAPE
KeyDownAction=[!UpdateMeasure mToggleSet]
UpdateDivider=-1

[Focus]
Measure=Plugin
Plugin=Focus

[Func]
Measure=Script
ScriptFile=#@#Lua\Func.lua

[FrostedGlass]
Measure=Plugin
Plugin=FrostedGlass
Type=#ActualBlur#
Corner=#BlurCorner#
DynamicVariables=1
Border=All
;Acrylic | Blur

[MeasureMouse]
Plugin=Mouse
; this measure uses the Plugin:Mouse
LeftMouseDragAction=[!CommandMEasure Func "DragMultiSlider($mouseX$)"]
; actions to be executed when the mouse drags. The first bang gets the mouse value and make sure it's in the slider. The bangs after that updates the required measures and the slider.
LeftMouseUpAction=[!CommandMEasure Func "TermMultiSlider()"]
; actions to be executed after the mouse click is lifted. The first bang stops the measure to retrieve information from mouse dragging.
RelativeToSkin=1
RequireDragging=1
DynamicVariables=1

[CheckForWinSkin]
Measure=Plugin
Plugin=ConfigActive
ConfigName=Inlay\WinBlock
IfCondition=CheckForWinSkin = 1
IfTrueAction=[!EnableMeasure WinBlockTransmitter]
OnUpdateAction=[!DisableMeasure #CURRENTSECTION#]
[WinBlockTransmitter]
Measure=Calc
Formula=1
IfCondition=WinBlockTransmitter = 1
IftrueAction=[!SetOption isValliOn Formula 1 "Inlay\WinBlock"][!UpdateMeasure isValliOn "Inlay\WinBlock"]
IfFalseAction=[!SetOption isValliOn Formula 0 "Inlay\WinBlock"][!UpdateMeasure isValliOn "Inlay\WinBlock"]
IfConditionMode=1
Disabled=1
Group=WinBlockTransmitter
[DroptopTransmitter]
Measure=Calc
Formula=1
IfCondition=DroptopTransmitter = 1
IftrueAction=[!SetOption isValliOn Formula 1 "Droptop\Dropdownbar"][!UpdateMeasure isValliOn "Droptop\Dropdownbar"]
IfFalseAction=[!SetOption isValliOn Formula 0 "Droptop\Dropdownbar"][!UpdateMeasure isValliOn "Droptop\Dropdownbar"]
IfConditionMode=1
Disabled=(1-#DroptopIntegration#)
Group=WinBlockTransmitter
[mToggle]
Measure=Calc
Formula=1 - mToggle
IfCondition=mToggle = 0
IfTrueAction=[!UpdateMeasure ACTIONLOAD][!CommandMeasure Esc Start][!SetOptionGroup WinBlockTransmitter Formula 1][!UpdateMeasureGroup WinBlockTransmitter][!CommandMEasure Focus "#CURRENTCONFIG#"][!UpdateMeasure CheckCheckKeyPress]
IfCondition2=mToggle = 1
IfTrueAction2=[!UpdateMeasure ACTIONUNLOAD][!CommandMeasure Esc Stop][!Delay 100]["#@#Actions\AHKv1.exe" "#@#Actions\Source Code\Close2.ahk"][!SetOptionGroup WinBlockTransmitter Formula 0][!UpdateMeasureGroup WinBlockTransmitter]
IfConditionMode=1
DynamicVariables=1
[mToggleSet]
Measure=Calc
Formula=mToggle
IfCondition=mToggle = 0
iftrueaction=[!UpdateMeasure mToggle]
ifconditionmode=1
Group=NUOL
Disabled=1
[CheckCheckKeyPress]
Measure=Calc
Formula=#TypeToSearch#
ifCondition=#TypeToSearch# = 1
iftrueaction=["#@#Actions\AHKv1.exe" "#@#Actions\Source Code\CheckKeyPress.ahk"]
ifconditionmode=1
Group=NUOL
Disabled=1

[SettingImport5]
Measure=String
String=#FetchImage#
IfMatch=0
IfMatchAction=[!SetOptionGroup MusicImg ImageName ""][!UpdateMeterGroup MusicImg]

[MeasureUser]
Measure=Plugin
Plugin=SysInfo
SysInfoType=USER_NAME

[m.OnLoad]
Measure=Calc
Formula=Counter
OnUpdateAction=[!CommandMeasure Func "valliStartAHK()"]
LastHotkey=#q1CC1
; ---------------------------------------------------------------------------- ;
;                                  MeterStyles                                 ;
; ---------------------------------------------------------------------------- ;

[Divider]
X=(22*#scale#)
Y=r
Shape=Line 0,0,(#W#-44*#Scale#),0 | StrokeWidth (#Divider#*1) | Stroke Color #Border#

; ---------------------------------------------------------------------------- ;
;                                    Content                                   ;
; ---------------------------------------------------------------------------- ;

[Background]
Meter=Shape
X=(#WinB#)
Y=(#WinB#)
Shape=Rectangle 0,0,#W#,#H#,(#WinR#*#scale#),(#WinR#*#scale#) | StrokeWidth (#WinB#*2) | Stroke Color #Border#,#Alpha# | Fill Color #Pri_color#,#Alpha#
DynamicVariables=1

@includeTweenNode1Style=#@#Includes\Animation#Animated#.inc
@includeImageUnderlay=#@#Includes\ImageUnderlay#ImageUnderlay#.inc

; ---------------------------------------------------------------------------- ;
;                                    Modules                                   ;
; ---------------------------------------------------------------------------- ;

[NoModules]
@includeNoModules=#@#Includes\ModuleAllNone#ModuleAllNone#.inc

[Module0]
@includeModule0=Modules\#Module0#.inc

[Divider0]
Meter=Shape
MeterStyle=Divider

[Module1]
@includeModule1=Modules\#Module1#.inc

[Divider1]
Meter=Shape
MeterStyle=Divider

[Module2]
@includeModule2=Modules\#Module2#.inc

[Divider2]
Meter=Shape
MeterStyle=Divider

[Module3]
@includeModule3=Modules\#Module3#.inc

[Divider3]
Meter=Shape
MeterStyle=Divider

[Module4]
@includeModule4=Modules\#Module4#.inc

[Divider4]
Meter=Shape
MeterStyle=Divider

[Module5]
@includeModule5=Modules\#Module5#.inc

[Divider5]
Meter=Shape
MeterStyle=Divider

[Module6]
@includeModule6=Modules\#Module6#.inc

[Anchor]
Meter=String
Y=r









; ---------------------------------------------------------------------------- ;
;                                    Footer                                    ;
; ---------------------------------------------------------------------------- ;


;///////////////////////////////////////////////////////////////////////////////////////////////////
;                                              Measures
;///////////////////////////////////////////////////////////////////////////////////////////////////


@includeMusic=#@#Includes\GlobalMusic#MediaType##MusicModuleCheckerVariable#.inc

; @includeMeasures=#@#Includes\GlobalMeasures.inc
