[Rainmeter]
Update=#Rm.Update#
DynamicWindowSize=1
Rightmouseupaction=[!SkinCustomMenu]
ContextTitle=Config
ContextAction=[!ActivateConfig "Plainext\@Settings" "Info.ini"][!DeactivateConfig]
OnRefreshAction=[!Delay 1000][!CommandMeasure MeasureCPUName "Run"][!CommandMeasure MeasureGPUName "Run"][!CommandMeasure MeasureMotherboardname "Run"][!CommandMeasure CPUPhyC "Run"][!CommandMeasure CPUVirC "Run"]

@includeCtx=#SKINSPATH##MosaicShell\CoreShell\}{CtxItms.inc
[Variables]

@includeVars=#@#Vars.inc
Blacklist="_Total|Idle|dwm"

W=(500*#scale#)
Sec.Ctx.Left=1

@includeGS=#@#Includes\GlobalStyles.inc

@includeMAINM=@Measures\MAINM.inc



; = = = = = METERS = = = = =

@includePrefix=@#Prefix#\Prefix.inc

@includeName=@#Name#\Name.inc

@includeTime=@#Time#\Time.inc

[Dot1]
Meter=String
MeterStyle=Dots | FirstAlign:#Align#

@includeCPU=@#CPU#\CPU.inc

@includeRAM=@#RAM#\RAM.inc

@includeGPU=@#GPU#\GPU.inc

@includeDisk=@#Drives#\Drives.inc

@includeMisc=@#Misc#\Misc.inc


@includeStyle=@#CompactLook#\Overview.inc
