[Rainmeter]
Update=-1
DefaultSavePosition=0
DefaultAlwaysOnTop=1
DefaultDraggable=0
DefaultSnapEdges=0
DefaultStartHidden=1
DefaultAlphaValue=255
DefaultHideOnMouseOver=0
DefaultFadeDuration=100
DefaultClickThrough=0
DefaultKeepOnScreen=0
DefaultAutoSelectScreen=0
DefaultUpdateDivider=-1
DynamicWindowSize=1
OnRefreshAction=[!Delay 100][!DisableMouseActionGroup "LeftMouseUpAction" Shortcut.Shape][!DisableMouseActionGroup "LeftMouseUpAction | MouseOverAction | MouseLeaveAction" Editor.Button.Shape][!UpdateMeterGroup Shortcut.Shape][!UpdateMeterGroup Editor.Button.String][!CommandMeasure p.ActionTimer "Execute 1"][!EnableMEasureGroup NUOL]

[Variables]
@includeModuleVariable=#ROOTCONFIGPATH#Main\Modules\Vars\Shortcuts.inc
@includeVars=#@#Vars.inc

process.x=10
process.y=583
process.w=212
process.module_shortcuts.rowitems_count=4
module_shortcuts.shortcut_shape_w=((#process.W#-50*#scale#-#module_shortcuts.items.p#*(#module_shortcuts.rowitems_count#-1))/#module_shortcuts.rowitems_count#)
title_h=(30*#scale#)
h=([Anchor:Y]+(25*2+30*3+10*2)*#scale#)
process.tween_node_0=1

; ---------------------------------------------------------------------------- ;
;                                   Functions                                  ;
; ---------------------------------------------------------------------------- ;

[p.ActionTimer]
Measure=Plugin
Plugin=ActionTimer
ActionList1=StartTween
;  | Repeat In,2,1
ActionList2=Deactivate
; EndTween | Repeat Out,2,40 |
StartTween=[!SetWindowPosition (#SCREENAREAWIDTH#/2) (#SCREENAREAHEIGHT#/2) 50% 50%][!Show]
EndTween=[!CommandMeasure s.SimpleAnimation "endTween()"]
Deactivate=[!DeactivateConfig "Inlay\Main\Accessories\ShortcutsEditor\Background"][!ActivateConfig "Inlay\Main"][!DeactivateConfig]

[s.ShortcutFunc]
Measure=Script
ScriptFile=#@#Lua\ShortcutFunc.lua

[Focus]
Measure=Plugin
Plugin=Focus
FocusOnRefresh=1

[FrostedGlass]
Measure=Plugin
Plugin=FrostedGlass
Type=#Blur#
Corner=#BlurCorner#
DynamicVariables=1
Border=All

[mToggle]
Measure=String
Formula=1 - mToggle
IfCondition=mToggle = 0
IfTrueAction=[!DisableMeasure mToggle][!CommandMeasure p.ActionTimer "Execute 2"]
IfCondition2=mToggle = 1
IfTrueAction2=
IfConditionMode=1
DynamicVariables=1
Disabled=1
Group=NUOL

[p.FileChoose]
Measure=Plugin
Plugin=FileChoose
ReturnValue=WholePath
FileInitialDirectory=
AllowNonstorageFolder=1
CopyLink=1
GetIcon=1
IconCache=#SKINSPATH#..\CoreData\Inlay\IconCache\
IconSize=3
DynamicVariables=1
GetTarget=0
Command1=[!CommandMeasure p.PSRM """ShortcutChangeTo -index #process.index# -selectedFile "$Path$" -selectedFileName "$Name$" -returnedImageName "$Name$_$Ext$"""" "Inlay\Main\Accessories\ShortcutsEditor\Background"]
Command2=[!CommandMeasure p.PSRM """ShortcutImageChangeTo -index #process.index# -selectedFile "$Path$"""" "Inlay\Main\Accessories\ShortcutsEditor\Background"]
Command3=[!CommandMeasure p.PSRM """ShortcutNew -index #process.index# -selectedFile "$Path$" -selectedFileName "$Name$" -returnedImageName "$Name$_$Ext$" -ti #module_shortcuts.totalitems_count# -ri #process.module_shortcuts.rowitems_count#""" "Inlay\Main\Accessories\ShortcutsEditor\Background"]

[p.InputText]
Measure=Plugin
Plugin=InputText
SolidColor=#Ter_Color#
FontColor=#Font_Color#
FontFace=#Font#
FontSize=(10)
StringAlign=Center
X=(25*#Scale#)
Y=(25*#Scale#)
W=(#process.W#-50*#scale#)
DynamicVariables=1
DefaultValue="..."
Command1=[!CommandMeasure p.PSRM """ShortcutNameChangeTo -index #process.index# -name "$UserInput$"""" "Inlay\Main\Accessories\ShortcutsEditor\Background"]

; ---------------------------------------------------------------------------- ;
;                                  MeterStyles                                 ;
; ---------------------------------------------------------------------------- ;

[Shortcut.Shape:S]
Group=Shortcut.Shape
LeftMouseDownAction=[!CommandMeasure s.ShortcutFunc "ChangeIndex('#CURRENTSECTION#')"]

@includeShortcutStyles=#ROOTCONFIGPATH#Main\Modules\Includes\Shortcuts\#ShortcutBoxStyles#.inc

; ------------------------------ Editor buttons ------------------------------ ;

[Editor.Button.Shape:S]
X=((#process.W#-(25*2+10*1)*#Scale#)/2/2+10*#scale#)r
Y=(-30*#Scale#/2)r
Shape=Rectangle 0,0,((#process.W#-(25*2+10*1)*#Scale#)/2),(30*#Scale#),(#R#/2*#Scale#) | StrokeWidth 0 | Extend This
This=Fill Color #Sec_color#
MouseOverAction=[!SetOption #CURRENTSECTION# This "Fill Color #Ter_Color#"][!UpdateMeter #CURRENTSECTION#][!Redraw]
MouseLeaveAction=[!SetOption #CURRENTSECTION# This "Fill Color #Sec_color#"][!UpdateMeter #CURRENTSECTION#][!Redraw]
DynamicVariables=1
Group=Editor.Button.Shape | Editor.Button
[Editor.Button.String:S]
X=((#process.W#-(25*2+10*1)*#Scale#)/2/2)r
Y=(30*#Scale#/2)r
StringAlign=CenterCenter
Text=N/A
FontColor=#Dark_Color#
DynamicVariables=1
W=((#process.W#-(25*2+10*1)*#Scale#)/2-10*#scale#)
ClipString=1
Group=Editor.Button.String | Editor.Button

[Editor.MoveButton.Shape:S]
X=((#process.W#-(25*2+10*3)*#Scale#)/4/2+10*#scale#)r
Y=(-30*#Scale#/2)r
Shape=Rectangle 0,0,((#process.W#-(25*2+10*3)*#Scale#)/4),(30*#Scale#),(#R#/2*#Scale#) | StrokeWidth 0 | Extend This
This=Fill Color #Sec_color#
MouseOverAction=[!SetOption #CURRENTSECTION# This "Fill Color #Ter_Color#"][!UpdateMeter #CURRENTSECTION#][!Redraw]
MouseLeaveAction=[!SetOption #CURRENTSECTION# This "Fill Color #Sec_color#"][!UpdateMeter #CURRENTSECTION#][!Redraw]
DynamicVariables=1
Group=Editor.Button.Shape | Editor.Button
[Editor.MoveButton.String:S]
X=((#process.W#-(25*2+10*3)*#Scale#)/4/2)r
Y=(30*#Scale#/2)r
StringAlign=CenterCenter
Text=N/A
FontFace=Segoe Fluent Icons
FontColor=#Dark_Color#
DynamicVariables=1
Group=Editor.Button.String | Editor.Button

; ---------------------------------------------------------------------------- ;
;                                    Content                                   ;
; ---------------------------------------------------------------------------- ;

[Background.Shape]
Meter=Shape
X=(#WinB#)
Y=(#WinB#)
Shape=Rectangle 0,0,#process.W#,#H#,(#WinR#*#scale#),(#WinR#*#scale#) | StrokeWidth (#WinB#*2) | Stroke Color #Border#,#Alpha# | Fill Color #Pri_color#,#Alpha# | Scale #process.tween_node_0#,#process.tween_node_0#,0,0
DynamicVariables=1
Group=Tween

[Header.String]
Meter=String
X=(25*#scale#)
Y=(25*#scale#)
Text=Edit shortcuts
FontSize=(16*#Scale#)
FontWeight=600
MeterStyle=RegularText

[SettingsButton.String]
Meter=String
X=(#process.W#-25*#Scale#)
Y=r
FontSize=(16*#Scale#)
Text=[\xe713]
LeftMouseUpAction=[!WriteKeyValue Variables Skin.Name #ROOTCONFIG# "#SKINSPATH##MosaicShell\@Resources\CacheVars\Configurator.inc"][!WriteKeyValue Variables Skin.Set_Page Modules "#SKINSPATH##MosaicShell\@Resources\CacheVars\Configurator.inc"][!WriteKeyValue Variables Page.Page 2 "#ROOTCONFIGPATH#Core\Modules.inc"][!WriteKeyValue Variables Page.SubpageModule Shortcuts "#ROOTCONFIGPATH#Core\Modules.inc"][!ActivateConfig "#MosaicShell\Main" "Settings.ini"][!UpdateMeasure mToggle]
FontFace=Segoe Fluent Icons
StringAlign=Right
MeterStyle=RegularText

[CloseButton.String]
Meter=String
X=(#process.W#-8*#Scale#)
Y=(8*#scale#)
FontSize=(8*#Scale#)
Text=[\xe8bb]
LeftMouseUpAction=[!UpdateMeasure mToggle]
FontFace=Segoe Fluent Icons
StringAlign=Right
FontColor=#Dark_Color#,200
MeterStyle=RegularText

; ----------------------------------- List ----------------------------------- ;

[Shortcut1.Shape]
X=(25*#scale#)
Y=(50*#scale#+#title_h#)

@includeShortcuts=#SKINSPATH#..\CoreData\Inlay\Shortcuts.inc

[Shortcut.New.Shape]
Meter=Shape
MeterStyle=[&s.ShortcutFunc:ReturnShortcutNewShapeMeterStyle()]
DynamicVariables=1
LeftMouseUpAction=[!CommandMeasure s.ShortcutFunc "ShortcutNew()"]
Group=
[Shortcut.New.String]
Meter=String
X=(#module_shortcuts.shortcut_shape_w#/2)r
Y=(#module_shortcuts.shortcut_shape_w#/2)r
FontSize=(20*#Scale#)
Text=[\xf8aa]
FontFace=Segoe Fluent Icons
StringAlign=CenterCenter
MeterStyle=RegularText

; ---------------------------------------------------------------------------- ;
;                                Anchor and more                               ;
; ---------------------------------------------------------------------------- ;

[Anchor]
Meter=String
Y=(#module_shortcuts.shortcut_shape_w#/2)r

[Editor.Button1.Shape]
Meter=Shape
X=(25*#scale#)
Y=(#H#-(25+30*3+10*2)*#scale#)
LeftMouseUpAction=[!CommandMeasure s.ShortcutFunc "ShortcutSelect('File')"]
MeterStyle=Editor.Button.Shape:S
[Editor.Button1.String]
Meter=String
Text=Change target
MeterStyle=RegularText | Editor.Button.String:S

[Editor.Button2.Shape]
Meter=Shape
LeftMouseUpAction=[!CommandMeasure s.ShortcutFunc "ShortcutSelect('Image')"]
MeterStyle=Editor.Button.Shape:S
[Editor.Button2.String]
Meter=String
Text=Change image
MeterStyle=RegularText | Editor.Button.String:S

[Editor.Button3.Shape]
Meter=Shape
X=(25*#scale#)
Y=((10+15)*#scale#)r
LeftMouseUpAction=[!CommandMeasure s.ShortcutFunc "ShortcutChange('Name')"]
MeterStyle=Editor.Button.Shape:S
[Editor.Button3.String]
Meter=String
Text=Change name
MeterStyle=RegularText | Editor.Button.String:S

[Editor.Button4.Shape]
Meter=Shape
LeftMouseUpAction=[!CommandMeasure s.ShortcutFunc "ShortcutRemove()"]
MeterStyle=Editor.Button.Shape:S
[Editor.Button4.String]
Meter=String
Text=Remove shortcut
MeterStyle=RegularText | Editor.Button.String:S

[Editor.MoveButton1.Shape]
Meter=Shape
X=(25*#scale#)
Y=((10+15)*#scale#)r
LeftMouseUpAction=[!CommandMeasure s.ShortcutFunc "ShortcutMove('Left')"]
MeterStyle=Editor.MoveButton.Shape:S
[Editor.MoveButton1.String]
Meter=String
Text=[\xf0b0]
MeterStyle=RegularText | Editor.MoveButton.String:S

[Editor.MoveButton2.Shape]
Meter=Shape
LeftMouseUpAction=[!CommandMeasure s.ShortcutFunc "ShortcutMove('Up')"]
MeterStyle=Editor.MoveButton.Shape:S
[Editor.MoveButton2.String]
Meter=String
Text=[\xf0ad]
MeterStyle=RegularText | Editor.MoveButton.String:S

[Editor.MoveButton3.Shape]
Meter=Shape
LeftMouseUpAction=[!CommandMeasure s.ShortcutFunc "ShortcutMove('Down')"]
MeterStyle=Editor.MoveButton.Shape:S
[Editor.MoveButton3.String]
Meter=String
Text=[\xf0ae]
MeterStyle=RegularText | Editor.MoveButton.String:S

[Editor.MoveButton4.Shape]
Meter=Shape
LeftMouseUpAction=[!CommandMeasure s.ShortcutFunc "ShortcutMove('Right')"]
MeterStyle=Editor.MoveButton.Shape:S
[Editor.MoveButton4.String]
Meter=String
Text=[\xf0af]
MeterStyle=RegularText | Editor.MoveButton.String:S

; ------------------------------------ -x ------------------------------------ ;

[Overlay.Background.Shape]
Meter=Shape
Shape=Rectangle 0,0,#module_shortcuts.shortcut_shape_w#,#module_shortcuts.shortcut_shape_w#,(#R#*#Scale#) | StrokeWidth 4 | Fill Color 0,0,0,0 | Stroke Color #Ter_Color#
Hidden=1
Group=Overlay
