﻿[Rainmeter]
Update=1000
DefaultSavePosition=0
DefaultAlwaysOnTop=0
DefaultDraggable=0
DefaultSnapEdges=0
DefaultStartHidden=1
DefaultAlphaValue=255
DefaultHideOnMouseOver=0
DefaultFadeDuration=100
DefaultClickThrough=0
DefaultKeepOnScreen=0
DefaultAutoSelectScreen=0
DefaultUpdateDivider=-1

AccurateIconName=1
SkinWidth=#W#
SkinHeight=#H#
OnCloseAction=[!DeactivateConfig "Mixdeck\Main\Elements\ControlScreen"]["#@#Actions\AHKv1.exe" "#@#Actions\Source Code\Close.ahk"]

[Variables]
@include=#@#Vars.inc
@includegVar1=#SKINSPATH##MosaicShell\@Resources\gVars\Time.inc
@includeCoreDataVars=#SKINSPATH#..\CoreData\Vars.inc

H=#MinH#

; ---------------------------------------------------------------------------- ;
;                                   Functions                                  ;
; ---------------------------------------------------------------------------- ;

[Esc]
Measure=Plugin
Plugin=Hotkey
HotKey=ESCAPE
KeyDownAction=[!UpdateMeasure mToggleSet]
UpdateDivider=-1

[Func]
Measure=Script
ScriptFile=#@#Lua\Func.lua
UpdateDivider=1

[generateMixer]
Measure=Plugin
Plugin=PowershellRM
Scriptfile=#@#Powershell\generateMixer.ps1

@includeTweenNode1Style=#@#Includes\Animation#Animated#.inc

[mToggle]
Measure=Calc
Formula=1 - mToggle
IfCondition=mToggle = 0
IfTrueAction=[!UpdateMeasure ACTIONLOAD][!CommandMeasure Esc Start]
IfCondition2=mToggle = 1
IfTrueAction2=[!UpdateMeasure ACTIONUNLOAD][!CommandMeasure Esc Stop]
IfConditionMode=1
DynamicVariables=1
[mToggleSet]
Measure=Calc
Formula=mToggle
IfCondition=mToggle = 0
iftrueaction=[!UpdateMeasure mToggle]
ifconditionmode=1
Group=NUOL
Disabled=1

[ACTIONLOAD]
Measure=String
OnUpdateAction=[!CommandMeasure generateMixer "generateMixer"]
Disabled=1
Group=NUOL
; ["#@#Icons\GetIcons#Layout.fetch_icons#\GetIcons.exe"]

[ACTIONUNLOAD]
Measure=String
OnUpdateAction=[!UpdateMeasure ACTIONUNLOAD "Mixdeck\Main\Elements\ControlScreen"]
Disabled=1
Group=NUOL

[ACTIONREFRESH]
Measure=String
OnUpdateAction=[!UpdateMeasure mToggleSet][!Delay 500][!UpdateMeasure mToggle]
Disabled=1
Group=NUOL

[AppVolumeParent]
Measure=Plugin
Plugin=AppVolume
IgnoreSystemSound=1
ExcludeApp=#ExcludeApp#
UpdateDivider=1
[AppVolTester]
Measure=Plugin
Plugin=AppVolume
Parent=AppVolumeParent
Index=1
Substitute=".exe":""

@includeTray=#@#Includes\Tray#StayOnDesktop##Tray##TrayScroll#.inc
; Thanks DEATHCRAFTER

; ---------------------------------------------------------------------------- ;
;                                    Content                                   ;
; ---------------------------------------------------------------------------- ;

[Dum]
Meter=String
