[1.Shape]
Meter=Shape
MeterStyle=Action.Shape:S
[1.String]
Meter=String
MeterStyle=Set.String:S | Action.String:S
[1.Hotkey.Shape]
Meter=Shape
MeterStyle=Action.Hotkey.Shape:S
[1.Hotkey.String]
Meter=String
MeterStyle=Set.String:S | Action.Hotkey.String:S
[1.Delete.Shape]
Meter=Shape
MeterStyle=Action.Delete.Shape:S
[1.Delete.StringIcon]
Meter=String
MeterStyle=Set.String:S | Action.Delete.StringIcon:S

