[Rainmeter]
Update=0
OnRefreshAction=[!CommandMeasure p.ActionTimer "Execute 4"]
RightMouseUpAction=[!SkinCustomMenu]
SkinWidth=#Sec.W#
SkinHeight=#Sec.H#
DefaultDraggable=0
DefaultAlwaysOnTop=1
DefaultUpdateDivider=-1
ContextTitle=Back
ContextAction=[!WriteKeyValue Variables process.page (#process.page#-1) "#ROOTCONFIGPATH#Accessories\Welcome\Main.ini"][!Refresh]

[Variables]
@includeVars=#@#Vars.inc
process.page=0
process.tween_node_0=1
Sec.tween_time_0=900
process.tween_node_1=0
Sec.tween_time_1=1600
process.tween_node_prog=0
Sec.S=((#SCREENAREAWIDTH#/1920) < (#SCREENAREAHEIGHT#/1080) ? (#SCREENAREAWIDTH#/1920) : (#SCREENAREAHEIGHT#/1080))
; Sec.S=1.5
Sec.W=(800*#Sec.S#)
Sec.H=(600*#Sec.S#)
Sec.R=16
Sec.P=(20*#Sec.S#)
Sec.WindowPaddingY=(50*#Sec.S#)
Sec.WindowPaddingX=(120*#Sec.S#)

; ---------------------------------------------------------------------------- ;
;                                   Functions                                  ;
; ---------------------------------------------------------------------------- ;

[p.ActionTimer]
Measure=Plugin
Plugin=ActionTimer
ActionList1=Wait 100 | EnableNUOL | Start0 | Wait 800 | Start1
ActionList2=Rewind1 | Wait #Sec.tween_time_1# | Next
ActionList3=RewindAll | wait #Sec.tween_time_1# | Progress
ActionList4=Wait 100 | EnableNUOL | Start1 | CustomAction
Start0=[!CommandMeasure s.Tween "Start(0)"]
Start1=[!CommandMeasure s.Tween "Start(1)"]
Rewind1=[!CommandMeasure s.Tween "Rewind(1)"][!CommandMeasure s.Tween "Start(2)"]
RewindAll=[!CommandMeasure s.Tween "Rewind('All')"]
Next=[!WriteKeyValue Variables process.page (#process.page#+1) "#ROOTCONFIGPATH#Accessories\Welcome\Main.ini"][!Refresh]
Progress=[!WriteKeyValue Variables UserNameCheckVariable "[p.SysInfo.USER_NAME]" "#@#Vars.inc"][!WriteKeyValue Variables Sec.Page 1 "#ROOTCONFIGPATH#Main\Home.ini"][!WriteKeyValue Variables PostWelcome.Guide 1 "#ROOTCONFIGPATH#CoreShell\Home\Page1.inc"][!CommandMeasure Func "interactionBox('BatchInstall')"][!DeactivateConfig]
EnableNUOL=[!EnableMeasureGroup NUOL]
DynamicVariables=1

[s.Tween]
Measure=Script
ScriptFile=#@#LuaTween/Main.lua
TweenGroup=Tweenable
Tween0=Single | Variable | process.tween_node_0 | 0 | 1 | #Sec.tween_time_0#
Tween1=Single | Variable | process.tween_node_1 | 0 | 1 | #Sec.tween_time_1#
Tween2=Single | Variable | process.tween_node_prog | 0 | 1 | #Sec.tween_time_0#
Optional0=Easing InOutExpo | Group All
Optional1=Easing InOutExpo | Group All
Optional2=Easing InOutQuart
UpdateDivider=1

; ---------------------------------------------------------------------------- ;
;                                  MeterStyles                                 ;
; ---------------------------------------------------------------------------- ;

[Sec.String:S]
FontFace=#Set.Font#
AntiAlias=1
FontSize=(10*#Sec.s#)
clipstring=2
FontColor=#Set.Text_Color#
SolidColor=0,0,0,1
Container=a.Container

; ---------------------------------------------------------------------------- ;
;                                    Content                                   ;
; ---------------------------------------------------------------------------- ;

[Background.Shape]
Meter=Shape
Shape=Rectangle 0,0,#Sec.W#,#Sec.H#,#Sec.R# | StrokeWidth 0 | Fill Color #SEt.Pri_color# | Scale #process.tween_node_0#,#process.tween_node_0#
Shape2=Line (#Sec.P#),#Sec.P#,((#Sec.W#-#Sec.P#)*#process.tween_node_0#),#Sec.P# | StrokeWidth (2*#Sec.S#*#process.tween_node_0#) | Stroke Color #Set.Ter_color# | StrokeStartCap Round | StrokeEndCap Round
Shape3=Line (#Sec.P#),#Sec.P#,(((#Sec.W#-#Sec.P#*2)/5*(#process.page#+#process.tween_node_prog#))+#Sec.P#),#Sec.P# | StrokeWidth (8*#Sec.S#*#process.tween_node_0#) | Stroke Color #Set.Positive_color# | StrokeStartCap Round | StrokeEndCap Round
DynamicVariables=1
Group=Tweenable

[Background.Image]
Meter=Image
Y=(#Sec.H#*(1-0.5*#process.tween_node_1#))
H=(#Sec.H#/2)
W=(#Sec.W#)
PreserveAspectRatio=2
ImageAlpha=10
ImageName=#@#Images\CoreTextureOverlay.png
DynamicVariables=1
Group=Tweenable

[a.Container]
Meter=Shape
Shape=Rectangle 0,0,#Sec.W#,#Sec.H#,#Sec.R# | StrokeWidth 0 | Fill Color 0,0,0,(255*#process.tween_node_1#)
DynamicVariables=1
Group=Tweenable

@includePageContent=Page\#process.page#.inc
