
[DeviceBox0]
Meter=Shape
MeterStyle=Device:S
LeftMouseUpAction=[!WriteKeyValue Variables DeviceName "G2490W1G4 (NVIDIA High Definition Audio)" "#Sec.SaveLocation2#"][!WriteKeyValue Variables DeviceID "{0.0.0.00000000}.{3daa73c2-d01f-4ad0-8a68-3dfc1462428a}" "#Sec.SaveLocation2#"][!UpdateMeasure "Auto_Refresh:M"]
[DeviceName0]
Meter=String
Text=G2490W1G4 (NVIDIA High Definition Audio)
MeterStyle=Set.String:S | DeviceName:S

[DeviceBox1]
Meter=Shape
MeterStyle=Device:S
LeftMouseUpAction=[!WriteKeyValue Variables DeviceName "2490W1 (NVIDIA High Definition Audio)" "#Sec.SaveLocation2#"][!WriteKeyValue Variables DeviceID "{0.0.0.00000000}.{65f205c4-ab0c-4dfe-a1e6-5a29ecb69916}" "#Sec.SaveLocation2#"][!UpdateMeasure "Auto_Refresh:M"]
[DeviceName1]
Meter=String
Text=2490W1 (NVIDIA High Definition Audio)
MeterStyle=Set.String:S | DeviceName:S

[DeviceBox2]
Meter=Shape
MeterStyle=Device:S
LeftMouseUpAction=[!WriteKeyValue Variables DeviceName "Headphones (Realtek(R) Audio)" "#Sec.SaveLocation2#"][!WriteKeyValue Variables DeviceID "{0.0.0.00000000}.{839c2501-67af-4610-a51a-841d5c08787c}" "#Sec.SaveLocation2#"][!UpdateMeasure "Auto_Refresh:M"]
[DeviceName2]
Meter=String
Text=Headphones (Realtek(R) Audio)
MeterStyle=Set.String:S | DeviceName:S

[DeviceBox3]
Meter=Shape
MeterStyle=Device:S
LeftMouseUpAction=[!WriteKeyValue Variables DeviceName "Speakers (2- MAONO AU-BM10)" "#Sec.SaveLocation2#"][!WriteKeyValue Variables DeviceID "{0.0.0.00000000}.{e679f97d-c626-4aae-a937-5366049a6839}" "#Sec.SaveLocation2#"][!UpdateMeasure "Auto_Refresh:M"]
[DeviceName3]
Meter=String
Text=Speakers (2- MAONO AU-BM10)
MeterStyle=Set.String:S | DeviceName:S

[DeviceBox4]
Meter=Shape
MeterStyle=Device:S
LeftMouseUpAction=[!WriteKeyValue Variables DeviceName "Microphone (2- MAONO AU-BM10)" "#Sec.SaveLocation2#"][!WriteKeyValue Variables DeviceID "{0.0.1.00000000}.{93cb243a-ea98-4710-825f-c6aaef3a225b}" "#Sec.SaveLocation2#"][!UpdateMeasure "Auto_Refresh:M"]
[DeviceName4]
Meter=String
Text=Microphone (2- MAONO AU-BM10)
MeterStyle=Set.String:S | DeviceName:S

