[Rainmeter]
Update=#UpdateRate#
DefaultKeepOnScreen=0
DefaultAlwaysOnTop=2
DefaultClickThrough=1
DefaultSavePosition=0
; DynamicWindowSize=1
SkinWidth=(#skinW#)
SkinHeight=(#skinH#)

[Variables]
@includevars=#@#Vars.inc
@includeStyleVars=Vars\#Style#.inc
Sec.Name=MosaicShell
Sec.Icon=JaxCore_lnk
Sec.Action=["C:\Users\Jax\AppData\Roaming\Microsoft\Windows\Start Menu\Programs\MosaicShell.lnk"]

TweenNode1=0
TweenNode2=0

[LoadActions]
Measure=Plugin
Plugin=ActionTimer
ActionList1=Start0 | Wait #Style.Time1# | Start1 | Wait #Style.Time2# | Deactivate
ActionList2=Action
ActionList3=Wait #Style.Time1# | Action
ActionList4=Deactivate
Start0=[!CommandMeasure mTween "Start(0)"]
Start1=[!CommandMeasure mTween "Start(1)"]
Deactivate=[!DeactivateConfig]
Action=#Sec.Action#

[Execute]
Measure=String
String=#ExecuteAt#
IFMatch=0
ifmatchaction=[!CommandMeasure LoadActions "Execute 2"]
ifnotmatchaction=[!CommandMeasure LoadActions "Execute 3"]
OnUpdateAction=[!SetWindowPosition "#moveX#" "#moveY#" "#anchorX#" "#anchorY#"][!CommandMeasure LoadActions "Execute 1"]
UpdateDivider=-1

@includeStyle=Styles\#Style#.inc


