﻿[Rainmeter]
Update=(#VolumePeaks# = 1 ? 30 : 1000)
DefaultSavePosition=0
DefaultAlwaysOnTop=2
DefaultDraggable=0
DefaultSnapEdges=0
DefaultAlphaValue=1
DefaultHideOnMouseOver=0
DefaultFadeDuration=100
DefaultClickThrough=0
DefaultKeepOnScreen=0
DefaultAutoSelectScreen=0

DefaultUpdateDivider=-1
AccurateText=1
DynamicWindowSize=1
OnUnfocusAction=[!UpdateMeasure mToggleSet "Mixdeck\Main"]
@includeCtx=#SKINSPATH##MosaicShell\CoreShell\}{CtxItms.inc

[Variables]
@include=#@#Vars.inc
@includeLayoutVars=#ROOTCONFIGPATH#Main\Elements\ControlScreen\Vars\#Layout#.inc

W=(#Width#*#Scale#)
H=[Anchor:Y]
R=(#Corner#*#Scale#)

process.volume_icon_index=0

; ---------------------------------------------------------------------------- ;
;                                   Functions                                  ;
; ---------------------------------------------------------------------------- ;

[p.Focus]
Measure=Plugin
Plugin=Focus

[Func]
Measure=Script
ScriptFile=#@#Lua\Func.lua

[p.MeasureMouse]
Measure=Plugin
Plugin=Mouse
LeftMouseDragAction=[!CommandMeasure Func "DragMultiSlider($mouseX$)"]
LeftMouseUpAction=[!CommandMeasure Func "TermMultiSlider()"]
RelativeToSkin=1
RequireDragging=1
DynamicVariables=1

; [m.OnLoad]
; Measure=Calc
; Formula=Counter
; UpdateDivider=-1

[p.AudioLevel]
Measure=Plugin
Plugin=AudioLevel
Port=Output

[p.AudioLevel.DeviceList]
Measure=Plugin
Plugin=AudioLevel
Parent=p.AudioLevel
Type=DeviceList

[m.volbar_width]
Measure=Calc
Formula=#Layout.volbar_width#

@includeAnimationStyle=#@#Includes\Animation#Animated#.inc

; ---------------------------- AppVolume mechanism --------------------------- ;

[AppVolumeParent]
Measure=Plugin
Plugin=AppVolume
IgnoreSystemSound=1
ExcludeApp=#ExcludeApp#
UpdateDivider=1
@includeIconFetcher=#@#Includes\Icon#Layout.fetch_icons#.inc

[AppVol0]
Measure=Plugin
Plugin=Win7AudioPlugin
DynamicVariables=1
UpdateDivider=1
Group=UpdateWhenChange

[AppVolPer0]
Measure=Calc
Formula=Round(AppVol0)
Group=UpdateWhenChange
IfCondition=AppVolper0 < 0
iftrueaction=[!SetVariable process.volume_icon_index 0]
IfCondition2=(AppVolPer0 = 0)
IfTrueAction2=[!SetVariable process.volume_icon_index 1]
IfCondition3=(AppVolPer0 > 0) && (AppVolPer0 < 30)
IfTrueAction3=[!SetVariable process.volume_icon_index 2]
IfCondition4=(AppVolPer0 >= 30) && (AppVolPer0 < 70)
IfTrueAction4=[!SetVariable process.volume_icon_index 3]
IfCondition5=(AppVolPer0 >= 70)
IfTrueAction5=[!SetVariable process.volume_icon_index 4]
Substitute="-1":"Muted"

[FlyoutsTrigger]
Measure=Plugin
Plugin=Tessera
VolumeChangeAction=[!UpdateMeasureGroup UpdateWhenChange][!UpdateMeterGroup Volumebar][!Redraw]

; ---------------------------------------------------------------------------- ;
;                                  MeterStyleS                                 ;
; ---------------------------------------------------------------------------- ;

[Item.Background.Shape:S]
X=r
Y=r
LeftMouseDownAction=[!CommandMeasure A#CURRENTSECTION# "ToggleMute"][!UpdateMeasureGroup UpdateWhenChange][!UpdateMeter *][!Redraw]

[Item.Image:S]
W=(#IconSize#*#scale#)
H=(#IconSize#*#scale#)
DynamicVariables=1
Group=Icons
LeftMouseDownAction=[!CommandMeasure Ap#CURRENTSECTION# "ToggleMute"][!UpdateMeasureGroup UpdateWhenChange][!UpdateMeter *][!Redraw]
ImageName=#@#Images\AppIcons\[Ap#CURRENTSECTION#].exe.png
ImageAlpha=([Ap#CURRENTSECTION#:] = -1 ? 180 : 255)
UpdateDivider=1

[Item.Name.String:S]
Clipstring=1
MeasureName=App#CURRENTSECTION#
FontColor=#FontColor#,([App#CURRENTSECTION#:] = -1 ? 180 : 255)
LeftMouseDownAction=[!CommandMeasure App#CURRENTSECTION# "ToggleMute"][!UpdateMeasureGroup UpdateWhenChange][!UpdateMeter *][!Redraw]
StringCase=Proper
DynamicVariables=1

[Item.Shape:S]
X=(#name_width#*#scale#)
Y=r
DynamicVariables=1
MouseScrollUpAction=[!CommandMeasure AppVol#CURRENTSECTION# "ChangeVolume +#VolumeChangeLevel#"][!UpdateMeasure AppVol#CURRENTSECTION#][!UpdateMeasure AppVolPer#CURRENTSECTION#][!UpdateMeter *][!UpdateMeasureGroup UpdateWhenChange][!Redraw]
MouseScrollDownAction=[!CommandMeasure AppVol#CURRENTSECTION# "ChangeVolume -#VolumeChangeLevel#"][!UpdateMeasure AppVol#CURRENTSECTION#][!UpdateMeasure AppVolPer#CURRENTSECTION#][!UpdateMeter *][!UpdateMeasureGroup UpdateWhenChange][!Redraw]
LeftMouseDownAction=[!CommandMeasure Func "InitMultiSlider('#CURRENTSECTION#')"]
BackgroundStrokeColor=Stroke Color #BackVolColorLeave#
ForegroundStrokeColor=Stroke Color #Accent#
VolumePeakStrokeColor=Stroke Color #VolumePeakColor#
NodeExtends=Fill Color #AccentNode# | Scale 1,1
UpdateDivider=(#VolumePeaks# = 1 ? 1 : -1)
MouseOverAction=[!SetOption #CURRENTSECTION# BackgroundStrokeColor "Stroke Color #BackVolColorOver#"][!SetOption #CURRENTSECTION# NodeExtends "Fill Color #AccentNodeHover# | Scale 1.1,1.1"][!UpdateMeter #CURRENTSECTION#][!Redraw]
MouseLeaveAction=[!SetOption #CURRENTSECTION# BackgroundStrokeColor "Stroke Color #BackVolColorLeave#"][!SetOption #CURRENTSECTION# NodeExtends "Fill Color #AccentNode# | Scale 1,1"][!UpdateMeter #CURRENTSECTION#][!Redraw]

[Item.Vol.String:S]
Text=[App#CURRENTSECTION#]
StringAlign=RightCenter
DynamicVariables=1
Clipstring=1

[String:S]
FontFace=#Font#
AntiAlias=1
FontColor=#FontColor#
FontSize=(11*#Scale#)
SolidColor=0,0,0,1

; ---------------------------------------------------------------------------- ;
;                                    Content                                   ;
; ---------------------------------------------------------------------------- ;

[Background.Shape]
Meter=Shape
Shape=Rectangle 0,0,#W#,#H#,#R# | StrokeWidth 0 | Fill Color #background_color#,#Alpha#
DynamicVariables=1

@includeLayout=#ROOTCONFIGPATH#Main\Elements\ControlScreen\Layout\#Layout#.inc
