[Rainmeter]
Update=-1


[Variables]
@includeSetVar=#SKINSPATH#\#MosaicShell\@Resources\Version.inc
; @includeCheckTime=#@#Vars.inc
Sec.LatestCoreVer=N/A

[Dum]
meter=String

;============================

[WebParser]
Measure=WebParser
URL=https://raw.githubusercontent.com/uairhahs/MosaicShell/main/%40Resources/Version.inc
RegExp==(.*)$
Group=Updater
CodePage=1200
FinishAction=[!Delay 1000][!CommandMeasure LogicalScript "check()"]

; [LoopMeasure]
; Measure=Loop
; StartValue=0
; EndValue=(#Set.BackgroundCheckTime#*60)
; Increment=1
; IfCondition=LoopMeasure = (#Set.BackgroundCheckTime#*60)
; IfTrueAction=[!CommandMeasure WebParser "Reset"]

[mVer]
Measure=WebParser
URL=[WebParser]
Group=Updater
CodePage=1200
StringIndex=1
; [mVer]
; Measure=String
; String=10000
; OnUpdateAction=[!Delay 100][!CommandMeasure LogicalScript "check()"]
; UpdateDivider=-1

[Func]
Measure=Script
ScriptFile=#@#Lua\Func.lua

[LogicalScript]
Measure=Script
ScriptFile=Logic.lua
