[Rainmeter]
Update=-1
DefaultSavePosition=0
DefaultAlwaysOnTop=2
DefaultDraggable=0
DefaultSnapEdges=0
DefaultStartHidden=0
DefaultAlphaValue=255
DefaultHideOnMouseOver=0
DefaultFadeDuration=100
DefaultClickThrough=0
DefaultKeepOnScreen=1
DefaultAutoSelectScreen=1
DefaultUpdateDivider=-1

OnRefreshAction=[!Delay 100][!EnableMEasureGroup NUOL]
OnUnfocusAction=[!UpdateMeasure mToggle]

; ---------------------------------------------------------------------------- ;
;                                   Functions                                  ;
; ---------------------------------------------------------------------------- ;

[Focus]
Measure=Plugin
Plugin=Focus
FocusOnRefresh=1

[Variables]
@includeVars=#@#Vars.inc
@includeCacheVarsCtx=#@#CacheVars\Ctx.inc

[ActionTimer]
Measure=Plugin
Plugin=ActionTimer
DynamicVariables=1
; ActionList1=Repeat In,2,#Animation_Steps#
; ActionList2=HideFade | Repeat Out,2,#Animation_Steps# | Hide
ActionList1=Show
ActionList2=Hide
Show=[!ShowFade]
HideFade=[!HideFade]
Hide=[!Hide][!UpdateMeasure CheckmToggleForParent][!DeactivateConfig]
In=[!CommandMeasure SlideAnimation "tweenAnimation('in')"]
Out=[!CommandMeasure SlideAnimation "tweenAnimation('out')"]

[Func]
Measure=Script
ScriptFile=#@#lua\Func.lua
[ActiveChecker]
Measure=Plugin
Plugin=ConfigActive
ConfigName=#MosaicShell\Main

[mToggle]
Measure=String
Formula=1 - mToggle
IfCondition=mToggle = 0
IfTrueAction=[!CommandMeasure ActionTimer "Execute 2"][!DisableMeasure #CURRENTSECTION#]
IfCondition2=mToggle = 1
IfTrueAction2=
IfConditionMode=1
DynamicVariables=1
Disabled=1
Group=NUOL
[CheckmToggleForParent]
Measure=String
String=#Ctx.Parent.Toggle#
IfMatch=1
IfMatchAction=[!EnableMeasure mToggle "#Ctx.Parent#"][!CommandMeasure Focus "#Ctx.Parent#"]
IfNotMatchaction=[!DeactivateConfig]
IfMatchMode=1
Disabled=1
Group=NUOL

[CurPos.X]
Measure=Plugin
Plugin=MouseXY
Dimension=X
Group=CurPos.XY
UpdateDivider=-1
[CurPos.Y]
Measure=Plugin
Plugin=MouseXY
Dimension=Y
Group=CurPos.XY
UpdateDivider=-1

; ---------------------------------------------------------------------------- ;
;                                  MeterStyles                                 ;
; ---------------------------------------------------------------------------- ;

@includeCtxStyles=CtxStyles.inc

; ---------------------------------------------------------------------------- ;
;                          Context option meter styles                         ;
; ---------------------------------------------------------------------------- ;

[Refresh:Act]
LeftMouseUpAction=[!Refresh "#Sec.Skin#\Main"][!CommandMeasure ActionTimer "Execute 2"]
[Refresh:Text]
Text=Refresh
[Position:Act]
LeftMouseUpAction=[!CommandMeasure Ctx.Move:M "OpenSub('#CURRENTSECTION#', 'Pos')"]
[Position:Text]
Text=Align...
[Rainmeter:Act]
LeftMouseUpAction=[!CommandMeasure Ctx.Move:M "OpenSub('#CURRENTSECTION#', 'Rainmeter')"]
[Rainmeter:Text]
Text=Rainmeter actions...
[ZPOS:Act]
LeftMouseUpAction=[!CommandMeasure Ctx.Move:M "OpenSub('#CURRENTSECTION#', 'ZPOS')"]
[ZPOS:Text]
Text=Change Z layer...
[Core:Act]
LeftMouseUpAction=[!CommandMeasure Func "corepage('#Sec.Skin#')"][!CommandMeasure ActionTimer "Execute 2"]
[Core:Text]
Text=Configure in Core
[Unload:Act]
LeftMouseUpAction=[!DeactivateConfig "#Sec.Skin#\Main"][!CommandMeasure ActionTimer "Execute 2"]
[Unload:Text]
Text=Unload
[Developer:Act]
LeftMouseUpAction=[!CommandMeasure Ctx.Move:M "OpenSub('#CURRENTSECTION#', 'Dev')"]
[Developer:Text]
Text=Developer tools

; ---------------------------------------------------------------------------- ;
;                                    Content                                   ;
; ---------------------------------------------------------------------------- ;


[Core]
Meter=Shape
Y=(#Ctx.P#+1)
Hidden=(1-#Sec.Ctx.Settings#)
MeterStyle=CtxBox:S | Core:Act
[CoreIcon]
Meter=Image
ImageAlpha=(150+105*#Sec.Ctx.Settings#)
MeterStyle=CtxIcon:S
[CoreText]
Meter=String
FontColor=#Set.Text_Color#,(150+105*#Sec.Ctx.Settings#)
MeterStyle=Ctx.String:S | CtxText:S | Core:Text

[Divider1]
Meter=Shape
MeterStyle=Ctx.Div:S

[Position]
Meter=Shape
Hidden=(1-#Sec.Ctx.Pos#)
MeterStyle=CtxBox:S | Position:Act
[PositionIcon]
Meter=Image
ImageAlpha=(150+105*#Sec.Ctx.Pos#)
MeterStyle=CtxIcon:S
[PositionText]
Meter=String
FontColor=#Set.Text_Color#,(150+105*#Sec.Ctx.Pos#)
MeterStyle=Ctx.String:S | CtxText:S | Position:Text
[PositionTextIcon]
Meter=String
Hidden=(1-#Sec.Ctx.Pos#)
MeterStyle=Ctx.String:S | CtxTextIcon:S

[ZPOS]
Meter=Shape
Hidden=(#Sec.Ctx.Core#)
MeterStyle=CtxBox:S | ZPOS:Act
[ZPOSIcon]
Meter=Image
ImageAlpha=(255-105*#Sec.Ctx.Core#)
MeterStyle=CtxIcon:S
[ZPOSText]
Meter=String
FontColor=#Set.Text_Color#,(255-105*#Sec.Ctx.Core#)
MeterStyle=Ctx.String:S | CtxText:S | ZPOS:Text
[ZPOSTextIcon]
Meter=String
Hidden=(#Sec.Ctx.Core#)
MeterStyle=Ctx.String:S | CtxTextIcon:S

[Divider2]
Meter=Shape
MeterStyle=Ctx.Div:S

[Refresh]
Meter=Shape
MeterStyle=CtxBox:S | Refresh:Act
[RefreshIcon]
Meter=Image
MeterStyle=CtxIcon:S
[RefreshText]
Meter=String
MeterStyle=Ctx.String:S | CtxText:S | Refresh:Text

[Unload]
Meter=Shape
MeterStyle=CtxBox:S | Unload:Act
[UnloadIcon]
Meter=Image
MeterStyle=CtxIcon:S
[UnloadText]
Meter=String
MeterStyle=Ctx.String:S | CtxText:S | Unload:Text

[RainmeterShape]
Meter=Shape
MeterStyle=CtxBox:S | Rainmeter:Act
[RainmeterIcon]
Meter=Image
MeterStyle=CtxIcon:S
[RainmeterText]
Meter=String
MeterStyle=Ctx.String:S | CtxText:S | Rainmeter:Text
[RainmeterTextIcon]
Meter=String
MeterStyle=Ctx.String:S | CtxTextIcon:S

[Divider3]
Meter=Shape
MeterStyle=Ctx.Div:S

[Developer]
Meter=Shape
MeterStyle=CtxBox:S | Developer:Act
[DeveloperIcon]
Meter=Image
MeterStyle=CtxIcon:S
[DeveloperText]
Meter=String
MeterStyle=Ctx.String:S | CtxText:S | Developer:Text
[DeveloperTextIcon]
Meter=String
MeterStyle=Ctx.String:S | CtxTextIcon:S

[EndAnchor]
Meter=String
X=r
Y=(#Ctx.BoxH#/2*#Ctx.S#)r

