using FluentAssertions;
using MosaicShell.Core.Install;
using MosaicShell.Core.Update;

namespace MosaicShell.Core.Tests
{
    public class ReleaseAssetChecksumsTests
    {
        private const string SetupHash = "9f2c1b4a7d3e6058fa11cc2b9e4d7f0a3b6c8d1e2f405162738495a6b7c8d9e0";
        private const string ZipHash = "1122334455667788990011223344556677889900112233445566778899001122";

        [Fact]
        public void Parses_the_standard_sha256sum_two_space_format()
        {
            string body = $"{SetupHash}  MosaicShell-Setup-2026.9.7-b19.exe\n{ZipHash}  MosaicShell-portable.zip\n";

            ReleaseAssetChecksums checksums = ReleaseAssetChecksums.Parse(body);

            _ = checksums.TryGet("MosaicShell-Setup-2026.9.7-b19.exe").Should().Be(SetupHash);
            _ = checksums.TryGet("MosaicShell-portable.zip").Should().Be(ZipHash);
        }

        [Fact]
        public void Parses_single_space_and_binary_star_variants()
        {
            string body = $"{SetupHash} Setup.exe\n{ZipHash} *portable.zip";

            ReleaseAssetChecksums checksums = ReleaseAssetChecksums.Parse(body);

            _ = checksums.TryGet("Setup.exe").Should().Be(SetupHash);
            _ = checksums.TryGet("portable.zip").Should().Be(ZipHash);
        }

        [Fact]
        public void Lookup_is_case_insensitive_on_name_and_normalizes_hash_case()
        {
            ReleaseAssetChecksums checksums = ReleaseAssetChecksums.Parse($"{SetupHash.ToUpperInvariant()}  Setup.exe");

            _ = checksums.TryGet("setup.EXE").Should().Be(SetupHash);
        }

        [Fact]
        public void Ignores_blank_lines_comments_and_malformed_rows()
        {
            string body = $"""
                # generated by CI

                not-a-hash  Setup.exe
                {ZipHash}
                {SetupHash}  Good.exe
                """;

            ReleaseAssetChecksums checksums = ReleaseAssetChecksums.Parse(body);

            _ = checksums.Count.Should().Be(1);
            _ = checksums.TryGet("Good.exe").Should().Be(SetupHash);
        }

        [Fact]
        public void Strips_a_leading_path_from_the_name()
        {
            ReleaseAssetChecksums checksums = ReleaseAssetChecksums.Parse($"{SetupHash}  ./stage/Setup.exe");

            _ = checksums.TryGet("Setup.exe").Should().Be(SetupHash);
        }

        [Fact]
        public void Empty_body_yields_an_empty_set()
        {
            _ = ReleaseAssetChecksums.Parse("").Count.Should().Be(0);
            _ = ReleaseAssetChecksums.Parse(null).Count.Should().Be(0);
        }

        [Fact]
        public void Unknown_name_returns_null()
        {
            ReleaseAssetChecksums checksums = ReleaseAssetChecksums.Parse($"{SetupHash}  Setup.exe");

            _ = checksums.TryGet("Other.exe").Should().BeNull();
        }

        [Fact]
        public void Checksum_asset_is_selected_by_the_published_file_name()
        {
            List<UpdateChecker.GhAsset> assets =
            [
                new() { Name = "MosaicShell-Setup.exe", BrowserDownloadUrl = "https://example.invalid/s.exe" },
                new() { Name = ReleaseAssetChecksums.FileName, BrowserDownloadUrl = "https://example.invalid/sums.txt" },
            ];

            UpdateChecker.GhAsset? found = UpdateChecker.SelectChecksumAsset(assets);

            _ = found!.BrowserDownloadUrl.Should().Be("https://example.invalid/sums.txt");
        }

        [Fact]
        public void Checksum_asset_is_null_when_ci_did_not_publish_one()
        {
            List<UpdateChecker.GhAsset> assets =
            [
                new() { Name = "MosaicShell-Setup.exe", BrowserDownloadUrl = "https://example.invalid/s.exe" },
            ];

            _ = UpdateChecker.SelectChecksumAsset(assets).Should().BeNull();
        }

        [Fact]
        public void Downloaded_asset_carries_the_checksum_through_to_the_downloader()
        {
            ReleaseAssetChecksums checksums = ReleaseAssetChecksums.Parse($"{SetupHash}  MosaicShell-Setup.exe");
            UpdateCheckResult check = new(
                UpdateAvailable: true,
                LatestVersion: "2026.9.7-b19",
                CurrentVersion: "2026.9.6-b18",
                ReleaseUrl: null,
                SetupDownloadUrl: "https://example.invalid/MosaicShell-Setup.exe",
                SetupFileName: "MosaicShell-Setup.exe",
                SetupSha256: checksums.TryGet("MosaicShell-Setup.exe"));

            ReleaseAsset asset = UpdateChecker.BuildSetupAsset(check);

            _ = asset.Url.Should().Be("https://example.invalid/MosaicShell-Setup.exe");
            _ = asset.FileName.Should().Be("MosaicShell-Setup.exe");
            _ = asset.Sha256.Should().Be(SetupHash);
        }

        [Fact]
        public void Missing_checksum_leaves_the_asset_unverified_rather_than_inventing_one()
        {
            UpdateCheckResult check = new(
                UpdateAvailable: true,
                LatestVersion: "2026.9.7-b19",
                CurrentVersion: "2026.9.6-b18",
                ReleaseUrl: null,
                SetupDownloadUrl: "https://example.invalid/MosaicShell-Setup.exe",
                SetupFileName: "MosaicShell-Setup.exe");

            _ = UpdateChecker.BuildSetupAsset(check).Sha256.Should().BeNull();
        }
    }
}
