

[Title.3_5]
Meter=String
Text="Change log v3.5"
MeterStyle=Sec.String:S | Style.Title:S

[Description.3_5.0]
Meter=String
Text="• New shortcuts editor accessible within the start menu!#CRLF#• New shortcuts module, with reactive elements#CRLF#• HotApps is now a module#CRLF#• New PowerControl module#CRLF#• Taskbar will now be activated#CRLF#• Fixed multiple critical issues"
MeterStyle=Sec.String:S | Style.Description:S

[Title.3_3]
Meter=String
Text="Change log v3.3 - 3.4"
Y=(#Sec.P#)R
MeterStyle=Sec.String:S | Style.Title:S

[Description.3_3.0]
Meter=String
Text="• Added a setup wizard for convenient setup#CRLF#• Fixed sleep not working properly#CRLF#• Fixed critical issuee where user can't change any options#CRLF#• Added button linking to page to change shortcuts"
MeterStyle=Sec.String:S | Style.Description:S

[Title.3_2]
Meter=String
Text="Change log v3.2"
Y=(#Sec.P#)R
MeterStyle=Sec.String:S | Style.Title:S

[Description.3_2.0]
Meter=String
Text="• Fixed multiple UI and background issues"
MeterStyle=Sec.String:S | Style.Description:S
